-- Table for tracking invitations that an Edge Function or Database Webhook can pick up
CREATE TABLE IF NOT EXISTS public.pending_invites (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT NOT NULL,
  invited_by UUID REFERENCES auth.users(id),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  processed_at TIMESTAMPTZ -- When the Edge Function actually sent the invite
);

-- Enable RLS and add basic policy
ALTER TABLE public.pending_invites ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can create invites" ON public.pending_invites FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Users can see their own invites" ON public.pending_invites FOR SELECT USING (auth.uid() = invited_by);

-- Function to invite a user by email via RPC
-- This should be run in the Supabase SQL Editor
CREATE OR REPLACE FUNCTION public.invite_user_by_email(target_email TEXT)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER -- This allows the function to run with service role privileges
AS $$
BEGIN
  INSERT INTO public.pending_invites (email, invited_by)
  VALUES (target_email, auth.uid());
END;
$$;
