-- Fix Ukrainian welcome title
INSERT INTO ui_translations (key, lang, value) 
VALUES ('doc_welcome_title', 'uk', 'Ласкаво просимо до Aliolo')
ON CONFLICT (key, lang) DO UPDATE SET value = EXCLUDED.value;

-- doc_tab_general translations
INSERT INTO ui_translations (key, lang, value) VALUES
('doc_tab_general', 'en', 'General'),
('doc_tab_general', 'id', 'Umum'),
('doc_tab_general', 'bg', 'Общи'),
('doc_tab_general', 'cs', 'Obecné'),
('doc_tab_general', 'da', 'Generelt'),
('doc_tab_general', 'de', 'Allgemein'),
('doc_tab_general', 'et', 'Üldine'),
('doc_tab_general', 'es', 'General'),
('doc_tab_general', 'fr', 'Général'),
('doc_tab_general', 'ga', 'Ginearálta'),
('doc_tab_general', 'hr', 'Općenito'),
('doc_tab_general', 'it', 'Generale'),
('doc_tab_general', 'lv', 'Vispārīgi'),
('doc_tab_general', 'lt', 'Bendra'),
('doc_tab_general', 'hu', 'Általános'),
('doc_tab_general', 'mt', 'Ġenerali'),
('doc_tab_general', 'nl', 'Algemeen'),
('doc_tab_general', 'pl', 'Ogólne'),
('doc_tab_general', 'pt', 'Geral'),
('doc_tab_general', 'ro', 'General'),
('doc_tab_general', 'sk', 'Všeobecné'),
('doc_tab_general', 'sl', 'Splošno'),
('doc_tab_general', 'fi', 'Yleinen'),
('doc_tab_general', 'sv', 'Allmänt'),
('doc_tab_general', 'tl', 'Pangkalahatan'),
('doc_tab_general', 'vi', 'Chung'),
('doc_tab_general', 'tr', 'Genel'),
('doc_tab_general', 'el', 'Γενικά'),
('doc_tab_general', 'uk', 'Загальні'),
('doc_tab_general', 'ar', 'عام'),
('doc_tab_general', 'hi', 'सामान्य'),
('doc_tab_general', 'zh', '常规'),
('doc_tab_general', 'ja', '一般'),
('doc_tab_general', 'ko', '일반')
ON CONFLICT (key, lang) DO UPDATE SET value = EXCLUDED.value;

-- doc_tab_learning translations
INSERT INTO ui_translations (key, lang, value) VALUES
('doc_tab_learning', 'en', 'Learning & Testing'),
('doc_tab_learning', 'id', 'Pembelajaran & Pengujian'),
('doc_tab_learning', 'bg', 'Обучение и Тестване'),
('doc_tab_learning', 'cs', 'Učení a Testování'),
('doc_tab_learning', 'da', 'Læring og Test'),
('doc_tab_learning', 'de', 'Lernen & Testen'),
('doc_tab_learning', 'et', 'Õppimine ja Testimine'),
('doc_tab_learning', 'es', 'Aprendizaje y Pruebas'),
('doc_tab_learning', 'fr', 'Apprentissage et Tests'),
('doc_tab_learning', 'ga', 'Foghlaim & Tástáil'),
('doc_tab_learning', 'hr', 'Učenje i Testiranje'),
('doc_tab_learning', 'it', 'Apprendimento e Test'),
('doc_tab_learning', 'lv', 'Mācīšanās un Testēšana'),
('doc_tab_learning', 'lt', 'Mokymasis ir Testavimas'),
('doc_tab_learning', 'hu', 'Tanulás és Tesztelés'),
('doc_tab_learning', 'mt', 'Tagħlim u Ittestjar'),
('doc_tab_learning', 'nl', 'Leren & Testen'),
('doc_tab_learning', 'pl', 'Nauka i Testowanie'),
('doc_tab_learning', 'pt', 'Aprendizagem e Testes'),
('doc_tab_learning', 'ro', 'Învățare și Testare'),
('doc_tab_learning', 'sk', 'Učení a Testovanie'),
('doc_tab_learning', 'sl', 'Učenje in Testiranje'),
('doc_tab_learning', 'fi', 'Oppiminen ja Testaus'),
('doc_tab_learning', 'sv', 'Inlärning & Testning'),
('doc_tab_learning', 'tl', 'Pag-aaral at Pagsusuri'),
('doc_tab_learning', 'vi', 'Học tập & Kiểm tra'),
('doc_tab_learning', 'tr', 'Öğrenme ve Test Etme'),
('doc_tab_learning', 'el', 'Μάθηση & Δοκιμή'),
('doc_tab_learning', 'uk', 'Навчання та Тестування'),
('doc_tab_learning', 'ar', 'التعلم والاختبار'),
('doc_tab_learning', 'hi', 'सीखना और परीक्षण'),
('doc_tab_learning', 'zh', '学习与测试'),
('doc_tab_learning', 'ja', '学習とテスト'),
('doc_tab_learning', 'ko', '학습 및 테스트')
ON CONFLICT (key, lang) DO UPDATE SET value = EXCLUDED.value;

-- doc_tab_creator translations
INSERT INTO ui_translations (key, lang, value) VALUES
('doc_tab_creator', 'en', 'Creator Guide'),
('doc_tab_creator', 'id', 'Panduan Kreator'),
('doc_tab_creator', 'bg', 'Ръководство за Създатели'),
('doc_tab_creator', 'cs', 'Průvodce pro Tvůrce'),
('doc_tab_creator', 'da', 'Skaberguide'),
('doc_tab_creator', 'de', 'Schöpfer-Leitfaden'),
('doc_tab_creator', 'et', 'Loojajuhend'),
('doc_tab_creator', 'es', 'Guía del Creador'),
('doc_tab_creator', 'fr', 'Guide du Créateur'),
('doc_tab_creator', 'ga', 'Treoir don Chruthaitheoir'),
('doc_tab_creator', 'hr', 'Vodič za Stvaratelje'),
('doc_tab_creator', 'it', 'Guida per i Creatori'),
('doc_tab_creator', 'lv', 'Veidotāju Rokasgrāmata'),
('doc_tab_creator', 'lt', 'Kūrėjo Vadovas'),
('doc_tab_creator', 'hu', 'Alkotói Útmutató'),
('doc_tab_creator', 'mt', 'Gwida għall-Ħallieqa'),
('doc_tab_creator', 'nl', 'Creator-gids'),
('doc_tab_creator', 'pl', 'Przewodnik Twórcy'),
('doc_tab_creator', 'pt', 'Guia do Criador'),
('doc_tab_creator', 'ro', 'Ghidul Creatorului'),
('doc_tab_creator', 'sk', 'Sprievodca pre Tvorcov'),
('doc_tab_creator', 'sl', 'Vodnik za Ustvarjalce'),
('doc_tab_creator', 'fi', 'Tekijän Opas'),
('doc_tab_creator', 'sv', 'Skaparguide'),
('doc_tab_creator', 'tl', 'Gabay ng Tagalikha'),
('doc_tab_creator', 'vi', 'Hướng dẫn cho Người sáng tạo'),
('doc_tab_creator', 'tr', 'Oluşturucu Kılavuzu'),
('doc_tab_creator', 'el', 'Οδηγός Δημιουργού'),
('doc_tab_creator', 'uk', 'Посібник для Творців'),
('doc_tab_creator', 'ar', 'دليل المنشئ'),
('doc_tab_creator', 'hi', 'निर्माता गाइड'),
('doc_tab_creator', 'zh', '创建者指南'),
('doc_tab_creator', 'ja', 'クリエイターガイド'),
('doc_tab_creator', 'ko', '크리에이터 가이드')
ON CONFLICT (key, lang) DO UPDATE SET value = EXCLUDED.value;
