-- Generated from api/config/curated_taxonomy.json
-- Applies the curated Aliolo taxonomy without touching user-created content.
-- Review before running against production data.
-- Do not wrap this file in SQL BEGIN/COMMIT when running through Durable Objects or D1 APIs.

-- Update pillar names and descriptions by sort order.
UPDATE pillars SET name = 'Education', description = 'Core learning topics such as early concepts, arithmetic, and writing systems.' WHERE sort_order = 1;
UPDATE pillars SET name = 'Animals & Nature', description = 'Animals, insects, and nature-related topics.' WHERE sort_order = 2;
UPDATE pillars SET name = 'Human Body & Health', description = 'The human body, anatomy, body systems, and health topics such as nutrition and wellbeing.' WHERE sort_order = 3;
UPDATE pillars SET name = 'World & Geography', description = 'Countries, flags, landmarks, and notable places around the world.' WHERE sort_order = 4;
UPDATE pillars SET name = 'Arts & Culture', description = 'Art, architecture, music, food, and history across cultures.' WHERE sort_order = 5;
UPDATE pillars SET name = 'Sports & Recreation', description = 'Sports and recreation topics centered on games and physical activity.' WHERE sort_order = 6;
UPDATE pillars SET name = 'Engineering & Transport', description = 'Vehicles, machines, and engineered equipment.' WHERE sort_order = 7;
UPDATE pillars SET name = 'Other', description = 'Topics that do not fit clearly elsewhere.' WHERE sort_order = 8;

-- Upsert curated folders.
INSERT INTO folders (id, pillar_id, owner_id, name, names, created_at, updated_at) SELECT 'fold_education_add_subtract', p.id, COALESCE((SELECT id FROM profiles WHERE username = 'Aliolo' LIMIT 1), (SELECT owner_id FROM subjects LIMIT 1)), 'Add & Subtract', '{}', COALESCE((SELECT created_at FROM folders WHERE id = 'fold_education_add_subtract'), CURRENT_TIMESTAMP), CURRENT_TIMESTAMP FROM pillars p WHERE p.sort_order = 1 ON CONFLICT(id) DO UPDATE SET pillar_id = excluded.pillar_id, owner_id = excluded.owner_id, name = excluded.name, names = excluded.names, updated_at = CURRENT_TIMESTAMP;
INSERT INTO folders (id, pillar_id, owner_id, name, names, created_at, updated_at) SELECT 'fold_education_multiply_divide', p.id, COALESCE((SELECT id FROM profiles WHERE username = 'Aliolo' LIMIT 1), (SELECT owner_id FROM subjects LIMIT 1)), 'Multiply & Divide', '{}', COALESCE((SELECT created_at FROM folders WHERE id = 'fold_education_multiply_divide'), CURRENT_TIMESTAMP), CURRENT_TIMESTAMP FROM pillars p WHERE p.sort_order = 1 ON CONFLICT(id) DO UPDATE SET pillar_id = excluded.pillar_id, owner_id = excluded.owner_id, name = excluded.name, names = excluded.names, updated_at = CURRENT_TIMESTAMP;
INSERT INTO folders (id, pillar_id, owner_id, name, names, created_at, updated_at) SELECT 'fold_education_languages', p.id, COALESCE((SELECT id FROM profiles WHERE username = 'Aliolo' LIMIT 1), (SELECT owner_id FROM subjects LIMIT 1)), 'Languages', '{}', COALESCE((SELECT created_at FROM folders WHERE id = 'fold_education_languages'), CURRENT_TIMESTAMP), CURRENT_TIMESTAMP FROM pillars p WHERE p.sort_order = 1 ON CONFLICT(id) DO UPDATE SET pillar_id = excluded.pillar_id, owner_id = excluded.owner_id, name = excluded.name, names = excluded.names, updated_at = CURRENT_TIMESTAMP;
INSERT INTO folders (id, pillar_id, owner_id, name, names, created_at, updated_at) SELECT 'fold_world_flags', p.id, COALESCE((SELECT id FROM profiles WHERE username = 'Aliolo' LIMIT 1), (SELECT owner_id FROM subjects LIMIT 1)), 'Flags', '{}', COALESCE((SELECT created_at FROM folders WHERE id = 'fold_world_flags'), CURRENT_TIMESTAMP), CURRENT_TIMESTAMP FROM pillars p WHERE p.sort_order = 4 ON CONFLICT(id) DO UPDATE SET pillar_id = excluded.pillar_id, owner_id = excluded.owner_id, name = excluded.name, names = excluded.names, updated_at = CURRENT_TIMESTAMP;
INSERT INTO folders (id, pillar_id, owner_id, name, names, created_at, updated_at) SELECT 'fold_world_landmarks', p.id, COALESCE((SELECT id FROM profiles WHERE username = 'Aliolo' LIMIT 1), (SELECT owner_id FROM subjects LIMIT 1)), 'Landmarks', '{}', COALESCE((SELECT created_at FROM folders WHERE id = 'fold_world_landmarks'), CURRENT_TIMESTAMP), CURRENT_TIMESTAMP FROM pillars p WHERE p.sort_order = 4 ON CONFLICT(id) DO UPDATE SET pillar_id = excluded.pillar_id, owner_id = excluded.owner_id, name = excluded.name, names = excluded.names, updated_at = CURRENT_TIMESTAMP;
INSERT INTO folders (id, pillar_id, owner_id, name, names, created_at, updated_at) SELECT 'fold_arts_music', p.id, COALESCE((SELECT id FROM profiles WHERE username = 'Aliolo' LIMIT 1), (SELECT owner_id FROM subjects LIMIT 1)), 'Music', '{}', COALESCE((SELECT created_at FROM folders WHERE id = 'fold_arts_music'), CURRENT_TIMESTAMP), CURRENT_TIMESTAMP FROM pillars p WHERE p.sort_order = 5 ON CONFLICT(id) DO UPDATE SET pillar_id = excluded.pillar_id, owner_id = excluded.owner_id, name = excluded.name, names = excluded.names, updated_at = CURRENT_TIMESTAMP;
INSERT INTO folders (id, pillar_id, owner_id, name, names, created_at, updated_at) SELECT 'fold_engineering_vehicles', p.id, COALESCE((SELECT id FROM profiles WHERE username = 'Aliolo' LIMIT 1), (SELECT owner_id FROM subjects LIMIT 1)), 'Vehicles', '{}', COALESCE((SELECT created_at FROM folders WHERE id = 'fold_engineering_vehicles'), CURRENT_TIMESTAMP), CURRENT_TIMESTAMP FROM pillars p WHERE p.sort_order = 7 ON CONFLICT(id) DO UPDATE SET pillar_id = excluded.pillar_id, owner_id = excluded.owner_id, name = excluded.name, names = excluded.names, updated_at = CURRENT_TIMESTAMP;

-- Move curated subjects, rename them, and refresh descriptions.
UPDATE subjects SET pillar_id = (SELECT id FROM pillars WHERE sort_order = 1 LIMIT 1), folder_id = NULL, name = 'Colors', description = 'Learn to identify common colors.', updated_at = CURRENT_TIMESTAMP WHERE id = '0b84447d-3af3-4509-bdf6-c4e7fe822cc7';
UPDATE subjects SET pillar_id = (SELECT id FROM pillars WHERE sort_order = 1 LIMIT 1), folder_id = NULL, name = 'Counting', description = 'Practice counting numbers in order.', updated_at = CURRENT_TIMESTAMP WHERE id = '68232807-b9cd-4cff-872c-c398444f85e2';
UPDATE subjects SET pillar_id = (SELECT id FROM pillars WHERE sort_order = 1 LIMIT 1), folder_id = NULL, name = 'Numbers', description = 'Learn to recognize and name numbers.', updated_at = CURRENT_TIMESTAMP WHERE id = 'bc354f43-f9be-42a9-a7bc-ac400bd5e310';
UPDATE subjects SET pillar_id = (SELECT id FROM pillars WHERE sort_order = 1 LIMIT 1), folder_id = NULL, name = 'Planets of the Solar System', description = 'Learn to identify the planets of the solar system.', updated_at = CURRENT_TIMESTAMP WHERE id = '193530d9-3e12-422a-801f-a0af7799f235';
UPDATE subjects SET pillar_id = (SELECT id FROM pillars WHERE sort_order = 1 LIMIT 1), folder_id = NULL, name = 'Shapes 2D', description = 'Learn to identify common two-dimensional shapes.', updated_at = CURRENT_TIMESTAMP WHERE id = '031f918e-6afa-469b-97bc-48a65e565237';
UPDATE subjects SET pillar_id = (SELECT id FROM pillars WHERE sort_order = 1 LIMIT 1), folder_id = NULL, name = 'Shapes 3D', description = 'Learn to identify common three-dimensional shapes.', updated_at = CURRENT_TIMESTAMP WHERE id = '39636cfd-cb6a-4d1c-95a7-c30b5db1846a';
UPDATE subjects SET pillar_id = (SELECT id FROM pillars WHERE sort_order = 1 LIMIT 1), folder_id = 'fold_education_add_subtract', name = 'Addition 0-10', description = 'Practice addition with numbers from 0 to 10.', updated_at = CURRENT_TIMESTAMP WHERE id = 'de04da1c-9820-4e61-ae6b-bc7ed07eeb93';
UPDATE subjects SET pillar_id = (SELECT id FROM pillars WHERE sort_order = 1 LIMIT 1), folder_id = 'fold_education_add_subtract', name = 'Addition 11-20', description = 'Practice addition with numbers up to 20.', updated_at = CURRENT_TIMESTAMP WHERE id = '5e81da1f-f92c-44d2-b3cd-f921d05425df';
UPDATE subjects SET pillar_id = (SELECT id FROM pillars WHERE sort_order = 1 LIMIT 1), folder_id = 'fold_education_add_subtract', name = 'Subtraction 0-10', description = 'Practice subtraction with numbers from 0 to 10.', updated_at = CURRENT_TIMESTAMP WHERE id = 'ce04da1c-9820-4e61-ae6b-bc7ed07eeb93';
UPDATE subjects SET pillar_id = (SELECT id FROM pillars WHERE sort_order = 1 LIMIT 1), folder_id = 'fold_education_add_subtract', name = 'Subtraction 11-20', description = 'Practice subtraction with numbers up to 20.', updated_at = CURRENT_TIMESTAMP WHERE id = 'f59a0f9c-5d6d-4f2d-b426-eb9ca6bf2782';
UPDATE subjects SET pillar_id = (SELECT id FROM pillars WHERE sort_order = 1 LIMIT 1), folder_id = 'fold_education_multiply_divide', name = 'Multiplication by 1', description = 'Practice multiplication facts for 1.', updated_at = CURRENT_TIMESTAMP WHERE id = 'e104da1c-9820-4e61-ae6b-bc7ed07eeb93';
UPDATE subjects SET pillar_id = (SELECT id FROM pillars WHERE sort_order = 1 LIMIT 1), folder_id = 'fold_education_multiply_divide', name = 'Multiplication by 2', description = 'Practice multiplication facts for 2.', updated_at = CURRENT_TIMESTAMP WHERE id = 'e204da1c-9820-4e61-ae6b-bc7ed07eeb93';
UPDATE subjects SET pillar_id = (SELECT id FROM pillars WHERE sort_order = 1 LIMIT 1), folder_id = 'fold_education_multiply_divide', name = 'Multiplication by 3', description = 'Practice multiplication facts for 3.', updated_at = CURRENT_TIMESTAMP WHERE id = 'e304da1c-9820-4e61-ae6b-bc7ed07eeb93';
UPDATE subjects SET pillar_id = (SELECT id FROM pillars WHERE sort_order = 1 LIMIT 1), folder_id = 'fold_education_multiply_divide', name = 'Multiplication by 4', description = 'Practice multiplication facts for 4.', updated_at = CURRENT_TIMESTAMP WHERE id = 'e404da1c-9820-4e61-ae6b-bc7ed07eeb93';
UPDATE subjects SET pillar_id = (SELECT id FROM pillars WHERE sort_order = 1 LIMIT 1), folder_id = 'fold_education_multiply_divide', name = 'Multiplication by 5', description = 'Practice multiplication facts for 5.', updated_at = CURRENT_TIMESTAMP WHERE id = 'e504da1c-9820-4e61-ae6b-bc7ed07eeb93';
UPDATE subjects SET pillar_id = (SELECT id FROM pillars WHERE sort_order = 1 LIMIT 1), folder_id = 'fold_education_multiply_divide', name = 'Multiplication by 6', description = 'Practice multiplication facts for 6.', updated_at = CURRENT_TIMESTAMP WHERE id = 'e604da1c-9820-4e61-ae6b-bc7ed07eeb93';
UPDATE subjects SET pillar_id = (SELECT id FROM pillars WHERE sort_order = 1 LIMIT 1), folder_id = 'fold_education_multiply_divide', name = 'Multiplication by 7', description = 'Practice multiplication facts for 7.', updated_at = CURRENT_TIMESTAMP WHERE id = 'e704da1c-9820-4e61-ae6b-bc7ed07eeb93';
UPDATE subjects SET pillar_id = (SELECT id FROM pillars WHERE sort_order = 1 LIMIT 1), folder_id = 'fold_education_multiply_divide', name = 'Multiplication by 8', description = 'Practice multiplication facts for 8.', updated_at = CURRENT_TIMESTAMP WHERE id = 'e804da1c-9820-4e61-ae6b-bc7ed07eeb93';
UPDATE subjects SET pillar_id = (SELECT id FROM pillars WHERE sort_order = 1 LIMIT 1), folder_id = 'fold_education_multiply_divide', name = 'Multiplication by 9', description = 'Practice multiplication facts for 9.', updated_at = CURRENT_TIMESTAMP WHERE id = 'e904da1c-9820-4e61-ae6b-bc7ed07eeb93';
UPDATE subjects SET pillar_id = (SELECT id FROM pillars WHERE sort_order = 1 LIMIT 1), folder_id = 'fold_education_multiply_divide', name = 'Division by 1', description = 'Practice division facts with 1.', updated_at = CURRENT_TIMESTAMP WHERE id = 'd104da1c-9820-4e61-ae6b-bc7ed07eeb93';
UPDATE subjects SET pillar_id = (SELECT id FROM pillars WHERE sort_order = 1 LIMIT 1), folder_id = 'fold_education_multiply_divide', name = 'Division by 2', description = 'Practice division facts with 2.', updated_at = CURRENT_TIMESTAMP WHERE id = 'd204da1c-9820-4e61-ae6b-bc7ed07eeb93';
UPDATE subjects SET pillar_id = (SELECT id FROM pillars WHERE sort_order = 1 LIMIT 1), folder_id = 'fold_education_multiply_divide', name = 'Division by 3', description = 'Practice division facts with 3.', updated_at = CURRENT_TIMESTAMP WHERE id = 'd304da1c-9820-4e61-ae6b-bc7ed07eeb93';
UPDATE subjects SET pillar_id = (SELECT id FROM pillars WHERE sort_order = 1 LIMIT 1), folder_id = 'fold_education_multiply_divide', name = 'Division by 4', description = 'Practice division facts with 4.', updated_at = CURRENT_TIMESTAMP WHERE id = 'd404da1c-9820-4e61-ae6b-bc7ed07eeb93';
UPDATE subjects SET pillar_id = (SELECT id FROM pillars WHERE sort_order = 1 LIMIT 1), folder_id = 'fold_education_multiply_divide', name = 'Division by 5', description = 'Practice division facts with 5.', updated_at = CURRENT_TIMESTAMP WHERE id = 'd504da1c-9820-4e61-ae6b-bc7ed07eeb93';
UPDATE subjects SET pillar_id = (SELECT id FROM pillars WHERE sort_order = 1 LIMIT 1), folder_id = 'fold_education_multiply_divide', name = 'Division by 6', description = 'Practice division facts with 6.', updated_at = CURRENT_TIMESTAMP WHERE id = 'd604da1c-9820-4e61-ae6b-bc7ed07eeb93';
UPDATE subjects SET pillar_id = (SELECT id FROM pillars WHERE sort_order = 1 LIMIT 1), folder_id = 'fold_education_multiply_divide', name = 'Division by 7', description = 'Practice division facts with 7.', updated_at = CURRENT_TIMESTAMP WHERE id = 'd704da1c-9820-4e61-ae6b-bc7ed07eeb93';
UPDATE subjects SET pillar_id = (SELECT id FROM pillars WHERE sort_order = 1 LIMIT 1), folder_id = 'fold_education_multiply_divide', name = 'Division by 8', description = 'Practice division facts with 8.', updated_at = CURRENT_TIMESTAMP WHERE id = 'd804da1c-9820-4e61-ae6b-bc7ed07eeb93';
UPDATE subjects SET pillar_id = (SELECT id FROM pillars WHERE sort_order = 1 LIMIT 1), folder_id = 'fold_education_multiply_divide', name = 'Division by 9', description = 'Practice division facts with 9.', updated_at = CURRENT_TIMESTAMP WHERE id = 'd904da1c-9820-4e61-ae6b-bc7ed07eeb93';
UPDATE subjects SET pillar_id = (SELECT id FROM pillars WHERE sort_order = 1 LIMIT 1), folder_id = 'fold_education_languages', name = 'Arabic Alphabet', description = 'Learn the letters of the Arabic alphabet.', updated_at = CURRENT_TIMESTAMP WHERE id = '4f24f604-ae85-40d0-9a96-6816bf26b7bf';
UPDATE subjects SET pillar_id = (SELECT id FROM pillars WHERE sort_order = 1 LIMIT 1), folder_id = 'fold_education_languages', name = 'Bulgarian Alphabet', description = 'Learn the letters of the Bulgarian alphabet.', updated_at = CURRENT_TIMESTAMP WHERE id = 'c8c8c8c7-1f9d-4e2a-88fe-f809469916e0';
UPDATE subjects SET pillar_id = (SELECT id FROM pillars WHERE sort_order = 1 LIMIT 1), folder_id = 'fold_education_languages', name = 'Chinese Alphabet', description = 'Learn the symbols taught in this Chinese alphabet subject.', updated_at = CURRENT_TIMESTAMP WHERE id = '45efa767-a560-4ed8-a1f9-9d0ccecc9248';
UPDATE subjects SET pillar_id = (SELECT id FROM pillars WHERE sort_order = 1 LIMIT 1), folder_id = 'fold_education_languages', name = 'Croatian Alphabet', description = 'Learn the letters of the Croatian alphabet.', updated_at = CURRENT_TIMESTAMP WHERE id = 'ba87655b-9f97-4022-85e0-9868620998f0';
UPDATE subjects SET pillar_id = (SELECT id FROM pillars WHERE sort_order = 1 LIMIT 1), folder_id = 'fold_education_languages', name = 'Czech Alphabet', description = 'Learn the letters of the Czech alphabet.', updated_at = CURRENT_TIMESTAMP WHERE id = '83a02e6e-44b3-4629-9fc9-bd63ee6eafde';
UPDATE subjects SET pillar_id = (SELECT id FROM pillars WHERE sort_order = 1 LIMIT 1), folder_id = 'fold_education_languages', name = 'Danish Alphabet', description = 'Learn the letters of the Danish alphabet.', updated_at = CURRENT_TIMESTAMP WHERE id = '6cb3d0b9-b1e2-4075-ba89-8fc074e67229';
UPDATE subjects SET pillar_id = (SELECT id FROM pillars WHERE sort_order = 1 LIMIT 1), folder_id = 'fold_education_languages', name = 'Dutch Alphabet', description = 'Learn the letters of the Dutch alphabet.', updated_at = CURRENT_TIMESTAMP WHERE id = 'b5270f43-f604-4be9-a9e4-4f804b808690';
UPDATE subjects SET pillar_id = (SELECT id FROM pillars WHERE sort_order = 1 LIMIT 1), folder_id = 'fold_education_languages', name = 'English Alphabet', description = 'Learn the letters of the English alphabet.', updated_at = CURRENT_TIMESTAMP WHERE id = '4b04fa27-8bfe-4580-912e-5d5f171b2670';
UPDATE subjects SET pillar_id = (SELECT id FROM pillars WHERE sort_order = 1 LIMIT 1), folder_id = 'fold_education_languages', name = 'Estonian Alphabet', description = 'Learn the letters of the Estonian alphabet.', updated_at = CURRENT_TIMESTAMP WHERE id = '945210fa-6559-4723-9a7c-4e5e8397342d';
UPDATE subjects SET pillar_id = (SELECT id FROM pillars WHERE sort_order = 1 LIMIT 1), folder_id = 'fold_education_languages', name = 'Finnish Alphabet', description = 'Learn the letters of the Finnish alphabet.', updated_at = CURRENT_TIMESTAMP WHERE id = 'a88eb556-812c-4df0-8e9d-c9911a801f17';
UPDATE subjects SET pillar_id = (SELECT id FROM pillars WHERE sort_order = 1 LIMIT 1), folder_id = 'fold_education_languages', name = 'French Alphabet', description = 'Learn the letters of the French alphabet.', updated_at = CURRENT_TIMESTAMP WHERE id = '49154771-9b6b-42f6-8e4a-c1545ca0e94a';
UPDATE subjects SET pillar_id = (SELECT id FROM pillars WHERE sort_order = 1 LIMIT 1), folder_id = 'fold_education_languages', name = 'German Alphabet', description = 'Learn the letters of the German alphabet.', updated_at = CURRENT_TIMESTAMP WHERE id = 'a1a7cbe7-2f68-4870-ba26-966132f75ba9';
UPDATE subjects SET pillar_id = (SELECT id FROM pillars WHERE sort_order = 1 LIMIT 1), folder_id = 'fold_education_languages', name = 'Greek Alphabet', description = 'Learn the letters of the Greek alphabet.', updated_at = CURRENT_TIMESTAMP WHERE id = '8df8e8bf-7fe8-4e99-a0eb-0a05c43ed6da';
UPDATE subjects SET pillar_id = (SELECT id FROM pillars WHERE sort_order = 1 LIMIT 1), folder_id = 'fold_education_languages', name = 'Hindi Alphabet', description = 'Learn the symbols taught in this Hindi alphabet subject.', updated_at = CURRENT_TIMESTAMP WHERE id = '3bf13dae-ace5-4fa8-ac9c-f84a7ac5cfc5';
UPDATE subjects SET pillar_id = (SELECT id FROM pillars WHERE sort_order = 1 LIMIT 1), folder_id = 'fold_education_languages', name = 'Hungarian Alphabet', description = 'Learn the letters of the Hungarian alphabet.', updated_at = CURRENT_TIMESTAMP WHERE id = '8e92cfd0-de89-4c2e-adc2-04854e2ec456';
UPDATE subjects SET pillar_id = (SELECT id FROM pillars WHERE sort_order = 1 LIMIT 1), folder_id = 'fold_education_languages', name = 'Indonesian Alphabet', description = 'Learn the letters of the Indonesian alphabet.', updated_at = CURRENT_TIMESTAMP WHERE id = '09680efb-fc98-4f32-a9c8-1d0542ab9b81';
UPDATE subjects SET pillar_id = (SELECT id FROM pillars WHERE sort_order = 1 LIMIT 1), folder_id = 'fold_education_languages', name = 'Irish Alphabet', description = 'Learn the letters of the Irish alphabet.', updated_at = CURRENT_TIMESTAMP WHERE id = '282881e3-7516-481b-9894-7ff5796bb1f1';
UPDATE subjects SET pillar_id = (SELECT id FROM pillars WHERE sort_order = 1 LIMIT 1), folder_id = 'fold_education_languages', name = 'Italian Alphabet', description = 'Learn the letters of the Italian alphabet.', updated_at = CURRENT_TIMESTAMP WHERE id = '094d5bf3-5b22-4691-b652-dc07b490b97b';
UPDATE subjects SET pillar_id = (SELECT id FROM pillars WHERE sort_order = 1 LIMIT 1), folder_id = 'fold_education_languages', name = 'Japanese Alphabet', description = 'Learn the symbols taught in this Japanese alphabet subject.', updated_at = CURRENT_TIMESTAMP WHERE id = '68f5f724-3e4a-4c90-80c7-aee708c6b6cd';
UPDATE subjects SET pillar_id = (SELECT id FROM pillars WHERE sort_order = 1 LIMIT 1), folder_id = 'fold_education_languages', name = 'Korean Alphabet', description = 'Learn the symbols taught in this Korean alphabet subject.', updated_at = CURRENT_TIMESTAMP WHERE id = 'c6c33310-7a3f-4a5c-aef4-b37feb0662a4';
UPDATE subjects SET pillar_id = (SELECT id FROM pillars WHERE sort_order = 1 LIMIT 1), folder_id = 'fold_education_languages', name = 'Latvian Alphabet', description = 'Learn the letters of the Latvian alphabet.', updated_at = CURRENT_TIMESTAMP WHERE id = '8e5ead38-3dcb-472c-a690-f8aaa01960a6';
UPDATE subjects SET pillar_id = (SELECT id FROM pillars WHERE sort_order = 1 LIMIT 1), folder_id = 'fold_education_languages', name = 'Lithuanian Alphabet', description = 'Learn the letters of the Lithuanian alphabet.', updated_at = CURRENT_TIMESTAMP WHERE id = '79f58eab-ab28-4673-a9e6-f2258edda08c';
UPDATE subjects SET pillar_id = (SELECT id FROM pillars WHERE sort_order = 1 LIMIT 1), folder_id = 'fold_education_languages', name = 'Maltese Alphabet', description = 'Learn the letters of the Maltese alphabet.', updated_at = CURRENT_TIMESTAMP WHERE id = '576e6494-7f4a-4dbe-af0c-d80dbb9afb9b';
UPDATE subjects SET pillar_id = (SELECT id FROM pillars WHERE sort_order = 1 LIMIT 1), folder_id = 'fold_education_languages', name = 'Polish Alphabet', description = 'Learn the letters of the Polish alphabet.', updated_at = CURRENT_TIMESTAMP WHERE id = '0a0bddf4-1de5-46e5-8183-fff7eb96952a';
UPDATE subjects SET pillar_id = (SELECT id FROM pillars WHERE sort_order = 1 LIMIT 1), folder_id = 'fold_education_languages', name = 'Portuguese Alphabet', description = 'Learn the letters of the Portuguese alphabet.', updated_at = CURRENT_TIMESTAMP WHERE id = '9606b189-82b5-4fda-8339-8c7edf83de63';
UPDATE subjects SET pillar_id = (SELECT id FROM pillars WHERE sort_order = 1 LIMIT 1), folder_id = 'fold_education_languages', name = 'Romanian Alphabet', description = 'Learn the letters of the Romanian alphabet.', updated_at = CURRENT_TIMESTAMP WHERE id = 'c351bd64-25e7-4de8-9ee4-07875fb94ba4';
UPDATE subjects SET pillar_id = (SELECT id FROM pillars WHERE sort_order = 1 LIMIT 1), folder_id = 'fold_education_languages', name = 'Slovak Alphabet', description = 'Learn the letters of the Slovak alphabet.', updated_at = CURRENT_TIMESTAMP WHERE id = '860510ac-bf6b-4202-af32-93a469c71048';
UPDATE subjects SET pillar_id = (SELECT id FROM pillars WHERE sort_order = 1 LIMIT 1), folder_id = 'fold_education_languages', name = 'Slovenian Alphabet', description = 'Learn the letters of the Slovenian alphabet.', updated_at = CURRENT_TIMESTAMP WHERE id = 'b5ccb20a-d137-4e1d-aaab-090cbd6d9cf0';
UPDATE subjects SET pillar_id = (SELECT id FROM pillars WHERE sort_order = 1 LIMIT 1), folder_id = 'fold_education_languages', name = 'Spanish Alphabet', description = 'Learn the letters of the Spanish alphabet.', updated_at = CURRENT_TIMESTAMP WHERE id = '3fef9ea6-2e9d-45b1-87b0-75cce5adeedd';
UPDATE subjects SET pillar_id = (SELECT id FROM pillars WHERE sort_order = 1 LIMIT 1), folder_id = 'fold_education_languages', name = 'Swedish Alphabet', description = 'Learn the letters of the Swedish alphabet.', updated_at = CURRENT_TIMESTAMP WHERE id = '1e7fe8e3-9c52-44f9-b47a-a5dcd20c542c';
UPDATE subjects SET pillar_id = (SELECT id FROM pillars WHERE sort_order = 1 LIMIT 1), folder_id = 'fold_education_languages', name = 'Tagalog Alphabet', description = 'Learn the letters of the Tagalog alphabet.', updated_at = CURRENT_TIMESTAMP WHERE id = '74cb0940-1f03-4c29-bbcb-6f8a2b2d080b';
UPDATE subjects SET pillar_id = (SELECT id FROM pillars WHERE sort_order = 1 LIMIT 1), folder_id = 'fold_education_languages', name = 'Turkish Alphabet', description = 'Learn the letters of the Turkish alphabet.', updated_at = CURRENT_TIMESTAMP WHERE id = '03488dd6-cdb1-4320-9c67-2df16febfdb7';
UPDATE subjects SET pillar_id = (SELECT id FROM pillars WHERE sort_order = 1 LIMIT 1), folder_id = 'fold_education_languages', name = 'Ukrainian Alphabet', description = 'Learn the letters of the Ukrainian alphabet.', updated_at = CURRENT_TIMESTAMP WHERE id = '48d52b9d-329b-44be-95e4-c89c0d5e9fca';
UPDATE subjects SET pillar_id = (SELECT id FROM pillars WHERE sort_order = 1 LIMIT 1), folder_id = 'fold_education_languages', name = 'Vietnamese Alphabet', description = 'Learn the letters of the Vietnamese alphabet.', updated_at = CURRENT_TIMESTAMP WHERE id = '68aa38d7-499a-4ab4-a8e7-9d0b1701cb1a';
UPDATE subjects SET pillar_id = (SELECT id FROM pillars WHERE sort_order = 2 LIMIT 1), folder_id = NULL, name = 'Dog Breeds', description = 'Learn to identify common dog breeds.', updated_at = CURRENT_TIMESTAMP WHERE id = '6f3f66e2-2dce-4762-b7a0-e3e1e5c7dbb1';
UPDATE subjects SET pillar_id = (SELECT id FROM pillars WHERE sort_order = 2 LIMIT 1), folder_id = NULL, name = 'Domesticated Animals', description = 'Learn to identify animals commonly domesticated by people.', updated_at = CURRENT_TIMESTAMP WHERE id = 'a6b5b079-4b75-400d-a9c6-43c28c80c040';
UPDATE subjects SET pillar_id = (SELECT id FROM pillars WHERE sort_order = 2 LIMIT 1), folder_id = NULL, name = 'Most Colorful Insects', description = 'Learn to identify colorful insect species.', updated_at = CURRENT_TIMESTAMP WHERE id = '5319e962-cd18-4e74-9cd7-8092ebe1752c';
UPDATE subjects SET pillar_id = (SELECT id FROM pillars WHERE sort_order = 2 LIMIT 1), folder_id = NULL, name = 'Types of Sea Animals', description = 'Learn to identify different sea animals.', updated_at = CURRENT_TIMESTAMP WHERE id = '2450ccd1-b439-4ed1-8280-30de3f41e400';
UPDATE subjects SET pillar_id = (SELECT id FROM pillars WHERE sort_order = 3 LIMIT 1), folder_id = NULL, name = 'Bones of the Human Skeleton', description = 'Learn to identify major bones of the human skeleton.', updated_at = CURRENT_TIMESTAMP WHERE id = '25fff407-d9d1-4e29-a176-41ce01157c63';
UPDATE subjects SET pillar_id = (SELECT id FROM pillars WHERE sort_order = 3 LIMIT 1), folder_id = NULL, name = 'Human Organ Systems', description = 'Learn the main organ systems of the human body.', updated_at = CURRENT_TIMESTAMP WHERE id = 'de0b6e00-8c3d-4a56-997d-6345cb4ee316';
UPDATE subjects SET pillar_id = (SELECT id FROM pillars WHERE sort_order = 3 LIMIT 1), folder_id = NULL, name = 'Parts of the Human Body', description = 'Learn to identify common parts of the human body.', updated_at = CURRENT_TIMESTAMP WHERE id = '44202921-bedf-47c7-9ac1-5d47ba522f73';
UPDATE subjects SET pillar_id = (SELECT id FROM pillars WHERE sort_order = 4 LIMIT 1), folder_id = 'fold_world_flags', name = 'Flags of International Organizations', description = 'Learn to identify flags used by international organizations.', updated_at = CURRENT_TIMESTAMP WHERE id = '6e242fd7-a743-49d5-813e-31f5e9622470';
UPDATE subjects SET pillar_id = (SELECT id FROM pillars WHERE sort_order = 4 LIMIT 1), folder_id = 'fold_world_flags', name = 'Flags of the World', description = 'Learn to identify national flags from around the world.', updated_at = CURRENT_TIMESTAMP WHERE id = '35b2f5c1-10be-4c1d-b915-1159ef35fe26';
UPDATE subjects SET pillar_id = (SELECT id FROM pillars WHERE sort_order = 4 LIMIT 1), folder_id = 'fold_world_landmarks', name = 'World Bridges', description = 'Learn to identify notable bridges from around the world.', updated_at = CURRENT_TIMESTAMP WHERE id = '849ff5de-c89c-402b-8564-69feeb5ab1da';
UPDATE subjects SET pillar_id = (SELECT id FROM pillars WHERE sort_order = 4 LIMIT 1), folder_id = 'fold_world_landmarks', name = 'World Landmarks', description = 'Learn to identify famous landmarks from around the world.', updated_at = CURRENT_TIMESTAMP WHERE id = '8efc96db-89ae-4137-91cd-6a5800b788ad';
UPDATE subjects SET pillar_id = (SELECT id FROM pillars WHERE sort_order = 5 LIMIT 1), folder_id = NULL, name = 'Architectural Styles', description = 'Learn to identify major architectural styles.', updated_at = CURRENT_TIMESTAMP WHERE id = 'a3f500b9-a631-4e63-bdfb-ce5e53156163';
UPDATE subjects SET pillar_id = (SELECT id FROM pillars WHERE sort_order = 5 LIMIT 1), folder_id = NULL, name = 'Famous Paintings', description = 'Learn to identify famous paintings and their artists.', updated_at = CURRENT_TIMESTAMP WHERE id = '2f0d2ba6-165f-4b1f-9460-0fb6eba79715';
UPDATE subjects SET pillar_id = (SELECT id FROM pillars WHERE sort_order = 5 LIMIT 1), folder_id = NULL, name = 'Food & Cuisines', description = 'Explore foods and cuisines from around the world.', updated_at = CURRENT_TIMESTAMP WHERE id = '4b210d48-c309-4c4b-ad80-24b9f8dde33e';
UPDATE subjects SET pillar_id = (SELECT id FROM pillars WHERE sort_order = 5 LIMIT 1), folder_id = NULL, name = 'Historical Figures', description = 'Learn to identify influential historical figures.', updated_at = CURRENT_TIMESTAMP WHERE id = '02299d94-6d07-419f-b7df-ffcc048d412a';
UPDATE subjects SET pillar_id = (SELECT id FROM pillars WHERE sort_order = 5 LIMIT 1), folder_id = 'fold_arts_music', name = 'Musical Instruments', description = 'Learn to identify musical instruments.', updated_at = CURRENT_TIMESTAMP WHERE id = '7c85b685-6821-4906-a0e6-e5baaa49b5bc';
UPDATE subjects SET pillar_id = (SELECT id FROM pillars WHERE sort_order = 5 LIMIT 1), folder_id = 'fold_arts_music', name = 'Unusual Musical Instruments', description = 'Explore unusual musical instruments from around the world.', updated_at = CURRENT_TIMESTAMP WHERE id = '010fcb98-bc64-48a3-a9ae-7230e8717517';
UPDATE subjects SET pillar_id = (SELECT id FROM pillars WHERE sort_order = 6 LIMIT 1), folder_id = NULL, name = 'Sports', description = 'Learn to identify different sports.', updated_at = CURRENT_TIMESTAMP WHERE id = '1c58e149-e9f8-4edb-876a-e148b19f6c82';
UPDATE subjects SET pillar_id = (SELECT id FROM pillars WHERE sort_order = 7 LIMIT 1), folder_id = NULL, name = 'Heavy Construction Machinery', description = 'Learn to identify heavy construction machines and equipment.', updated_at = CURRENT_TIMESTAMP WHERE id = '09a77e7a-e70b-4e5f-a1f9-1ec2aaac7f0d';
UPDATE subjects SET pillar_id = (SELECT id FROM pillars WHERE sort_order = 7 LIMIT 1), folder_id = 'fold_engineering_vehicles', name = 'Car Brands', description = 'Learn to identify major car brands.', updated_at = CURRENT_TIMESTAMP WHERE id = '156365d1-0e84-40ca-a1a0-e0480ed278b5';
UPDATE subjects SET pillar_id = (SELECT id FROM pillars WHERE sort_order = 7 LIMIT 1), folder_id = 'fold_engineering_vehicles', name = 'Car Body Styles', description = 'Learn to identify common car body styles.', updated_at = CURRENT_TIMESTAMP WHERE id = '424bd963-b3d7-4f5b-b021-56ec5492d1a6';

