INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_status_active', 'en', 'You are a premium member', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_expires_at', 'en', 'Expires at {date}', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_lifetime', 'en', 'Lifetime access', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_unlock_title', 'en', 'Unlock Full Access', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_unlock_desc', 'en', 'Gain access to all subjects, create unlimited cards, and support Aliolos mission.', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_status_active', 'id', 'Anda adalah anggota premium', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_expires_at', 'id', 'Berakhir pada {date}', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_lifetime', 'id', 'Akses seumur hidup', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_unlock_title', 'id', 'Buka Akses Penuh', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_unlock_desc', 'id', 'Dapatkan akses ke semua subjek, buat kartu tanpa batas, dan dukung misi Aliolo.', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_status_active', 'bg', 'Вие сте премиум член', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_expires_at', 'bg', 'Изтича на {date}', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_lifetime', 'bg', 'Доживотен достъп', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_unlock_title', 'bg', 'Отключете пълен достъп', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_unlock_desc', 'bg', 'Получете достъп до всички предмети, създавайте неограничен брой карти и подкрепете мисията на Aliolo.', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_status_active', 'cs', 'Jste prémiovým členem', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_expires_at', 'cs', 'Platnost vyprší {date}', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_lifetime', 'cs', 'Doživotní přístup', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_unlock_title', 'cs', 'Odemknout plný přístup', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_unlock_desc', 'cs', 'Získejte přístup ke všem předmětům, vytvářejte neomezené množství karet a podpořte misi Aliolo.', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_status_active', 'da', 'Du er premium-medlem', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_expires_at', 'da', 'Udløber den {date}', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_lifetime', 'da', 'Livstidsadgang', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_unlock_title', 'da', 'Lås op for fuld adgang', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_unlock_desc', 'da', 'Få adgang til alle emner, opret ubegrænsede kort og støt Aliolos mission.', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_status_active', 'de', 'Sie sind ein Premium-Mitglied', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_expires_at', 'de', 'Läuft am {date} ab', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_lifetime', 'de', 'Lebenslanger Zugriff', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_unlock_title', 'de', 'Vollen Zugriff freischalten', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_unlock_desc', 'de', 'Erhalten Sie Zugriff auf alle Themen, erstellen Sie unbegrenzt Karten und unterstützen Sie die Mission von Aliolo.', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_status_active', 'et', 'Olete premium-liige', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_expires_at', 'et', 'Aegub {date}', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_lifetime', 'et', 'Eluaegne juurdepääs', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_unlock_title', 'et', 'Ava täielik juurdepääs', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_unlock_desc', 'et', 'Saage juurdepääs kõigile teemadele, looge piiramatult kaarte ja toetage Aliolo missiooni.', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_status_active', 'es', 'Eres un miembro premium', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_expires_at', 'es', 'Expira el {date}', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_lifetime', 'es', 'Acceso de por vida', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_unlock_title', 'es', 'Desbloquear acceso total', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_unlock_desc', 'es', 'Obtén acceso a todos los temas, crea tarjetas ilimitadas y apoya la misión de Aliolo.', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_status_active', 'fr', 'Vous êtes un membre premium', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_expires_at', 'fr', 'Expire le {date}', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_lifetime', 'fr', 'Accès à vie', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_unlock_title', 'fr', 'Débloquer laccès complet', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_unlock_desc', 'fr', 'Accédez à tous les sujets, créez des cartes illimitées et soutenez la mission dAliolo.', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_status_active', 'ga', 'Is ball préimhe thú', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_expires_at', 'ga', 'In éag ar {date}', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_lifetime', 'ga', 'Rochtain ar feadh an tsaoil', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_unlock_title', 'ga', 'Díghlasáil Rochtain Iomlán', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_unlock_desc', 'ga', 'Faigh rochtain ar gach ábhar, cruthaigh cártaí gan teorainn, agus tacaigh le misean Aliolo.', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_status_active', 'hr', 'Ви сте премиум члан', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_expires_at', 'hr', 'Istječe {date}', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_lifetime', 'hr', 'Doživotni pristup', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_unlock_title', 'hr', 'Otključaj puni pristup', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_unlock_desc', 'hr', 'Dobijte pristup svim predmetima, stvarajte neograničeno kartica i podržite misiju Aliola.', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_status_active', 'it', 'Sei un membro premium', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_expires_at', 'it', 'Scade il {date}', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_lifetime', 'it', 'Accesso a vita', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_unlock_title', 'it', 'Sblocca laccesso completo', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_unlock_desc', 'it', 'Ottieni laccesso a tutti gli argomenti, crea carte illimitate e sostieni la missione di Aliolo.', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_status_active', 'lv', 'Jūs esat premium biedrs', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_expires_at', 'lv', 'Beidzas {date}', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_lifetime', 'lv', 'Mūža piekļuve', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_unlock_title', 'lv', 'Atbloķēt pilnu piekļuvi', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_unlock_desc', 'lv', 'Iegūstiet piekļuvi visiem priekšmetiem, izveidojiet neierobežotu skaitu karšu un atbalstiet Aliolo misiju.', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_status_active', 'lt', 'Jūs esate „premium“ narys', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_expires_at', 'lt', 'Galioja iki {date}', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_lifetime', 'lt', 'Prieiga visam gyvenimui', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_unlock_title', 'lt', 'Atrakinti visą prieigą', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_unlock_desc', 'lt', 'Gaukite prieigą prie visų temų, kurkite neribotą kiekį kortelių ir palaikykite „Aliolo“ misiją.', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_status_active', 'hu', 'Ön prémium tag', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_expires_at', 'hu', 'Lejárat: {date}', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_lifetime', 'hu', 'Élethosszig tartó hozzáférés', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_unlock_title', 'hu', 'Teljes hozzáférés feloldása', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_unlock_desc', 'hu', 'Hozzáférés az összes tantárgyhoz, korlátlan kártyakészítés és az Aliolo küldetésének támogatása.', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_status_active', 'mt', 'Int membru premium', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_expires_at', 'mt', 'Jiskadi nhar {date}', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_lifetime', 'mt', 'Aċċess għal għomrok', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_unlock_title', 'mt', 'Iftaħ Aċċess Sħiħ', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_unlock_desc', 'mt', 'Ikseb aċċess għas-suġġetti kollha, oħloq karti illimitati, u appoġġja l-missjoni ta Aliolo.', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_status_active', 'nl', 'Je bent een premium lid', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_expires_at', 'nl', 'Verloopt op {date}', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_lifetime', 'nl', 'Levenslange toegang', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_unlock_title', 'nl', 'Ontgrendel volledige toegang', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_unlock_desc', 'nl', 'Krijg toegang tot alle onderwerpen, maak onbeperkt kaarten en ondersteun de missie van Aliolo.', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_status_active', 'pl', 'Jesteś członkiem premium', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_expires_at', 'pl', 'Wygasa {date}', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_lifetime', 'pl', 'Dożywotni dostęp', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_unlock_title', 'pl', 'Odblokuj pełny dostęp', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_unlock_desc', 'pl', 'Uzyskaj dostęp do wszystkich przedmiotów, twórz nieograniczoną liczbę kart i wspieraj misję Aliolo.', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_status_active', 'pt', 'Você é um membro premium', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_expires_at', 'pt', 'Expira em {date}', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_lifetime', 'pt', 'Acesso vitalício', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_unlock_title', 'pt', 'Desbloquear acesso total', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_unlock_desc', 'pt', 'Tenha acesso a todos os assuntos, crie cartões ilimitados e apoie a missão da Aliolo.', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_status_active', 'ro', 'Sunteți membru premium', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_expires_at', 'ro', 'Expiră la data de {date}', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_lifetime', 'ro', 'Acces pe viață', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_unlock_title', 'ro', 'Deblocați accesul complet', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_unlock_desc', 'ro', 'Obțineți acces la toate subiectele, creați carduri nelimitate și susțineți misiunea Aliolo.', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_status_active', 'sk', 'Ste prémiovým členom', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_expires_at', 'sk', 'Platnosť vyprší {date}', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_lifetime', 'sk', 'Doživotný prístup', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_unlock_title', 'sk', 'Odomknúť úplný prístup', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_unlock_desc', 'sk', 'Získajte prístup ku všetkým predmetom, vytvárajte neobmedzený počet kariet a podporte misiu Aliolo.', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_status_active', 'sl', 'Ste premium član', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_expires_at', 'sl', 'Poteče {date}', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_lifetime', 'sl', 'Doživljen dostop', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_unlock_title', 'sl', 'Odkleni poln dostop', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_unlock_desc', 'sl', 'Pridobite dostop do vseh predmetov, ustvarite neomejeno število kartic in podprite misijo Aliolo.', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_status_active', 'fi', 'Olet premium-jäsen', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_expires_at', 'fi', 'Vanhentuu {date}', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_lifetime', 'fi', 'Elinikäinen käyttöoikeus', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_unlock_title', 'fi', 'Avaa täysi käyttöoikeus', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_unlock_desc', 'fi', 'Saat pääsyn kaikkiin aiheisiin, luo rajattomasti kortteja ja tue Aliolon missiota.', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_status_active', 'sv', 'Du är premiummedlem', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_expires_at', 'sv', 'Löper ut {date}', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_lifetime', 'sv', 'Livstidsåtkomst', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_unlock_title', 'sv', 'Lås upp full åtkomst', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_unlock_desc', 'sv', 'Få tillgång till alla ämnen, skapa obegränsat antal kort och stöd Aliolos uppdrag.', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_status_active', 'tl', 'Ikaw ay isang premium member', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_expires_at', 'tl', 'Mag-e-expire sa {date}', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_lifetime', 'tl', 'Lifetime access', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_unlock_title', 'tl', 'I-unlock ang Buong Access', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_unlock_desc', 'tl', 'Kumuha ng access sa lahat ng subject, gumawa ng walang limitasyong mga card, at suportahan ang misyon ng Aliolo.', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_status_active', 'vi', 'Bạn là thành viên cao cấp', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_expires_at', 'vi', 'Hết hạn vào {date}', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_lifetime', 'vi', 'Truy cập trọn đời', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_unlock_title', 'vi', 'Mở khóa quyền truy cập đầy đủ', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_unlock_desc', 'vi', 'Truy cập tất cả các chủ đề, tạo thẻ không giới hạn và hỗ trợ sứ mệnh của Aliolo.', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_status_active', 'tr', 'Premium üyesiniz', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_expires_at', 'tr', '{date} tarihinde sona eriyor', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_lifetime', 'tr', 'Ömür boyu erişim', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_unlock_title', 'tr', 'Tam Erişimin Kilidini Aç', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_unlock_desc', 'tr', 'Tüm konulara erişim sağlayın, sınırsız kart oluşturun ve Aliolonun misyonunu destekleyin.', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_status_active', 'el', 'Είστε μέλος premium', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_expires_at', 'el', 'Λήγει στις {date}', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_lifetime', 'el', 'Ισόβια πρόσβαση', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_unlock_title', 'el', 'Ξεκλειδώστε την πλήρη πρόσβαση', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_unlock_desc', 'el', 'Αποκτήστε πρόσβαση σε όλα τα θέματα, δημιουργήστε απεριόριστες κάρτες και υποστηρίξτε την αποστολή της Aliolo.', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_status_active', 'uk', 'Ви є преміум-учасником', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_expires_at', 'uk', 'Термін дії закінчується {date}', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_lifetime', 'uk', 'Довічний доступ', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_unlock_title', 'uk', 'Розблокувати повний доступ', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_unlock_desc', 'uk', 'Отримайте доступ до всіх предметів, створюйте необмежену кількість карток і підтримайте місію Aliolo.', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_status_active', 'ar', 'أنت عضو بريميوم', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_expires_at', 'ar', 'تنتهي الصلاحية في {date}', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_lifetime', 'ar', 'وصول مدى الحياة', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_unlock_title', 'ar', 'فتح الوصول الكامل', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_unlock_desc', 'ar', 'احصل على إمكانية الوصول إلى جميع المواد، وقم بإنشاء بطاقات غير محدودة، وادعم مهمة Aliolo.', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_status_active', 'hi', 'आप एक प्रीमियम सदस्य हैं', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_expires_at', 'hi', '{date} को समाप्त होगा', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_lifetime', 'hi', 'आजीवन पहुंच', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_unlock_title', 'hi', 'पूर्ण पहुंच अनलॉक करें', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_unlock_desc', 'hi', 'सभी विषयों तक पहुंच प्राप्त करें, असीमित कार्ड बनाएं और Aliolo के मिशन का समर्थन करें.', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_status_active', 'zh', '您是高级会员', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_expires_at', 'zh', '将于 {date} 到期', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_lifetime', 'zh', '终身访问权限', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_unlock_title', 'zh', '解锁全部权限', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_unlock_desc', 'zh', '访问所有主题，创建无限卡片，并支持 Aliolo 的使命。', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_status_active', 'ja', 'あなたはプレミアムメンバーです', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_expires_at', 'ja', '{date} に期限切れになります', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_lifetime', 'ja', 'ライフタイムアクセス', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_unlock_title', 'ja', 'フルアクセスを解除', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_unlock_desc', 'ja', 'すべての科目にアクセスし、無制限にカードを作成して、Alioloのミッションをサポートしてください。', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_status_active', 'ko', '프리미엄 회원입니다', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_expires_at', 'ko', '{date}에 만료됩니다', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_lifetime', 'ko', '평생 이용권', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_unlock_title', 'ko', '모든 권한 잠금 해제', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('premium_unlock_desc', 'ko', '모든 주제에 액세스하고, 무제한 카드를 생성하며, Aliolo의 미션을 지원하세요.', CURRENT_TIMESTAMP);