INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_localized_images', 'en', 'No localized images', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_localized_images', 'id', 'Tidak ada gambar yang dilokalkan', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_localized_images', 'bg', 'Няма локализирани изображения', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_localized_images', 'cs', 'Žádné lokalizované obrázky', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_localized_images', 'da', 'Ingen lokaliserede billeder', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_localized_images', 'de', 'Keine lokalisierten Bilder', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_localized_images', 'et', 'Lokaliseeritud pilte pole', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_localized_images', 'es', 'No hay imágenes localizadas', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_localized_images', 'fr', 'Aucune image localisée', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_localized_images', 'ga', 'Níl aon íomhánna logánta', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_localized_images', 'hr', 'Nema lokaliziranih slika', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_localized_images', 'it', 'Nessuna immagine localizzata', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_localized_images', 'lv', 'Nav lokalizētu attēlu', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_localized_images', 'lt', 'Nėra lokalizuotų vaizdų', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_localized_images', 'hu', 'Nincsenek lokalizált képek', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_localized_images', 'mt', 'L-ebda immaġni lokalizzata', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_localized_images', 'nl', 'Geen gelokaliseerde afbeeldingen', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_localized_images', 'pl', 'Brak zlokalizowanych obrazów', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_localized_images', 'pt', 'Nenhuma imagem localizada', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_localized_images', 'ro', 'Nu există imagini localizate', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_localized_images', 'sk', 'Žiadne lokalizované obrázky', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_localized_images', 'sl', 'Ni lokaliziranih slik', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_localized_images', 'fi', 'Ei lokalisoituja kuvia', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_localized_images', 'sv', 'Inga lokaliserade bilder', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_localized_images', 'tl', 'Walang na-localize na mga larawan', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_localized_images', 'vi', 'Không có hình ảnh được bản địa hóa', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_localized_images', 'tr', 'Yerelleştirilmiş resim yok', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_localized_images', 'el', 'Δεν υπάρχουν τοπικοποιημένες εικόνες', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_localized_images', 'uk', 'Немає локалізованих зображень', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_localized_images', 'ar', 'لا توجد صور محلية', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_localized_images', 'hi', 'कोई स्थानीयकृत चित्र नहीं', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_localized_images', 'zh', '没有本地化图像', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_localized_images', 'ja', 'ローカライズされた画像はありません', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_localized_images', 'ko', '현지화된 이미지 없음', CURRENT_TIMESTAMP);