INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_creation', 'en', 'Creation Tools', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_testing', 'en', 'Interactive Testing', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_customize', 'en', 'Advanced Customization', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_full_library', 'en', 'Full Library Access', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_creation', 'id', 'Alat Pembuatan', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_testing', 'id', 'Pengujian Interaktif', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_customize', 'id', 'Kustomisasi Lanjutan', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_full_library', 'id', 'Akses Perpustakaan Penuh', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_creation', 'bg', 'Инструменти за създаване', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_testing', 'bg', 'Интерактивно тестване', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_customize', 'bg', 'Разширено персонализиране', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_full_library', 'bg', 'Пълен достъп до библиотеката', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_creation', 'cs', 'Nástroje pro tvorbu', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_testing', 'cs', 'Interaktivní testování', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_customize', 'cs', 'Pokročilé přizpůsobení', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_full_library', 'cs', 'Úplný přístup do knihovny', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_creation', 'da', 'Skabelsesværktøjer', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_testing', 'da', 'Interaktiv testning', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_customize', 'da', 'Avanceret tilpasning', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_full_library', 'da', 'Fuld adgang til biblioteket', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_creation', 'de', 'Erstellungstools', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_testing', 'de', 'Interaktives Testen', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_customize', 'de', 'Erweiterte Anpassung', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_full_library', 'de', 'Vollständiger Bibliothekszugriff', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_creation', 'et', 'Loomise tööriistad', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_testing', 'et', 'Interaktiivne testimine', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_customize', 'et', 'Täpsem kohandamine', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_full_library', 'et', 'Täielik juurdepääs raamatukogule', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_creation', 'es', 'Herramientas de creación', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_testing', 'es', 'Pruebas interactivas', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_customize', 'es', 'Personalización avanzada', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_full_library', 'es', 'Acceso completo a la biblioteca', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_creation', 'fr', 'Outils de création', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_testing', 'fr', 'Tests interactifs', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_customize', 'fr', 'Personnalisation avancée', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_full_library', 'fr', 'Accès complet à la bibliothèque', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_creation', 'ga', 'Uirlisí Cruthaithe', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_testing', 'ga', 'Tástáil Idirghníomhach', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_customize', 'ga', 'Saincheapadh Casta', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_full_library', 'ga', 'Rochtain Iomlán ar an Leabharlann', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_creation', 'hr', 'Alati za stvaranje', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_testing', 'hr', 'Interaktivno testiranje', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_customize', 'hr', 'Napredno prilagođavanje', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_full_library', 'hr', 'Puni pristup knjižnici', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_creation', 'it', 'Strumenti di creazione', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_testing', 'it', 'Test interattivi', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_customize', 'it', 'Personalizzazione avanzada', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_full_library', 'it', 'Accesso completo alla biblioteca', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_creation', 'lv', 'Veidošanas rīki', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_testing', 'lv', 'Interaktīvā testēšana', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_customize', 'lv', 'Uzlabota pielāgošana', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_full_library', 'lv', 'Pilna piekļuve bibliotēkai', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_creation', 'lt', 'Kūrimo įrankiai', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_testing', 'lt', 'Interaktyvus testavimas', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_customize', 'lt', 'Išplėstinis pritaikymas', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_full_library', 'lt', 'Visiška prieiga prie bibliotekos', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_creation', 'hu', 'Létrehozási eszközök', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_testing', 'hu', 'Interaktív tesztelés', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_customize', 'hu', 'Speciális testreszabás', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_full_library', 'hu', 'Teljes könyvtári hozzáférés', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_creation', 'mt', 'Għodod tal-Ħolqien', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_testing', 'mt', 'Ittestjar Interattiv', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_customize', 'mt', 'Personalizzazzjoni Avvanzata', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_full_library', 'mt', 'Aċċess Sħiħ għal-Librerija', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_creation', 'nl', 'Creatietools', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_testing', 'nl', 'Interactief testen', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_customize', 'nl', 'Geavanceerde aanpassing', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_full_library', 'nl', 'Volledige bibliotheektoegang', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_creation', 'pl', 'Narzędzia do tworzenia', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_testing', 'pl', 'Testy interaktywne', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_customize', 'pl', 'Zaawansowana personalizacja', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_full_library', 'pl', 'Pełny dostęp do biblioteki', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_creation', 'pt', 'Ferramentas de criação', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_testing', 'pt', 'Testes interativos', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_customize', 'pt', 'Personalização avançada', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_full_library', 'pt', 'Acesso total à biblioteca', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_creation', 'ro', 'Instrumente de creare', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_testing', 'ro', 'Testare interactivă', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_customize', 'ro', 'Personalizare avansată', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_full_library', 'ro', 'Acces complet la bibliotecă', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_creation', 'sk', 'Nástroje na tvorbu', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_testing', 'sk', 'Interaktívne testovanie', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_customize', 'sk', 'Pokročilé prispôsobenie', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_full_library', 'sk', 'Úplný prístup do knižnice', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_creation', 'sl', 'Orodja za ustvarjanje', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_testing', 'sl', 'Interaktivno testiranje', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_customize', 'sl', 'Napredna prilagoditev', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_full_library', 'sl', 'Popoln dostup do knjižnice', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_creation', 'fi', 'Luontityökalut', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_testing', 'fi', 'Interaktiivinen testaus', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_customize', 'fi', 'Edistynyt muokkaus', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_full_library', 'fi', 'Täysi pääsy kirjastoon', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_creation', 'sv', 'Skaparverktyg', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_testing', 'sv', 'Interaktiv testning', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_customize', 'sv', 'Avancerad anpassning', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_full_library', 'sv', 'Full tillgång till biblioteket', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_creation', 'tl', 'Mga Tool sa Paglikha', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_testing', 'tl', 'Interactive na Pagsusulit', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_customize', 'tl', 'Advanced na Pag-customize', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_full_library', 'tl', 'Ganap na Akses sa Library', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_creation', 'vi', 'Công cụ sáng tạo', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_testing', 'vi', 'Kiểm tra tương tác', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_customize', 'vi', 'Tùy chỉnh nâng cao', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_full_library', 'vi', 'Truy cập thư viện đầy đủ', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_creation', 'tr', 'Oluşturma Araçları', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_testing', 'tr', 'İnteraktif Test', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_customize', 'tr', 'Gelişmiş Özelleştirme', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_full_library', 'tr', 'Tam Kütüphane Erişimi', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_creation', 'el', 'Εργαλεία Δημιουργίας', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_testing', 'el', 'Διαδραστική Δοκιμή', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_customize', 'el', 'Προηγμένη Προσαρμογή', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_full_library', 'el', 'Πλήρης Πρόσβαση στη Βιβλιοθήκη', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_creation', 'uk', 'Інструменти створення', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_testing', 'uk', 'Інтерактивне тестування', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_customize', 'uk', 'Розширене налаштування', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_full_library', 'uk', 'Повний доступ до бібліотеки', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_creation', 'ar', 'أدوات الإنشاء', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_testing', 'ar', 'اختبار تفاعلي', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_customize', 'ar', 'تخصيص متقدم', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_full_library', 'ar', 'وصول كامل للمكتبة', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_creation', 'hi', 'निर्माण उपकरण', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_testing', 'hi', 'इंटरएक्टिव परीक्षण', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_customize', 'hi', 'उन्नत अनुकूलन', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_full_library', 'hi', 'पूर्ण पुस्तकालय पहुंच', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_creation', 'zh', '创建工具', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_testing', 'zh', '互动测试', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_customize', 'zh', '高级定制', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_full_library', 'zh', '完整库访问权限', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_creation', 'ja', '作成ツール', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_testing', 'ja', 'インタラクティブ・テスト', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_customize', 'ja', '高度なカスタマイズ', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_full_library', 'ja', 'フルライブラリ・アクセス', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_creation', 'ko', '제작 도구', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_testing', 'ko', '대화형 테스트', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_customize', 'ko', '고급 사용자 정의', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('feature_full_library', 'ko', '전체 라이브러리 액세스', CURRENT_TIMESTAMP);