INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_weekly_title', 'en', 'Weekly Access', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_monthly_title', 'en', 'Monthly Access', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_yearly_title', 'en', 'Yearly Access', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_weekly_tagline', 'en', 'Best for quick goals', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_monthly_tagline', 'en', 'Most popular choice', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_yearly_tagline', 'en', 'Save 33% per month', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_weekly_title', 'id', 'Akses Mingguan', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_monthly_title', 'id', 'Akses Bulanan', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_yearly_title', 'id', 'Akses Tahunan', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_weekly_tagline', 'id', 'Terbaik untuk tujuan cepat', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_monthly_tagline', 'id', 'Pilihan paling populer', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_yearly_tagline', 'id', 'Hemat 33% per bulan', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_weekly_title', 'bg', 'Седмичен достъп', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_monthly_title', 'bg', 'Месечен достъп', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_yearly_title', 'bg', 'Годишен достъп', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_weekly_tagline', 'bg', 'Най-доброто за бързи голове', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_monthly_tagline', 'bg', 'Най-популярният избор', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_yearly_tagline', 'bg', 'Спестете 33% на месец', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_weekly_title', 'cs', 'Týdenní přístup', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_monthly_title', 'cs', 'Měsíční přístup', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_yearly_title', 'cs', 'Roční přístup', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_weekly_tagline', 'cs', 'Nejlepší na rychlé góly', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_monthly_tagline', 'cs', 'Nejoblíbenější volba', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_yearly_tagline', 'cs', 'Ušetřete 33 % měsíčně', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_weekly_title', 'da', 'Ugentlig adgang', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_monthly_title', 'da', 'Månedlig adgang', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_yearly_title', 'da', 'Årlig adgang', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_weekly_tagline', 'da', 'Bedst til hurtige mål', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_monthly_tagline', 'da', 'Mest populære valg', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_yearly_tagline', 'da', 'Spar 33% om måneden', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_weekly_title', 'de', 'Wöchentlicher Zugriff', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_monthly_title', 'de', 'Monatlicher Zugriff', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_yearly_title', 'de', 'Jährlicher Zugang', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_weekly_tagline', 'de', 'Am besten für schnelle Ziele', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_monthly_tagline', 'de', 'Beliebteste Wahl', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_yearly_tagline', 'de', 'Sparen Sie 33 % pro Monat', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_weekly_title', 'et', 'Iganädalane juurdepääs', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_monthly_title', 'et', 'Igakuine juurdepääs', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_yearly_title', 'et', 'Aastane juurdepääs', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_weekly_tagline', 'et', 'Parim kiirete eesmärkide saavutamiseks', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_monthly_tagline', 'et', 'Kõige populaarsem valik', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_yearly_tagline', 'et', 'Säästa 33% kuus', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_weekly_title', 'es', 'Acceso Semanal', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_monthly_title', 'es', 'Acceso Mensual', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_yearly_title', 'es', 'Acceso Anual', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_weekly_tagline', 'es', 'Lo mejor para objetivos rápidos', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_monthly_tagline', 'es', 'Elección más popular', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_yearly_tagline', 'es', 'Ahorre 33% por mes', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_weekly_title', 'fr', 'Accès hebdomadaire', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_monthly_title', 'fr', 'Accès mensuel', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_yearly_title', 'fr', 'Accès annuel', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_weekly_tagline', 'fr', 'Idéal pour les objectifs rapides', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_monthly_tagline', 'fr', 'Choix le plus populaire', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_yearly_tagline', 'fr', 'Économisez 33 % par mois', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_weekly_title', 'ga', 'Rochtain Seachtainiúil', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_monthly_title', 'ga', 'Rochtain Mhíosúil', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_yearly_title', 'ga', 'Rochtain Bhliantúil', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_weekly_tagline', 'ga', 'Is fearr le haghaidh spriocanna tapa', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_monthly_tagline', 'ga', 'Rogha is coitianta', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_yearly_tagline', 'ga', 'Sábháil 33% in aghaidh na míosa', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_weekly_title', 'hr', 'Tjedni pristup', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_monthly_title', 'hr', 'Mjesečni pristup', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_yearly_title', 'hr', 'Godišnji pristup', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_weekly_tagline', 'hr', 'Najbolji za brze golove', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_monthly_tagline', 'hr', 'Najpopularniji izbor', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_yearly_tagline', 'hr', 'Uštedite 33% mjesečno', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_weekly_title', 'it', 'Accesso settimanale', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_monthly_title', 'it', 'Accesso mensile', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_yearly_title', 'it', 'Accesso annuale', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_weekly_tagline', 'it', 'Ideale per obiettivi rapidi', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_monthly_tagline', 'it', 'La scelta più popolare', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_yearly_tagline', 'it', 'Risparmia il 33% al mese', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_weekly_title', 'lv', 'Iknedēļas piekļuve', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_monthly_title', 'lv', 'Ikmēneša piekļuve', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_yearly_title', 'lv', 'Ikgadējā piekļuve', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_weekly_tagline', 'lv', 'Vislabāk ātriem mērķiem', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_monthly_tagline', 'lv', 'Populārākā izvēle', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_yearly_tagline', 'lv', 'Ietaupiet 33% mēnesī', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_weekly_title', 'lt', 'Savaitinė prieiga', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_monthly_title', 'lt', 'Mėnesinė prieiga', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_yearly_title', 'lt', 'Kasmetinė prieiga', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_weekly_tagline', 'lt', 'Geriausiai tinka greitiems įvarčiams', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_monthly_tagline', 'lt', 'Populiariausias pasirinkimas', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_yearly_tagline', 'lt', 'Sutauvykite 33% per mėnesį', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_weekly_title', 'hu', 'Heti hozzáférés', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_monthly_title', 'hu', 'Havi hozzáférés', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_yearly_title', 'hu', 'Éves hozzáférés', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_weekly_tagline', 'hu', 'Legjobb gyors gólokhoz', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_monthly_tagline', 'hu', 'A legnépszerűbb választás', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_yearly_tagline', 'hu', '33% megtakarítás havonta', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_weekly_title', 'mt', 'Aċċess ta'' kull ġimgħa', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_monthly_title', 'mt', 'Aċċess ta'' Kull Xahar', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_yearly_title', 'mt', 'Aċċess annwali', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_weekly_tagline', 'mt', 'L-aħjar għal għanijiet ta'' malajr', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_monthly_tagline', 'mt', 'L-aktar għażla popolari', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_yearly_tagline', 'mt', 'Iffranka 33% fix-xahar', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_weekly_title', 'nl', 'Wekelijkse toegang', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_monthly_title', 'nl', 'Maandelijkse toegang', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_yearly_title', 'nl', 'Jaarlijkse toegang', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_weekly_tagline', 'nl', 'Beste voor snelle doelpunten', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_monthly_tagline', 'nl', 'Meest populaire keuze', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_yearly_tagline', 'nl', 'Bespaar 33% per maand', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_weekly_title', 'pl', 'Dostęp tygodniowy', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_monthly_title', 'pl', 'Dostęp miesięczny', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_yearly_title', 'pl', 'Dostęp roczny', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_weekly_tagline', 'pl', 'Najlepszy do szybkich bramek', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_monthly_tagline', 'pl', 'Najpopularniejszy wybór', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_yearly_tagline', 'pl', 'Oszczędzaj 33% miesięcznie', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_weekly_title', 'pt', 'Acesso Semanal', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_monthly_title', 'pt', 'Acesso Mensual', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_yearly_title', 'pt', 'Acesso Anual', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_weekly_tagline', 'pt', 'Melhor para metas rápidas', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_monthly_tagline', 'pt', 'Escolha mais popular', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_yearly_tagline', 'pt', 'Economize 33% ao mês', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_weekly_title', 'ro', 'Acces săptămânal', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_monthly_title', 'ro', 'Acces lunar', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_yearly_title', 'ro', 'Acces anual', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_weekly_tagline', 'ro', 'Cel mai bun pentru goluri rapide', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_monthly_tagline', 'ro', 'Cea mai populară alegere', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_yearly_tagline', 'ro', 'Economisiți 33% pe lună', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_weekly_title', 'sk', 'Týždenný prístup', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_monthly_title', 'sk', 'Mesačný prístup', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_yearly_title', 'sk', 'Ročný prístup', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_weekly_tagline', 'sk', 'Najlepšie na rýchle góly', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_monthly_tagline', 'sk', 'Najobľúbenejšia voľba', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_yearly_tagline', 'sk', 'Ušetrite 33% mesačne', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_weekly_title', 'sl', 'Tedenski dostop', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_monthly_title', 'sl', 'Mesečni dostop', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_yearly_title', 'sl', 'Letni dostop', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_weekly_tagline', 'sl', 'Najboljši za hitre gole', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_monthly_tagline', 'sl', 'Najbolj priljubljena izbira', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_yearly_tagline', 'sl', 'Prihranite 33 % na mesec', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_weekly_title', 'fi', 'Viikoittainen pääsy', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_monthly_title', 'fi', 'Kuukausittainen pääsy', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_yearly_title', 'fi', 'Vuosittainen pääsy', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_weekly_tagline', 'fi', 'Paras nopeille maaleille', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_monthly_tagline', 'fi', 'Suosituin valinta', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_yearly_tagline', 'fi', 'Säästä 33 % kuukaudessa', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_weekly_title', 'sv', 'Veckovis tillgång', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_monthly_title', 'sv', 'Månatlig tillgång', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_yearly_title', 'sv', 'Årlig tillgång', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_weekly_tagline', 'sv', 'Bäst för snabba mål', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_monthly_tagline', 'sv', 'Mest populära valet', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_yearly_tagline', 'sv', 'Spara 33 % per månad', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_weekly_title', 'tl', 'Lingguhang Access', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_monthly_title', 'tl', 'Buwanang Access', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_yearly_title', 'tl', 'Taunang Access', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_weekly_tagline', 'tl', 'Pinakamahusay para sa mabilis na layunin', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_monthly_tagline', 'tl', 'Pinakatanyag na pagpipilian', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_yearly_tagline', 'tl', 'Makatipid ng 33% bawat buwan', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_weekly_title', 'vi', 'Truy cập hàng tuần', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_monthly_title', 'vi', 'Truy cập hàng tháng', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_yearly_title', 'vi', 'Truy cập hàng năm', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_weekly_tagline', 'vi', 'Tốt nhất cho mục tiêu nhanh chóng', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_monthly_tagline', 'vi', 'Sự lựa chọn phổ biến nhất', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_yearly_tagline', 'vi', 'Tiết kiệm 33% mỗi tháng', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_weekly_title', 'tr', 'Haftalık Erişim', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_monthly_title', 'tr', 'Aylık Erişim', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_yearly_title', 'tr', 'Yıllık Erişim', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_weekly_tagline', 'tr', 'Hızlı hedefler için en iyisi', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_monthly_tagline', 'tr', 'En popüler seçim', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_yearly_tagline', 'tr', 'Ayda %33 tasarruf edin', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_weekly_title', 'el', 'Εβδομαδιαία πρόσβαση', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_monthly_title', 'el', 'Μηνιαία πρόσβαση', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_yearly_title', 'el', 'Ετήσια πρόσβαση', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_weekly_tagline', 'el', 'Το καλύτερο για γρήγορους στόχους', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_monthly_tagline', 'el', 'Η πιο δημοφιλής επιλογή', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_yearly_tagline', 'el', 'Εξοικονομήστε 33% ανά μήνα', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_weekly_title', 'uk', 'Щотижневий доступ', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_monthly_title', 'uk', 'Щомісячний доступ', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_yearly_title', 'uk', 'Річний доступ', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_weekly_tagline', 'uk', 'Найкраще для швидких голів', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_monthly_tagline', 'uk', 'Найпопулярніший вибір', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_yearly_tagline', 'uk', 'Економія 33% на місяць', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_weekly_title', 'ar', 'الوصول الأسبوعي', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_monthly_title', 'ar', 'الوصول الشهري', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_yearly_title', 'ar', 'الوصول السنوي', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_weekly_tagline', 'ar', 'الأفضل للأهداف السريعة', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_monthly_tagline', 'ar', 'الاختيار الأكثر شعبية', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_yearly_tagline', 'ar', 'وفر 33% شهريًا', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_weekly_title', 'hi', 'साप्ताहिक प्रवेश', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_monthly_title', 'hi', 'मासिक प्रवेश', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_yearly_title', 'hi', 'वार्षिक प्रवेश', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_weekly_tagline', 'hi', 'त्वरित लक्ष्यों के लिए सर्वोत्तम', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_monthly_tagline', 'hi', 'सबसे लोकप्रिय विकल्प', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_yearly_tagline', 'hi', 'प्रति माह 33% बचाएं', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_weekly_title', 'zh', '每周访问', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_monthly_title', 'zh', '每月访问', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_yearly_title', 'zh', '每年访问', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_weekly_tagline', 'zh', '最适合快速目标', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_monthly_tagline', 'zh', '最受欢迎的选择', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_yearly_tagline', 'zh', '每月节省 33%', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_weekly_title', 'ja', '週間アクセス', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_monthly_title', 'ja', '月間アクセス数', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_yearly_title', 'ja', '年間アクセス', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_weekly_tagline', 'ja', '素早い目標に最適', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_monthly_tagline', 'ja', '最も人気のある選択肢', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_yearly_tagline', 'ja', '毎月 33% 割引', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_weekly_title', 'ko', '주간 액세스', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_monthly_title', 'ko', '월간 액세스', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_yearly_title', 'ko', '연간 액세스', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_weekly_tagline', 'ko', '빠른 목표에 가장 적합', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_monthly_tagline', 'ko', '가장 인기있는 선택', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('plan_yearly_tagline', 'ko', '월 33% 할인', CURRENT_TIMESTAMP);