INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('renderer', 'en', 'Renderer', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('visual_text', 'en', 'Visual Text', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_images_added', 'en', 'No images added', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('audio', 'en', 'Audio', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_localized_audio', 'en', 'No localized audio', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_localized_video', 'en', 'No localized video', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('visual_content_required', 'en', 'At least one visual content is required', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('visual_content_required_msg', 'en', 'At least one visual content (text, image, audio, or video) must be provided.', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('renderer', 'id', 'Perender', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('visual_text', 'id', 'Teks Visual', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_images_added', 'id', 'Tidak ada gambar yang ditambahkan', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('audio', 'id', 'Audio', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_localized_audio', 'id', 'Tidak ada audio yang dilokalkan', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_localized_video', 'id', 'Tidak ada video yang dilokalkan', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('visual_content_required', 'id', 'Setidaknya satu konten visual diperlukan', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('visual_content_required_msg', 'id', 'Setidaknya satu konten visual (teks, gambar, audio, atau video) harus disediakan.', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('renderer', 'bg', 'Рендерер', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('visual_text', 'bg', 'Визуален текст', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_images_added', 'bg', 'Няма добавени изображения', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('audio', 'bg', 'Аудио', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_localized_audio', 'bg', 'Няма локализирано аудио', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_localized_video', 'bg', 'Няма локализирано видео', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('visual_content_required', 'bg', 'Изисква се поне едно визуално съдържание', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('visual_content_required_msg', 'bg', 'Трябва да бъде предоставено поне едно визуално съдържание (текст, изображение, аудио или видео).', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('renderer', 'cs', 'Vykreslovací modul', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('visual_text', 'cs', 'Vizuální text', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_images_added', 'cs', 'Nebyly přidány žádné obrázky', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('audio', 'cs', 'Zvuk', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_localized_audio', 'cs', 'Žádný lokalizovaný zvuk', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_localized_video', 'cs', 'Žádné lokalizované video', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('visual_content_required', 'cs', 'Je vyžadován alespoň jeden vizuální obsah', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('visual_content_required_msg', 'cs', 'Musí být poskytnut alespoň jeden vizuální obsah (text, obrázek, zvuk nebo video).', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('renderer', 'da', 'Gengiver', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('visual_text', 'da', 'Visuel tekst', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_images_added', 'da', 'Ingen billeder tilføjet', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('audio', 'da', 'Lyd', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_localized_audio', 'da', 'Ingen lokaliseret lyd', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_localized_video', 'da', 'Ingen lokaliseret video', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('visual_content_required', 'da', 'Mindst ét visuelt indhold er påkrævet', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('visual_content_required_msg', 'da', 'Der skal angives mindst ét visuelt indhold (tekst, billede, lyd eller video).', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('renderer', 'de', 'Renderer', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('visual_text', 'de', 'Visueller Text', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_images_added', 'de', 'Keine Bilder hinzugefügt', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('audio', 'de', 'Audio', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_localized_audio', 'de', 'Kein lokalisiertes Audio', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_localized_video', 'de', 'Kein lokalisiertes Video', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('visual_content_required', 'de', 'Mindestens ein visueller Inhalt ist erforderlich', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('visual_content_required_msg', 'de', 'Mindestens ein visueller Inhalt (Text, Bild, Audio oder Video) muss bereitgestellt werden.', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('renderer', 'et', 'Renderdaja', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('visual_text', 'et', 'Visuaalne tekst', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_images_added', 'et', 'Pilte pole lisatud', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('audio', 'et', 'Heli', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_localized_audio', 'et', 'Lokaliseeritud heli pole', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_localized_video', 'et', 'Lokaliseeritud videot pole', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('visual_content_required', 'et', 'Vaja on vähemalt ühte visuaalset sisu', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('visual_content_required_msg', 'et', 'Esitada tuleb vähemalt üks visuaalne sisu (tekst, pilt, heli või video).', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('renderer', 'es', 'Renderizador', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('visual_text', 'es', 'Texto visual', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_images_added', 'es', 'No se han añadido imágenes', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('audio', 'es', 'Audio', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_localized_audio', 'es', 'Sin audio localizado', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_localized_video', 'es', 'Sin vídeo localizado', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('visual_content_required', 'es', 'Se requiere al menos un contenido visual', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('visual_content_required_msg', 'es', 'Se debe proporcionar al menos un contenido visual (texto, imagen, audio o vídeo).', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('renderer', 'fr', 'Moteur de rendu', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('visual_text', 'fr', 'Texte visuel', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_images_added', 'fr', 'Aucune image ajoutée', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('audio', 'fr', 'Audio', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_localized_audio', 'fr', 'Aucun audio localisé', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_localized_video', 'fr', 'Aucune vidéo localisée', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('visual_content_required', 'fr', 'Au moins un contenu visuel est requis', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('visual_content_required_msg', 'fr', 'Au moins un contenu visuel (texte, image, audio ou vidéo) doit être fourni.', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('renderer', 'ga', 'Rindreálaí', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('visual_text', 'ga', 'Téacs Físiúil', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_images_added', 'ga', 'Níor cuireadh aon íomhánna leis', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('audio', 'ga', 'Fuaim', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_localized_audio', 'ga', 'Gan aon fhuaim logánta', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_localized_video', 'ga', 'Gan aon fhíseán logánta', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('visual_content_required', 'ga', 'Tá gá le hábhar físiúil amháin ar a laghad', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('visual_content_required_msg', 'ga', 'Ní mór ábhar físiúil amháin ar a laghad (téacs, íomhá, fuaim nó físeán) a sholáthar.', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('renderer', 'hr', 'Prikazivač', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('visual_text', 'hr', 'Vizualni tekst', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_images_added', 'hr', 'Nema dodanih slika', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('audio', 'hr', 'Audio', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_localized_audio', 'hr', 'Nema lokaliziranog zvuka', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_localized_video', 'hr', 'Nema lokaliziranog videa', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('visual_content_required', 'hr', 'Potreban je barem jedan vizualni sadržaj', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('visual_content_required_msg', 'hr', 'Mora se navesti barem jedan vizualni sadržaj (tekst, slika, zvuk ili video).', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('renderer', 'it', 'Renderer', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('visual_text', 'it', 'Testo visivo', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_images_added', 'it', 'Nessuna immagine aggiunta', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('audio', 'it', 'Audio', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_localized_audio', 'it', 'Nessun audio localizzato', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_localized_video', 'it', 'Nessun video localizzato', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('visual_content_required', 'it', 'È richiesto almeno un contenuto visivo', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('visual_content_required_msg', 'it', 'Deve essere fornito almeno un contenuto visivo (testo, immagine, audio o video).', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('renderer', 'lv', 'Renderētājs', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('visual_text', 'lv', 'Vizuālais teksts', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_images_added', 'lv', 'Nav pievienotu attēlu', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('audio', 'lv', 'Audio', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_localized_audio', 'lv', 'Nav lokalizēta audio', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_localized_video', 'lv', 'Nav lokalizēta video', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('visual_content_required', 'lv', 'Nepieciešams vismaz viens vizuālais saturs', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('visual_content_required_msg', 'lv', 'Jānorāda vismaz viens vizuālais saturs (teksts, attēls, audio vai video).', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('renderer', 'lt', 'Atvaizdavimo modulis', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('visual_text', 'lt', 'Vaizdinis tekstas', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_images_added', 'lt', 'Nepridėta jokių vaizdų', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('audio', 'lt', 'Garsas', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_localized_audio', 'lt', 'Nėra lokalizuoto garso', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_localized_video', 'lt', 'Nėra lokalizuoto vaizdo įrašo', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('visual_content_required', 'lt', 'Reikalingas bent vienas vizualinis turinys', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('visual_content_required_msg', 'lt', 'Turi būti pateiktas bent vienas vizualinis turinys (tekstas, vaizdas, garsas arba vaizdo įrašas).', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('renderer', 'hu', 'Megjelenítő', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('visual_text', 'hu', 'Vizuális szöveg', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_images_added', 'hu', 'Nincs kép hozzáadva', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('audio', 'hu', 'Hang', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_localized_audio', 'hu', 'Nincs lokalizált hang', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_localized_video', 'hu', 'Nincs lokalizált videó', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('visual_content_required', 'hu', 'Legalább egy vizuális tartalom kötelező', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('visual_content_required_msg', 'hu', 'Legalább egy vizuális tartalmat (szöveg, kép, hang vagy videó) meg kell adni.', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('renderer', 'mt', 'Renditur', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('visual_text', 'mt', 'Test Viżwali', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_images_added', 'mt', 'L-ebda immaġni miżjuda', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('audio', 'mt', 'Awdjo', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_localized_audio', 'mt', 'L-ebda awdjo lokalizzat', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_localized_video', 'mt', 'L-ebda vidjo lokalizzat', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('visual_content_required', 'mt', 'Huwa meħtieġ mill-inqas kontenut viżwali wieħed', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('visual_content_required_msg', 'mt', 'Għandu jiġi pprovdut mill-inqas kontenut viżwali wieħed (test, immaġni, awdjo, jew vidjo).', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('renderer', 'nl', 'Renderer', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('visual_text', 'nl', 'Visuele tekst', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_images_added', 'nl', 'Geen afbeeldingen toegevoegd', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('audio', 'nl', 'Audio', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_localized_audio', 'nl', 'Geen gelokaliseerde audio', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_localized_video', 'nl', 'Geen gelokaliseerde video', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('visual_content_required', 'nl', 'Ten minste één visuele inhoud is vereist', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('visual_content_required_msg', 'nl', 'Er moet ten minste één visuele inhoud (tekst, afbeelding, audio of video) worden opgegeven.', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('renderer', 'pl', 'Mechanizm renderujący', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('visual_text', 'pl', 'Tekst wizualny', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_images_added', 'pl', 'Nie dodano żadnych obrazów', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('audio', 'pl', 'Dźwięk', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_localized_audio', 'pl', 'Brak zlokalizowanego dźwięku', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_localized_video', 'pl', 'Brak zlokalizowanego wideo', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('visual_content_required', 'pl', 'Wymagana jest co najmniej jedna treść wizualna', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('visual_content_required_msg', 'pl', 'Należy podać co najmniej jedną treść wizualną (tekst, obraz, dźwięk lub wideo).', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('renderer', 'pt', 'Renderizador', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('visual_text', 'pt', 'Texto visual', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_images_added', 'pt', 'Nenhuma imagem adicionada', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('audio', 'pt', 'Áudio', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_localized_audio', 'pt', 'Nenhum áudio localizado', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_localized_video', 'pt', 'Nenhum vídeo localizado', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('visual_content_required', 'pt', 'É necessário pelo menos um conteúdo visual', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('visual_content_required_msg', 'pt', 'Pelo menos um conteúdo visual (texto, imagem, áudio ou vídeo) deve ser fornecido.', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('renderer', 'ro', 'Motor de randare', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('visual_text', 'ro', 'Text vizual', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_images_added', 'ro', 'Nicio imagine adăugată', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('audio', 'ro', 'Audio', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_localized_audio', 'ro', 'Niciun sunet localizat', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_localized_video', 'ro', 'Niciun videoclip localizat', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('visual_content_required', 'ro', 'Este necesar cel puțin un conținut vizual', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('visual_content_required_msg', 'ro', 'Trebuie furnizat cel puțin un conținut vizual (text, imagine, audio sau videoclip).', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('renderer', 'sk', 'Vykresľovač', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('visual_text', 'sk', 'Vizuálny text', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_images_added', 'sk', 'Žiadne pridané obrázky', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('audio', 'sk', 'Zvuk', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_localized_audio', 'sk', 'Žiadny lokalizovaný zvuk', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_localized_video', 'sk', 'Žiadne lokalizované video', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('visual_content_required', 'sk', 'Vyžaduje sa aspoň jeden vizuálny obsah', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('visual_content_required_msg', 'sk', 'Musí sa poskytnúť aspoň jeden vizuálny obsah (text, obrázok, zvuk alebo video).', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('renderer', 'sl', 'Upodabljalnik', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('visual_text', 'sl', 'Vizualno besedilo', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_images_added', 'sl', 'Ni dodanih slik', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('audio', 'sl', 'Zvok', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_localized_audio', 'sl', 'Ni lokaliziranega zvoka', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_localized_video', 'sl', 'Ni lokaliziranega videa', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('visual_content_required', 'sl', 'Potrebna je vsaj ena vizualna vsebina', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('visual_content_required_msg', 'sl', 'Zagotoviti je treba vsaj eno vizualno vsebino (besedilo, slika, zvok ali video).', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('renderer', 'fi', 'Renderöijä', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('visual_text', 'fi', 'Visuaalinen teksti', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_images_added', 'fi', 'Ei lisättyjä kuvia', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('audio', 'fi', 'Ääni', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_localized_audio', 'fi', 'Ei lokalisoitua ääntä', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_localized_video', 'fi', 'Ei lokalisoitua videota', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('visual_content_required', 'fi', 'Vähintään yksi visuaalinen sisältö vaaditaan', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('visual_content_required_msg', 'fi', 'Vähintään yksi visuaalinen sisältö (teksti, kuva, ääni tai video) on annettava.', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('renderer', 'sv', 'Rendrerare', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('visual_text', 'sv', 'Visuell text', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_images_added', 'sv', 'Inga bilder har lagts till', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('audio', 'sv', 'Ljud', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_localized_audio', 'sv', 'Inget lokaliserat ljud', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_localized_video', 'sv', 'Inget lokaliserat videoklipp', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('visual_content_required', 'sv', 'Minst ett visuellt innehåll krävs', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('visual_content_required_msg', 'sv', 'Minst ett visuellt innehåll (text, bild, ljud eller video) måste anges.', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('renderer', 'tl', 'Renderer', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('visual_text', 'tl', 'Visual Text', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_images_added', 'tl', 'Walang idinagdag na mga larawan', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('audio', 'tl', 'Audio', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_localized_audio', 'tl', 'Walang naka-localize na audio', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_localized_video', 'tl', 'Walang naka-localize na video', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('visual_content_required', 'tl', 'Kinakailangan ng hindi bababa sa isang visual content', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('visual_content_required_msg', 'tl', 'Dapat magbigay ng hindi bababa sa isang visual content (text, larawan, audio, o video).', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('renderer', 'vi', 'Trình kết xuất', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('visual_text', 'vi', 'Văn bản trực quan', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_images_added', 'vi', 'Không có hình ảnh nào được thêm', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('audio', 'vi', 'Âm thanh', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_localized_audio', 'vi', 'Không có âm thanh được bản địa hóa', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_localized_video', 'vi', 'Không có video được bản địa hóa', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('visual_content_required', 'vi', 'Yêu cầu ít nhất một nội dung trực quan', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('visual_content_required_msg', 'vi', 'Phải cung cấp ít nhất một nội dung trực quan (văn bản, hình ảnh, âm thanh hoặc video).', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('renderer', 'tr', 'Oluşturucu', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('visual_text', 'tr', 'Görsel Metin', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_images_added', 'tr', 'Görsel eklenmedi', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('audio', 'tr', 'Ses', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_localized_audio', 'tr', 'Yerelleştirilmiş ses yok', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_localized_video', 'tr', 'Yerelleştirilmiş video yok', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('visual_content_required', 'tr', 'En az bir görsel içerik gereklidir', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('visual_content_required_msg', 'tr', 'En az bir görsel içerik (metin, resim, ses veya video) sağlanmalıdır.', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('renderer', 'el', 'Απόδοση', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('visual_text', 'el', 'Οπτικό κείμενο', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_images_added', 'el', 'Δεν προστέθηκαν εικόνες', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('audio', 'el', 'Ήχος', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_localized_audio', 'el', 'Δεν υπάρχει τοπικός ήχος', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_localized_video', 'el', 'Δεν υπάρχει τοπικό βίντεο', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('visual_content_required', 'el', 'Απαιτείται τουλάχιστον ένα οπτικό περιεχόμενο', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('visual_content_required_msg', 'el', 'Πρέπει να παρέχεται τουλάχιστον ένα οπτικό περιεχόμενο (κείμενο, εικόνα, ήχος ή βίντεο).', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('renderer', 'uk', 'Рендерер', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('visual_text', 'uk', 'Візуальний текст', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_images_added', 'uk', 'Зображення не додано', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('audio', 'uk', 'Аудіо', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_localized_audio', 'uk', 'Немає локалізованого аудіо', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_localized_video', 'uk', 'Немає локалізованого відео', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('visual_content_required', 'uk', 'Потрібен принаймні один візуальний вміст', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('visual_content_required_msg', 'uk', 'Необхідно надати принаймні один візуальний вміст (текст, зображення, аудіо або відео).', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('renderer', 'ar', 'العارض', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('visual_text', 'ar', 'نص مرئي', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_images_added', 'ar', 'لم تتم إضافة أي صور', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('audio', 'ar', 'صوت', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_localized_audio', 'ar', 'لا يوجد صوت محلي', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_localized_video', 'ar', 'لا يوجد فيديو محلي', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('visual_content_required', 'ar', 'مطلوب محتوى مرئي واحد على الأقل', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('visual_content_required_msg', 'ar', 'يجب توفير محتوى مرئي واحد على الأقل (نص أو صورة أو صوت أو فيديو).', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('renderer', 'hi', 'रेंडरर', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('visual_text', 'hi', 'विज़ुअल टेक्स्ट', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_images_added', 'hi', 'कोई चित्र नहीं जोड़ा गया', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('audio', 'hi', 'ऑडियो', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_localized_audio', 'hi', 'कोई स्थानीयकृत ऑडियो नहीं', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_localized_video', 'hi', 'कोई स्थानीयकृत वीडियो नहीं', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('visual_content_required', 'hi', 'कम से कम एक विज़ुअल सामग्री आवश्यक है', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('visual_content_required_msg', 'hi', 'कम से कम एक विज़ुअल सामग्री (टेक्स्ट, छवि, ऑडियो या वीडियो) प्रदान की जानी चाहिए।', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('renderer', 'zh', '渲染器', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('visual_text', 'zh', '视觉文本', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_images_added', 'zh', '未添加图像', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('audio', 'zh', '音频', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_localized_audio', 'zh', '没有本地化音频', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_localized_video', 'zh', '没有本地化视频', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('visual_content_required', 'zh', '至少需要一个视觉内容', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('visual_content_required_msg', 'zh', '必须提供至少一个视觉内容（文本、图像、音频或视频）。', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('renderer', 'ja', 'レンダラー', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('visual_text', 'ja', 'ビジュアルテキスト', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_images_added', 'ja', '画像が追加されていません', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('audio', 'ja', 'オーディオ', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_localized_audio', 'ja', 'ローカライズされたオーディオはありません', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_localized_video', 'ja', 'ローカライズされたビデオはありません', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('visual_content_required', 'ja', '少なくとも1つの視覚コンテンツが必要です', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('visual_content_required_msg', 'ja', '少なくとも1つの視覚コンテンツ（テキスト、画像、音声、またはビデオ）を提供する必要があります。', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('renderer', 'ko', '렌더러', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('visual_text', 'ko', '시각적 텍스트', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_images_added', 'ko', '추가된 이미지 없음', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('audio', 'ko', '오디오', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_localized_audio', 'ko', '현지화된 오디오 없음', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('no_localized_video', 'ko', '현지화된 비디오 없음', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('visual_content_required', 'ko', '하나 이상의 시각적 콘텐츠가 필요합니다', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('visual_content_required_msg', 'ko', '하나 이상의 시각적 콘텐츠(텍스트, 이미지, 오디오 또는 비디오)를 제공해야 합니다.', CURRENT_TIMESTAMP);