INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('billing_title', 'en', 'Billing', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('confirm_subscription', 'en', 'Confirm Subscription', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('billing_disclaimer', 'en', 'Subscriptions automatically renew unless cancelled. You can manage your subscription in your store settings.', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('subscribe_now', 'en', 'Subscribe Now', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('current_subscription', 'en', 'Current Subscription', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('billing_title', 'id', 'Penagihan', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('confirm_subscription', 'id', 'Konfirmasi Langganan', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('billing_disclaimer', 'id', 'Langganan diperpanjang secara otomatis kecuali dibatalkan. Anda dapat mengelola langganan di pengaturan toko Anda.', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('subscribe_now', 'id', 'Berlangganan Sekarang', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('current_subscription', 'id', 'Langganan Saat Ini', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('billing_title', 'bg', 'Фактуриране', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('confirm_subscription', 'bg', 'Потвърждаване на абонамента', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('billing_disclaimer', 'bg', 'Абонаментите се подновяват автоматично, освен ако не бъдат анулирани. Можете да управлявате абонамента си в настройките на магазина.', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('subscribe_now', 'bg', 'Абонирайте се сега', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('current_subscription', 'bg', 'Текущ абонамент', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('billing_title', 'cs', 'Fakturace', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('confirm_subscription', 'cs', 'Potvrdit předplatné', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('billing_disclaimer', 'cs', 'Předplatné se automaticky obnovuje, pokud není zrušeno. Předplatné můžete spravovat v nastavení obchodu.', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('subscribe_now', 'cs', 'Předplatit nyní', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('current_subscription', 'cs', 'Stávající předplatné', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('billing_title', 'da', 'Fakturering', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('confirm_subscription', 'da', 'Bekræft abonnement', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('billing_disclaimer', 'da', 'Abonnementer fornyes automatisk, medmindre de opsiges. Du kan administrere dit abonnement i dine butiksindstillinger.', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('subscribe_now', 'da', 'Tilmeld dig nu', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('current_subscription', 'da', 'Nuværende abonnement', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('billing_title', 'de', 'Abrechnung', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('confirm_subscription', 'de', 'Abonnement bestätigen', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('billing_disclaimer', 'de', 'Abonnements verlängern sich automatisch, sofern sie nicht gekündigt werden. Sie können Ihr Abonnement in Ihren Store-Einstellungen verwalten.', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('subscribe_now', 'de', 'Jetzt abonnieren', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('current_subscription', 'de', 'Aktuelles Abonnement', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('billing_title', 'et', 'Arveldus', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('confirm_subscription', 'et', 'Kinnita tellimus', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('billing_disclaimer', 'et', 'Tellimused uuenevad automaatselt, kui neid ei tühistata. Saate oma tellimust hallata poe seadetes.', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('subscribe_now', 'et', 'Telli kohe', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('current_subscription', 'et', 'Praegune tellimus', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('billing_title', 'es', 'Facturación', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('confirm_subscription', 'es', 'Confirmar suscripción', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('billing_disclaimer', 'es', 'Las suscripciones se renuevan automáticamente a menos que se cancelen. Puedes administrar tu suscripción en los ajustes de tu tienda.', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('subscribe_now', 'es', 'Suscribirse ahora', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('current_subscription', 'es', 'Suscripción actual', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('billing_title', 'fr', 'Facturation', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('confirm_subscription', 'fr', 'Confirmer labonnement', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('billing_disclaimer', 'fr', 'Les abonnements se renouvellent automatiquement sauf sils sont annulés. Vous pouvez gérer votre abonnement dans les paramètres de votre boutique.', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('subscribe_now', 'fr', 'Sabonner maintenant', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('current_subscription', 'fr', 'Abonnement actuel', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('billing_title', 'ga', 'Billiú', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('confirm_subscription', 'ga', 'Deimhnigh an Síntiús', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('billing_disclaimer', 'ga', 'Athnuaitear síntiúis go huathoibríoch mura gcuirtear ar ceal iad. Is féidir leat do shíntiús a bhainistiú i socruithe do stórais.', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('subscribe_now', 'ga', 'Liostáil Anois', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('current_subscription', 'ga', 'Síntiús Reatha', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('billing_title', 'hr', 'Naplata', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('confirm_subscription', 'hr', 'Potvrdi pretplatu', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('billing_disclaimer', 'hr', 'Pretplate se automatski obnavljaju osim ako se ne otkažu. Svojom pretplatom možete upravljati u postavkama trgovine.', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('subscribe_now', 'hr', 'Pretplatite se sada', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('current_subscription', 'hr', 'Trenutna pretplata', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('billing_title', 'it', 'Fatturazione', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('confirm_subscription', 'it', 'Conferma abbonamento', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('billing_disclaimer', 'it', 'Gli abbonamenti si rinnovano automaticamente a meno que non vengano annullati. Puoi gestire il tuo abbonamento nelle impostazioni del tuo store.', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('subscribe_now', 'it', 'Iscriviti ora', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('current_subscription', 'it', 'Abbonamento attuale', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('billing_title', 'lv', 'Norēķini', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('confirm_subscription', 'lv', 'Apstiprināt abonementu', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('billing_disclaimer', 'lv', 'Abonements tiek automātiski atjaunots, ja vien tas netiek atcelts. Savu abonementu varat pārvaldīt veikala iestatījumos.', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('subscribe_now', 'lv', 'Abonēt tagad', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('current_subscription', 'lv', 'Pašreizējais abonements', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('billing_title', 'lt', 'Atsiskaitymas', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('confirm_subscription', 'lt', 'Patvirtinti prenumeratą', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('billing_disclaimer', 'lt', 'Prenumeratos atnaujinamos automatiškai, nebent jos atšaukiamos. Prenumeratą galite tvarkyti parduotuvės nustatymuose.', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('subscribe_now', 'lt', 'Prenumeruoti dabar', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('current_subscription', 'lt', 'Dabartinė prenumerata', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('billing_title', 'hu', 'Számlázás', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('confirm_subscription', 'hu', 'Előfizetés megerősítése', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('billing_disclaimer', 'hu', 'Az előfizetések automatikusan megújulnak, hacsak nem mondják le őket. Az előfizetését az áruház beállításaiban kezelheti.', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('subscribe_now', 'hu', 'Feliratkozás most', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('current_subscription', 'hu', 'Jelenlegi előfizetés', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('billing_title', 'mt', 'Fatturazzjoni', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('confirm_subscription', 'mt', 'Ikkonferma l-abbonament', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('billing_disclaimer', 'mt', 'L-abbonamenti jiġdidu awtomatikament sakemm ma jiġux ikkanċellati. Tista timmaniġġja l-abbonament tiegħek fis-settings tal-maħżen tiegħek.', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('subscribe_now', 'mt', 'Abbona issa', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('current_subscription', 'mt', 'Abbonament kurrenti', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('billing_title', 'nl', 'Facturering', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('confirm_subscription', 'nl', 'Abonnement bevestigen', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('billing_disclaimer', 'nl', 'Abonnementen worden automatisch verlengd, tenzij ze worden opgezegd. Je kunt je abonnement beheren in je winkelinstellingen.', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('subscribe_now', 'nl', 'Nu abonneren', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('current_subscription', 'nl', 'Huidig abonnement', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('billing_title', 'pl', 'Rozliczenia', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('confirm_subscription', 'pl', 'Potwierdź subskrypcję', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('billing_disclaimer', 'pl', 'Subskrypcje odnawiają się automatycznie, chyba że zostaną anulowane. Możesz zarządzać subskrypcją u ustawieniach sklepu.', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('subscribe_now', 'pl', 'Subskrybuj teraz', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('current_subscription', 'pl', 'Aktualna subskrypcja', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('billing_title', 'pt', 'Faturamento', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('confirm_subscription', 'pt', 'Confirmar assinatura', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('billing_disclaimer', 'pt', 'As assinaturas são renovadas automaticamente, a menos que sejam canceladas. Você pode gerenciar sua assinatura nas configurações da sua loja.', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('subscribe_now', 'pt', 'Assinar agora', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('current_subscription', 'pt', 'Assinatura atual', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('billing_title', 'ro', 'Facturare', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('confirm_subscription', 'ro', 'Confirmă abonamentul', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('billing_disclaimer', 'ro', 'Abonamentele se reînnoiesc automat, cu excepția cazului în care sunt anulate. Vă puteți gestiona abonamentul în setările magazinului.', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('subscribe_now', 'ro', 'Abonează-te acum', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('current_subscription', 'ro', 'Abonament curent', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('billing_title', 'sk', 'Fakturácia', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('confirm_subscription', 'sk', 'Potvrdiť predplatné', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('billing_disclaimer', 'sk', 'Predplatné sa automaticky obnovuje, ak nie je zrušené. Predplatné môžete spravovať v nastaveniach obchodu.', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('subscribe_now', 'sk', 'Predplatiť teraz', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('current_subscription', 'sk', 'Aktuálne predplatné', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('billing_title', 'sl', 'Obračunavanje', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('confirm_subscription', 'sl', 'Potrdi naročnino', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('billing_disclaimer', 'sl', 'Naročnine se samodejno podaljšajo, razen če jih prekličete. Naročnino lahko upravljate v nastavitvah trgovine.', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('subscribe_now', 'sl', 'Naročite se zdaj', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('current_subscription', 'sl', 'Trenutna naročnina', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('billing_title', 'fi', 'Laskutus', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('confirm_subscription', 'fi', 'Vahvista tilaus', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('billing_disclaimer', 'fi', 'Tilaukset uusiutuvat automaattisesti, ellei niitä peruuteta. Voit hallinnoida tilaustasi kaupan asetuksista.', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('subscribe_now', 'fi', 'Tilaa nyt', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('current_subscription', 'fi', 'Nykyinen tilaus', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('billing_title', 'sv', 'Fakturering', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('confirm_subscription', 'sv', 'Bekräfta prenumeration', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('billing_disclaimer', 'sv', 'Prenumerationer förnyas automatiskt om de inte sägs upp. Du kan hantera din prenumeration i dina butiksinställningar.', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('subscribe_now', 'sv', 'Prenumerera nu', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('current_subscription', 'sv', 'Nuvarande prenumeration', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('billing_title', 'tl', 'Pagsingil', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('confirm_subscription', 'tl', 'Kumpirmahin ang Subscription', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('billing_disclaimer', 'tl', 'Awtomatikong magre-renew ang mga subscription maliban kung kakanselahin. Maaari mong pamahalaan ang iyong subscription sa mga setting ng iyong store.', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('subscribe_now', 'tl', 'Mag-subscribe Ngayon', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('current_subscription', 'tl', 'Kasalukuyang Subscription', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('billing_title', 'vi', 'Thanh toán', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('confirm_subscription', 'vi', 'Xác nhận đăng ký', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('billing_disclaimer', 'vi', 'Các gói đăng ký tự động gia hạn trừ khi bị hủy. Bạn có thể quản lý gói đăng ký của mình dalam cài đặt cửa hàng.', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('subscribe_now', 'vi', 'Đăng ký ngay', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('current_subscription', 'vi', 'Gói đăng ký hiện tại', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('billing_title', 'tr', 'Faturalandırma', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('confirm_subscription', 'tr', 'Aboneliği Onayla', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('billing_disclaimer', 'tr', 'Abonelikler, iptal edilmediği sürece otomatik olarak yenilenir. Aboneliğinizi mağaza ayarlarınızdan yönetebilirsiniz.', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('subscribe_now', 'tr', 'Şimdi Abone Ol', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('current_subscription', 'tr', 'Mevcut Abonelik', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('billing_title', 'el', 'Χρέωση', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('confirm_subscription', 'el', 'Επιβεβαίωση συνδρομής', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('billing_disclaimer', 'el', 'Οι συνδρομές ανανεώνονται αυτόματα εκτός εάν ακυρωθούν. Μπορείτε να διαχειριστείτε τη συνδρομή σας στις ρυθμίσεις του καταστήματός σας.', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('subscribe_now', 'el', 'Εγγραφείτε τώρα', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('current_subscription', 'el', 'Τρέχουσα συνδρομή', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('billing_title', 'uk', 'Білінг', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('confirm_subscription', 'uk', 'Підтвердити підписку', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('billing_disclaimer', 'uk', 'Підписки автоматично поновлюються, якщо їх не скасувати. Ви можете керувати своєю підпиською в налаштуваннях магазину.', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('subscribe_now', 'uk', 'Підписатися зараз', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('current_subscription', 'uk', 'Поточна підписка', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('billing_title', 'ar', 'الفواتير', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('confirm_subscription', 'ar', 'تأكيد الاشتراك', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('billing_disclaimer', 'ar', 'يتم تجديد الاشتراكات تلقائيًا ما لم يتم إلغاؤها. يمكنك إدارة اشتراكك في إعدادات متجرك.', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('subscribe_now', 'ar', 'اشترك الآن', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('current_subscription', 'ar', 'الاشتراك الحالي', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('billing_title', 'hi', 'बिलिंग', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('confirm_subscription', 'hi', 'सदस्यता की पुष्टि करें', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('billing_disclaimer', 'hi', 'सदस्यता स्वतः नवीनीकृत हो जाती है जब तक कि उसे रद्द न किया जाए। आप अपनी स्टोर सेटिंग्स में अपनी सदस्यता का प्रबंधन कर सकते हैं।', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('subscribe_now', 'hi', 'अभी सब्सक्राइब करें', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('current_subscription', 'hi', 'वर्तमान सदस्यता', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('billing_title', 'zh', '账单', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('confirm_subscription', 'zh', '确认订阅', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('billing_disclaimer', 'zh', '除非取消，否则订阅将自动续订。您可以在商店设置中管理您的订阅。', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('subscribe_now', 'zh', '立即订阅', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('current_subscription', 'zh', '当前订阅', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('billing_title', 'ja', '請求', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('confirm_subscription', 'ja', '定期購読を確認', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('billing_disclaimer', 'ja', '定期購読は、キャンセルされない限り自動的に更新されます。定期購読はストアの設定で管理できます。', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('subscribe_now', 'ja', '今すぐ購読', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('current_subscription', 'ja', '現在の定期購読', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('billing_title', 'ko', '청구', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('confirm_subscription', 'ko', '구독 확인', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('billing_disclaimer', 'ko', '구독은 취소하지 않는 한 자동으로 갱신됩니다. 스토어 설정에서 구독을 관리할 수 있습니다.', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('subscribe_now', 'ko', '지금 구독하기', CURRENT_TIMESTAMP);
INSERT OR REPLACE INTO ui_translations (key, lang, value, updated_at) VALUES ('current_subscription', 'ko', '현재 구독', CURRENT_TIMESTAMP);