import os
import json

TRANSLATIONS = {
    "chain bridge (budapest)": "Ланцюговий міст (Будапешт)",
    "mammoth cave national park": "Національний парк Мамонтова печера",
    "egypt": "Єгипет",
    "windsor castle": "Віндзорський замок",
    "portugal": "Португалія",
    "urinary bladder": "сечовий міхур",
    "crab nebula": "Крабоподібна туманність",
    "burj al-arab": "Бурдж-Ель-Араб",
    "patrol boat": "патрульний катер",
    "phobos": "Фобос",
    "sitar": "ситар",
    "termite": "терміт",
    "grigori rasputin": "Григорій Распутін",
    "yellowstone national park": "Єллоустоунський національний парк",
    "giant squid": "велетенський кальмар",
    "glossopharyngeal": "язикоглотковий нерв",
    "potato": "картопля",
    "samoyed": "самоїд",
    "greyhound": "ґрейгаунд",
    "albayzín": "Альбайсін",
    "shanghai tower": "Шанхайська вежа",
    "marcus aurelius": "Марк Аврелій",
    "forth bridge": "Міст Форт",
    "the geographer": "Географ",
    "pug": "мопс",
    "cytoskeleton": "цитоскелет",
    "prostate": "простата",
    "golgi apparatus": "апарат Гольджі",
    "ancient roman": "давньоримський",
    "tomato": "помідор",
    "new zealand": "Нова Зеландія",
    "vision after the sermon": "Видіння після проповіді",
    "switzerland": "Швейцарія",
    "trombone": "тромбон",
    "firefly": "світлячок",
    "galápagos tortoise": "галапагоська черепаха",
    "china": "Китай",
    "great white shark": "біла акула",
    "stag beetle": "жук-олень",
    "nicholas ii": "Микола II",
    "pisco sour": "піско сауер",
    "oculomotor": "окоруховий нерв",
    "temple of artemis": "Храм Артеміди",
    "sartorius": "кравецький м'яз",
    "shih tzu": "ши-цу",
    "the triumph of bacchus": "Тріумф Вакха",
    "sea anemone": "актинія",
    "dill": "кріп",
    "the seven deadly sins and the four last things": "Сім смертних гріхів і чотири останні речі",
    "ivan": "Іван",
    "enceladus": "Енцелад",
    "everglades national park": "Національний парк Еверглейдс",
    "clavicle": "ключиця",
    "lute": "лютня",
    "gothic": "готика",
    "opal": "опал",
    "napoleon": "Наполеон",
    "bottlenose dolphin": "афаліна",
    "dove": "голуб",
    "raft": "пліт",
    "corvette": "корвет",
    "julius caesar": "Юлій Цезар",
    "pyramids of giza": "Піраміди Гізи",
    "turkey": "Туреччина",
    "bulldog": "бульдог",
    "sphenoid": "клиноподібна кістка",
    "bedbug": "клоп",
    "milky way": "Чумацький Шлях",
    "toad": "жаба",
    "violin": "скрипка",
    "manta ray": "манта",
    "clownfish": "риба-клоун",
    "café terrace at night": "Нічне кафе на терасі",
    "frigate": "фрегат",
    "burmese python": "тигровий пітон",
    "water lily": "латаття",
    "plasma": "плазма",
    "housefly": "кімнатна муха",
    "minehunter": "тральщик",
    "quartz": "кварц",
    "hagia sophia": "Софійський собор",
    "titan": "Титан",
    "willis tower": "Вілліс-Тауер",
    "bladderwort": "пухирник",
    "rib cage": "грудна клітка",
    "typewriter": "друкарська машинка",
    "the shard": "The Shard",
    "norway": "Норвегія",
    "bongos": "бонго",
    "the card players": "Гравці в карти",
    "taipei 101": "Тайбей 101",
    "martin luther king jr.": "Мартін Лютер Кінг",
    "guitar": "гітара",
    "dragonfly": "бабка",
    "united states": "Сполучені Штати Америки",
    "petra": "Петра",
    "ribosome": "рибосома",
    "ferdinand magellan": "Фернан Магеллан",
    "buckingham palace": "Букінгемський палац",
    "voyager 2": "Вояджер-2",
    "halley's comet": "Комета Галлея",
    "hard disk drive": "жорсткий диск",
    "greece": "Греція",
    "impression, sunrise": "Враження. Схід сонця",
    "kremlin": "Кремль",
    "limestone": "вапняк",
    "ostrich": "страус",
    "vena cava": "порожниста вена",
    "carcassonne": "Каркассон",
    "edinburgh castle": "Единбурзький замок",
    "pitcher plant": "непентес",
    "submarine": "підводний човен",
    "mount rushmore": "Гора Рашмор",
    "centipede": "сороконіжка",
    "vietnam": "В'єтнам",
    "honey bee": "медоносна бджола",
    "monarch butterfly": "монарх",
    "cow": "корова",
    "christopher columbus": "Христофор Колумб",
    "cello": "віолончель",
    "tasmanian devil": "тасманійський диявол",
    "ancient greek": "давньогрецький",
    "piano": "піаніно",
    "destroyer": "есмінець",
    "dachshund": "такса",
    "australia": "Австралія",
    "drums": "барабани",
    "sagrada familia": "Саграда Фамілія",
    "baba ghanoush": "бабагануш",
    "abraj al-bait towers": "Абрадж аль-Бейт",
    "the gherkin": "Мері-Екс",
    "ceres": "Церера",
    "seahorse": "морський коник",
    "fluorite": "флюорит",
    "io": "Іо",
    "rialto bridge": "Міст Ріальто",
    "golden gate bridge": "Міст Золоті Ворота",
    "narwhal": "нарвал",
    "maltese": "мальтійська болонка",
    "salamander": "саламандра",
    "burj khalifa": "Бурдж Халіфа",
    "marco polo": "Марко Поло",
    "blimp": "дирижабль",
    "kayak": "каяк",
    "box jellyfish": "кубомедуза",
    "generalife": "Хенераліфе",
    "trevi fountain": "Фонтан Треві",
    "siberian husky": "сибірський хаскі",
    "kk100": "КК100",
    "green anaconda": "анаконда",
    "great dane": "дог",
    "wombat": "вомбат",
    "gramophone": "грамофон",
    "queen victoria": "Королева Вікторія",
    "leatherback sea turtle": "шкіряста черепаха",
    "constantine": "Констянтин",
    "cochlea": "завитка",
    "sainte-chapelle": "Сент-Шапель",
    "belgium": "Бельгія",
    "denmark": "Данія",
    "tractor": "трактор",
    "marie curie": "Марія Кюрі",
    "parthenon": "Парфенон",
    "mackinac bridge": "Міст Макінак",
    "cassiopeia": "Кассіопея",
    "vasco da gama": "Васко да Гама",
    "snail": "равлик",
    "opera house": "Оперний театр",
    "grasshopper": "коник",
    "olfactory bulb": "нюхова цибулина",
    "augustus": "Октавіан Август",
    "rottweiler": "ротвейлер",
    "poodle": "пудель",
    "peace lily": "спатифілум",
    "ancient egyptian": "давньоєгипетський",
    "praying mantis": "богомол",
    "space needle": "Спейс Нідл",
    "cabbage": "капуста",
    "solar panel": "сонячна панель",
    "confederation bridge": "Міст Конфедерації",
    "abraham lincoln": "Авраам Лінкольн",
    "latissimus dorsi": "найширший м'яз спини",
    "olfactory": "нюховий нерв",
    "flute": "флейта",
    "deltoid": "дельтоподібний м'яз",
    "gallbladder": "жовчний міхур",
    "chhatrapati shivaji terminus": "Вокзал Чхатрапаті-Шиваджі",
    "cocker spaniel": "кокер-спанієль",
    "dna helix": "спіраль ДНК",
    "hemoglobin": "гемоглобін",
    "british museum": "Британський музей",
    "semicircular canals": "півколові канали",
    "the extraction of the stone of madness": "Видалення каменю глупоти",
    "trapezius": "трапецієподібний м'яз",
    "accordion": "акордеон",
    "tower bridge": "Тауерський міст",
    "contemporary": "сучасний",
    "zygomatic": "вилична кістка",
    "marina bay sands": "Marina Bay Sands",
    "humerus": "плечова кістка",
    "golden eagle": "беркут",
    "pigeon": "голуб",
    "duomo di milano": "Міланський собор",
    "the sleeping gypsy": "Спляча циганка",
    "mistress and maid": "Господиня і служниця",
    "white house": "Білий дім",
    "quadriceps": "квадрицепс",
    "mausoleum at halicarnassus": "Мавзолей у Галікарнасі",
    "where do we come from? what are we? where are we going?": "Звідки ми прийшли? Хто ми? Куди ми йдемо?",
    "charles bridge": "Карлів міст",
    "sweden": "Швеція",
    "sydney harbour bridge": "Міст Гарбор-Брідж",
    "verrazzano-narrows bridge": "Міст Верраццано",
    "orion": "Оріон",
    "pyrite": "пірит",
    "the last judgment": "Страшний суд",
    "deconstructivism": "деконструктівізм",
    "ponte vecchio": "Понте Веккіо",
    "walrus": "морж",
    "slug": "слимак",
    "wolfgang amadeus mozart": "Вольфганг Амадей Моцарт",
    "ethmoid": "решітчаста кістка",
    "portrait of innocent x": "Портрет папи Інокентія X",
    "joan of arc": "Жанна д'Арк",
    "neuschwanstein castle": "Замок Нойшванштайн",
    "hovercraft": "судно на повітряній подушці",
    "gila monster": "арізонський ядозуб",
    "panama canal": "Панамський канал",
    "the dream": "Сон",
    "italy": "Італія",
    "plato": "Платон",
    "lysosome": "лізосома",
    "peregrine falcon": "сапсан",
    "art nouveau": "модерн",
    "silver": "срібло",
    "independence hall": "Індепенденс-хол",
    "peter": "Петро I",
    "exoplanet": "екзопланета",
    "pulsar": "пульсар",
    "széchenyi chain bridge": "Ланцюговий міст Сечені",
    "south korea": "Південна Корея",
    "laptop": "ноутбук",
    "nero": "Нерон",
    "the yellow christ": "Жовтий Христос",
    "smartwatch": "смарт-годинник",
    "france": "Франція",
    "catherine": "Катерина II",
    "pufferfish": "риба-фугу",
    "austria": "Австрія",
    "lunar eclipse": "місячне затемнення",
    "pig": "свиня",
    "robot": "робот",
    "lotus temple": "Храм Лотоса",
    "white blood cell": "лейкоцит",
    "thomas edison": "Томас Едісон",
    "echidna": "єхидна",
    "facial": "лицьовий нерв",
    "bismuth": "вісмут",
    "crux": "Південний Хрест",
    "reticulated python": "сітчастий пітон",
    "malachite": "малахіт",
    "girl with a red hat": "Дівчина в червоному капелюсі",
    "statue of zeus at olympia": "Статуя Зевса в Олімпії",
    "charon": "Харон",
    "university of virginia": "Вірджинський університет",
    "humpback whale": "горбатий кит",
    "tabbouleh": "табуле",
    "ulna": "ліктьова кістка",
    "didgeridoo": "диджериду",
    "gluteus maximus": "великий сідничний м'яз",
    "white dwarf": "білий карлик",
    "callisto": "Каллісто",
    "spinach": "шпинат",
    "gherkin": "Мері-Екс",
    "st. peter's basilica": "Собор Святого Петра",
    "german shepherd": "німецька вівчарка",
    "platypus": "качкодзьоб",
    "harmonica": "губна гармоніка",
    "neoclassical": "неокласицизм",
    "ironman": "Ironman",
    "the entombment": "Покладення в труну",
    "coriander": "коріандр",
    "new horizons": "New Horizons",
    "smart speaker": "розумна колонка",
    "baroque": "бароко",
    "synthesizer": "синтезатор",
    "bran castle": "Замок Бран",
    "hamstring": "підколінне сухожилля",
    "doberman": "доберман",
    "topaz": "топаз",
    "borscht": "борщ",
    "metropolitan museum of art": "Метрополітен-музей",
    "isaac newton": "Ісаак Ньютон",
    "mount kilimanjaro": "Кіліманджаро",
    "mastiff": "мастиф",
    "eustachian tube": "євстахієва труба",
    "christ the redeemer": "Христос-Спаситель",
    "tablet": "планшет",
    "starry night": "Зоряна ніч",
    "renaissance": "Відродження",
    "xylophone": "ксилофон",
    "supernova": "наднова",
    "ping an finance center": "Міжнародний фінансовий центр Пінань",
    "mezquita": "Мескіта",
    "floppy disk": "дискета",
    "thailand": "Таїланд",
    "japan": "Японія",
    "opossum": "опосум",
    "old woman frying eggs": "Стара, що смажить яєчню",
    "goat": "коза",
    "banyan": "баньян",
    "cruise ship": "круїзне судно",
    "redwood national park": "Редвуд",
    "harp": "арфа",
    "cygnus": "Лебідь",
    "triton": "Тритон",
    "ursa major": "Велика Ведмедиця",
    "retina": "сітківка",
    "trigeminal": "трійчастий нерв",
    "crow": "ворона",
    "united nations headquarters": "Штаб-квартира ООН",
    "millau viaduct": "Віадук Мійо",
    "cockroach": "тарган",
    "petronas towers": "Вежі Петронас",
    "trumpet": "труба",
    "modern": "модерн",
    "endoplasmic reticulum": "ендоплазматичний ретикулум",
    "postmodern": "постмодернізм",
    "optic nerve": "зоровий нерв",
    "the rokeby venus": "Венера з дзеркалом",
    "hermitage museum": "Ермітаж",
    "radius": "променева кістка",
    "hot air balloon": "повітряна куля",
    "art deco": "ар-деко",
    "vasco da gama bridge": "Міст Васко да Гама",
    "venus flytrap": "венерина мухоловка",
    "makkah royal clock tower": "Абрадж аль-Бейт",
    "rococo": "рококо",
    "colossus of rhodes": "Колос Родоський",
    "potala palace": "Палац Потала",
    "cessna 172": "Cessna 172",
    "border collie": "бордер-коллі",
    "mangrove": "мангри",
    "portrait of baldassare castiglione": "Портрет Бальдассаре Кастільйоне",
    "broccoli": "броколі",
    "digital camera": "цифрова камера"
}

def translate_file(filepath):
    with open(filepath, 'r') as f:
        data = json.load(f)
    if "answers" not in data: return
    
    # Check if already has UA
    if any(a.startswith("UA: ") for a in data["answers"]): return

    english_raw = ""
    for ans in data["answers"]:
        if ans.startswith("UK: "):
            english_raw = ans.replace("UK: ", "")
        else:
            english_raw = ans
    
    if not english_raw: return
    
    primary_term = english_raw.split(';')[0].strip().lower()
    
    # Try exact match
    ua_val = TRANSLATIONS.get(primary_term)
    
    if ua_val:
        data["answers"] = [f"UK: {english_raw}", f"UA: {ua_val}"]
        with open(filepath, 'w') as f:
            json.dump(data, f, indent=2)

def main():
    root = os.path.expanduser("~/.aliolo/cards")
    for path, dirs, files in os.walk(root):
        for file in files:
            if file.endswith(".json"):
                translate_file(os.path.join(path, file))

if __name__ == "__main__":
    main()
