import json
import os

lang_dir = "/home/vitaliinoha/aliolo/assets/lang"
os.makedirs(lang_dir, exist_ok=True)

# Base template from en.json
base_en = {
    "login": "Login",
    "username": "Username",
    "password": "Password",
    "email": "Email",
    "confirm_password": "Confirm Password",
    "create_account": "Create Account",
    "create_new_account": "Create New Account",
    "back_to_login": "Back to Login",
    "forgot_password": "Forgot Password?",
    "select_user": "Select User",
    "settings": "Settings",
    "subjects": "Subjects",
    "about": "About",
    "language": "Language",
    "english": "English",
    "ukrainian": "Ukrainian",
    "logout": "Logout",
    "session_complete": "Session Complete!",
    "xp": "XP",
    "mastery": "Mastery",
    "next": "Next",
    "back_to_subjects": "Back to Subjects",
    "select_an_answer": "Select an Answer",
    "card_details": "Card Details",
    "edit_card": "Edit Card",
    "create_new_card": "Create New Card",
    "save": "Save",
    "delete": "Delete",
    "confirm_logout": "Are you sure you want to logout?",
    "cancel": "Cancel",
    "ui_language": "UI Language",
    "general_preferences": "General Preferences",
    "sidebar_left": "Sidebar on the left",
    "sidebar_left_desc": "Move learning controls to the left side of the screen.",
    "sound_effects": "Sound Effects",
    "sound_effects_desc": "Enable audio feedback for correct and wrong answers.",
    "public_profile": "Public Profile",
    "public_profile_desc": "Show your XP and Streak on Hall of Fame.",
    "theme_mode": "Theme Mode",
    "system": "System",
    "light": "Light",
    "dark": "Dark",
    "keyboard_shortcuts": "Keyboard Shortcuts",
    "previous_card": "Previous Card",
    "next_card": "Next Card",
    "shortcuts_hint": "Press the key you want to use with Ctrl.",
    "record_shortcut": "Record Shortcut",
    "setting_saved": "Setting saved",
    "default_learning_language": "Default Learning Language",
    "default_learning_language_desc": "Pre-selects this language on the subjects page.",
    "left_arrow": "Left Arrow",
    "right_arrow": "Right Arrow",
    "up_arrow": "Up Arrow",
    "down_arrow": "Down Arrow",
    "mock_email_title": "Mock Email Inbox",
    "reset_code_sent": "Reset code for: ",
    "send_verification_code": "Send verification code?",
    "verify": "Verify",
    "update": "Update",
    "send_code": "Send Code",
    "invalid_password": "Invalid password",
    "fill_all_fields": "Please fill all fields",
    "passwords_dont_match": "Passwords do not match",
    "user_exists": "User already exists",
    "email_in_use": "Email is already in use",
    "account_created": "Account created!",
    "invalid_email": "Invalid email address",
    "no_cards_found": "No cards found for language",
    "go_to_manager": "Go to Library Manager",
    "mastered": "mastered",
    "cards": "cards",
    "finished_session": "You finished {count} cards. XP bonus awarded!",
    "select_lang": "Select Language",
    "learning": "Learning",
    "bronze": "BRONZE",
    "silver": "SILVER",
    "gold": "GOLD",
    "new": "NEW",
    "subject": "Subject",
    "prompt_optional": "Prompt / Question",
    "video_url_optional": "Video URL (Optional)",
    "card_level": "Card Level (1-20)",
    "multi_lang_answers": "Multi-language Answers",
    "multi_lang_prompts": "Multi-language Prompts",
    "lang_abbr": "Lang",
    "answer": "Answer",
    "prompt_label": "Prompt",
    "add_lang_translation": "Add Language Translation",
    "add_prompt_translation": "Add Prompt Translation",
    "prev": "Prev",
    "unsaved_changes": "Unsaved Changes",
    "save_before_nav": "Do you want to save changes before navigating?",
    "discard": "Discard",
    "delete_card_confirm": "Delete this card?",
    "click_to_select_image": "Click to select image",
    "video_link": "Video Link",
    "required": "Required",
    "enter_number": "Enter a number",
    "invalid_number": "Invalid number",
    "level_range": "Must be between 1 and 20",
    "provide_at_least_one_answer": "Please provide at least one answer",
    "enter_or_select_subject": "Please enter or select a subject",
    "manage_library": "Manage Library ({sCount} subjects, {cCount} cards)",
    "selected_count": "{count} Selected",
    "delete_selected_cards": "Delete selected cards?",
    "no_cards_in_library": "No cards found in the library.",
    "card_label": "card",
    "cards_label": "cards",
    "answer_label": "answer",
    "answers_label": "answers",
    "level": "Level",
    "pro_label": "PRO",
    "about_tagline": "The smart companion that helps your brain learn more effectively.",
    "algorithm_title": "THE ALIOLO ALGORITHM",
    "feat_spacing_title": "Cognitive Spacing (SM-2)",
    "feat_spacing_desc": "A full implementation of the SuperMemo-2 model predicts your memory decay and schedules reviews at the peak of retention.",
    "feat_adaptive_title": "Adaptive Response Timing",
    "feat_adaptive_desc": "The system monitors your recognition speed across MCQ options, dynamically adjusting intervals to push your boundaries.",
    "feat_recognition_title": "Visual Pattern Training",
    "feat_recognition_desc": "Immersive identification drills designed to build instant \"muscle memory\" for complex visual subjects.",
    "feat_mastery_title": "Visual Mastery & XP",
    "feat_mastery_desc": "Dynamic XP rewards difficulty, while real-time mastery badges (Bronze, Silver, Gold) track your journey from novice to expert.",
    "licenses": "Licenses",
    "master_visual_ease": "Master visual subjects with ease.",
    "all_rights_reserved": "© 2026 Aliolo. All rights reserved.",
    "hall_of_fame": "Hall of Fame",
    "streak": "Streak",
    "day": "day",
    "days": "days",
    "you_rank": "You are ranked #{rank}",
    "no_leaderboard_data": "No leaderboard data available.",
    "profile": "Profile",
    "profile_title": "My Profile & Progress",
    "daily_goal": "Daily Goal",
    "cards_per_day": "cards per day",
    "session_size": "Session Size",
    "cards_per_session": "cards per session",
    "options_count": "Number of Answers",
    "options_per_card": "options per card",
    "total_xp": "Total XP",
    "current_streak": "Current Streak",
    "change_avatar": "Change Avatar",
    "delete_account": "Delete Account",
    "delete_account_confirm": "Are you sure you want to delete your account? This action is permanent.",
    "enter_pass_to_confirm": "Enter your password to confirm",
    "account_deleted": "Account deleted successfully",
    "error_deleting_account": "Could not delete account. Check your password.",
    "version": "Version",
    "reset_password_for": "Reset Password for: ",
    "digit_code": "6-digit Code",
    "user_not_found": "User not found",
    "invalid_code": "Invalid code",
    "password_reset_success": "Password reset successful",
    "to_label": "To",
    "email_subject": "Subject",
    "reset_code_email_title": "Password Reset Code",
    "code_label": "Code",
    "new_password": "New Password",
    "confirm": "Confirm",
    "manage_subjects": "Manage Subjects",
    "manage_cards": "Manage Cards",
    "manage_learning_langs": "Manage Learning Languages",
    "add_subject": "Add Subject",
    "enter_subject_name": "Enter subject name",
    "delete_subject_confirm": "Delete subject '{subject}' and all {count} cards inside?"
}

# Key translations for Spanish (es)
es = {
    "login": "Iniciar sesión",
    "username": "Nombre de usuario",
    "password": "Contraseña",
    "email": "Correo electrónico",
    "confirm_password": "Confirmar contraseña",
    "create_account": "Crear cuenta",
    "create_new_account": "Crear nueva cuenta",
    "back_to_login": "Volver al inicio",
    "forgot_password": "¿Olvidó su contraseña?",
    "select_user": "Seleccionar usuario",
    "settings": "Ajustes",
    "subjects": "Temas",
    "about": "Acerca de",
    "language": "Idioma",
    "english": "Inglés",
    "ukrainian": "Ucraniano",
    "logout": "Cerrar sesión",
    "session_complete": "¡Sesión completada!",
    "xp": "XP",
    "mastery": "Dominio",
    "next": "Siguiente",
    "back_to_subjects": "Volver a temas",
    "select_an_answer": "Seleccione una respuesta",
    "card_details": "Detalles de la tarjeta",
    "edit_card": "Editar tarjeta",
    "create_new_card": "Crear nueva tarjeta",
    "save": "Guardar",
    "delete": "Eliminar",
    "confirm_logout": "¿Está seguro de que desea cerrar sesión?",
    "cancel": "Cancelar",
    "ui_language": "Idioma de la interfaz",
    "general_preferences": "Preferencias generales",
    "sidebar_left": "Barra lateral a la izquierda",
    "sidebar_left_desc": "Mover controles a la izquierda de la pantalla.",
    "sound_effects": "Efectos de sonido",
    "sound_effects_desc": "Habilitar audio para respuestas.",
    "public_profile": "Perfil público",
    "public_profile_desc": "Mostrar XP y racha en el Salón de la Fama.",
    "theme_mode": "Modo de tema",
    "system": "Sistema",
    "light": "Claro",
    "dark": "Oscuro",
    "keyboard_shortcuts": "Atajos de teclado",
    "previous_card": "Tarjeta anterior",
    "next_card": "Siguiente tarjeta",
    "shortcuts_hint": "Presione la tecla que desea usar con Ctrl.",
    "record_shortcut": "Grabar atajo",
    "setting_saved": "Ajuste guardado",
    "default_learning_language": "Idioma de aprendizaje por defecto",
    "default_learning_language_desc": "Preselecciona este idioma en la página de temas.",
    "left_arrow": "Flecha izquierda",
    "right_arrow": "Flecha derecha",
    "up_arrow": "Flecha arriba",
    "down_arrow": "Flecha abajo",
    "mock_email_title": "Bandeja de entrada simulada",
    "reset_code_sent": "Código de restablecimiento para: ",
    "send_verification_code": "¿Enviar código de verificación?",
    "verify": "Verificar",
    "update": "Actualizar",
    "send_code": "Enviar código",
    "invalid_password": "Contraseña inválida",
    "fill_all_fields": "Por favor complete todos los campos",
    "passwords_dont_match": "Las contraseñas no coinciden",
    "user_exists": "El usuario ya existe",
    "email_in_use": "El correo ya está en uso",
    "account_created": "¡Cuenta creada!",
    "invalid_email": "Dirección de correo inválida",
    "no_cards_found": "No se encontraron tarjetas para el idioma",
    "go_to_manager": "Ir al administrador de biblioteca",
    "mastered": "dominado",
    "cards": "tarjetas",
    "finished_session": "Terminaste {count} tarjetas. ¡Bono de XP otorgado!",
    "select_lang": "Seleccionar idioma",
    "learning": "Aprendizaje",
    "bronze": "BRONCE",
    "silver": "PLATA",
    "gold": "ORO",
    "new": "NUEVO",
    "subject": "Tema",
    "prompt_optional": "Pregunta / Indicación",
    "video_url_optional": "URL de video (Opcional)",
    "card_level": "Nivel de tarjeta (1-20)",
    "multi_lang_answers": "Respuestas multilingües",
    "multi_lang_prompts": "Indicaciones multilingües",
    "lang_abbr": "Id.",
    "answer": "Respuesta",
    "prompt_label": "Pregunta",
    "add_lang_translation": "Agregar traducción de idioma",
    "add_prompt_translation": "Agregar traducción de indicación",
    "prev": "Anterior",
    "unsaved_changes": "Cambios sin guardar",
    "save_before_nav": "¿Desea guardar los cambios antes de navegar?",
    "discard": "Descartar",
    "delete_card_confirm": "¿Eliminar esta tarjeta?",
    "click_to_select_image": "Clic para seleccionar imagen",
    "video_link": "Enlace de video",
    "required": "Obligatorio",
    "enter_number": "Ingrese un número",
    "invalid_number": "Número inválido",
    "level_range": "Debe estar entre 1 y 20",
    "provide_at_least_one_answer": "Por favor proporcione al menos una respuesta",
    "enter_or_select_subject": "Por favor ingrese o seleccione un tema",
    "manage_library": "Administrar biblioteca ({sCount} temas, {cCount} tarjetas)",
    "selected_count": "{count} seleccionado(s)",
    "delete_selected_cards": "¿Eliminar tarjetas seleccionadas?",
    "no_cards_in_library": "No se encontraron tarjetas en la biblioteca.",
    "card_label": "tarjeta",
    "cards_label": "tarjetas",
    "answer_label": "respuesta",
    "answers_label": "respuestas",
    "level": "Nivel",
    "pro_label": "PRO",
    "about_tagline": "El compañero inteligente que ayuda a tu cerebro a aprender mejor.",
    "algorithm_title": "EL ALGORITMO ALIOLO",
    "feat_spacing_title": "Espaciado cognitivo (SM-2)",
    "feat_spacing_desc": "Una implementación completa del modelo SuperMemo-2 predice el olvido y programa repasos.",
    "feat_adaptive_title": "Tiempo de respuesta adaptativo",
    "feat_adaptive_desc": "El sistema monitorea la velocidad de reconocimiento para ajustar los intervalos.",
    "feat_recognition_title": "Entrenamiento de patrones visuales",
    "feat_recognition_desc": "Ejercicios de identificación diseñados para crear memoria muscular visual.",
    "feat_mastery_title": "Dominio visual y XP",
    "feat_mastery_desc": "Recompensas dinámicas de XP y medallas de dominio (Bronce, Plata, Oro).",
    "licenses": "Licencias",
    "master_visual_ease": "Domina temas visuales con facilidad.",
    "all_rights_reserved": "© 2026 Aliolo. Todos los derechos reservados.",
    "hall_of_fame": "Salón de la Fama",
    "streak": "Racha",
    "day": "día",
    "days": "días",
    "you_rank": "Estás en el puesto #{rank}",
    "no_leaderboard_data": "No hay datos de clasificación disponibles.",
    "profile": "Perfil",
    "profile_title": "Mi Perfil y Progreso",
    "daily_goal": "Meta diaria",
    "cards_per_day": "tarjetas por día",
    "session_size": "Tamaño de sesión",
    "cards_per_session": "tarjetas por sesión",
    "options_count": "Número de respuestas",
    "options_per_card": "opciones por tarjeta",
    "total_xp": "XP total",
    "current_streak": "Racha actual",
    "change_avatar": "Cambiar avatar",
    "delete_account": "Eliminar cuenta",
    "delete_account_confirm": "¿Seguro que desea eliminar su cuenta? Esta acción es permanente.",
    "enter_pass_to_confirm": "Ingrese su contraseña para confirmar",
    "account_deleted": "Cuenta eliminada con éxito",
    "error_deleting_account": "No se pudo eliminar la cuenta. Revise su contraseña.",
    "version": "Versión",
    "reset_password_for": "Restablecer contraseña para: ",
    "digit_code": "Código de 6 dígitos",
    "user_not_found": "Usuario no encontrado",
    "invalid_code": "Código inválido",
    "password_reset_success": "Contraseña restablecida con éxito",
    "to_label": "Para",
    "email_subject": "Asunto",
    "reset_code_email_title": "Código de restablecimiento",
    "code_label": "Código",
    "new_password": "Nueva contraseña",
    "confirm": "Confirmar",
    "manage_subjects": "Administrar temas",
    "manage_cards": "Administrar tarjetas",
    "manage_learning_langs": "Administrar idiomas de aprendizaje",
    "add_subject": "Agregar tema",
    "enter_subject_name": "Ingrese el nombre del tema",
    "delete_subject_confirm": "¿Eliminar el tema '{subject}' y las {count} tarjetas en su interior?"
}

# French (fr)
fr = {
    "login": "Connexion",
    "username": "Nom d'utilisateur",
    "password": "Mot de passe",
    "email": "E-mail",
    "confirm_password": "Confirmer le mot de passe",
    "create_account": "Créer un compte",
    "create_new_account": "Créer un nouveau compte",
    "back_to_login": "Retour à la connexion",
    "forgot_password": "Mot de passe oublié ?",
    "select_user": "Sélectionner un utilisateur",
    "settings": "Paramètres",
    "subjects": "Sujets",
    "about": "À propos",
    "language": "Langue",
    "english": "Anglais",
    "ukrainian": "Ukrainien",
    "logout": "Déconnexion",
    "session_complete": "Session terminée !",
    "xp": "XP",
    "mastery": "Maîtrise",
    "next": "Suivant",
    "back_to_subjects": "Retour aux sujets",
    "select_an_answer": "Sélectionnez une réponse",
    "card_details": "Détails de la carte",
    "edit_card": "Modifier la carte",
    "create_new_card": "Créer une nouvelle carte",
    "save": "Enregistrer",
    "delete": "Supprimer",
    "confirm_logout": "Voulez-vous vraiment vous déconnecter ?",
    "cancel": "Annuler",
    "ui_language": "Langue de l'interface",
    "general_preferences": "Préférences générales",
    "sidebar_left": "Barre latérale à gauche",
    "sidebar_left_desc": "Déplacer les commandes à gauche de l'écran.",
    "sound_effects": "Effets sonores",
    "sound_effects_desc": "Activer le retour audio pour les réponses.",
    "public_profile": "Profil public",
    "public_profile_desc": "Afficher l'XP et la série dans le Temple de la Renommée.",
    "theme_mode": "Mode thème",
    "system": "Système",
    "light": "Clair",
    "dark": "Sombre",
    "keyboard_shortcuts": "Raccourcis clavier",
    "previous_card": "Carte précédente",
    "next_card": "Carte suivante",
    "shortcuts_hint": "Appuyez sur la touche à utiliser avec Ctrl.",
    "record_shortcut": "Enregistrer le raccourci",
    "setting_saved": "Paramètre enregistré",
    "default_learning_language": "Langue d'apprentissage par défaut",
    "default_learning_language_desc": "Présélectionne cette langue sur la page des sujets.",
    "left_arrow": "Flèche gauche",
    "right_arrow": "Flèche droite",
    "up_arrow": "Flèche haut",
    "down_arrow": "Flèche bas",
    "mock_email_title": "Boîte de réception simulée",
    "reset_code_sent": "Code de réinitialisation pour : ",
    "send_verification_code": "Envoyer le code de vérification ?",
    "verify": "Vérifier",
    "update": "Mettre à jour",
    "send_code": "Envoyer le code",
    "invalid_password": "Mot de passe invalide",
    "fill_all_fields": "Veuillez remplir tous les champs",
    "passwords_dont_match": "Les mots de passe ne correspondent pas",
    "user_exists": "L'utilisateur existe déjà",
    "email_in_use": "L'e-mail est déjà utilisé",
    "account_created": "Compte créé !",
    "invalid_email": "Adresse e-mail invalide",
    "no_cards_found": "Aucune carte trouvée pour la langue",
    "go_to_manager": "Aller au gestionnaire de bibliothèque",
    "mastered": "maîtrisé",
    "cards": "cartes",
    "finished_session": "Vous avez terminé {count} cartes. Bonus XP accordé !",
    "select_lang": "Sélectionner la langue",
    "learning": "Apprentissage",
    "bronze": "BRONZE",
    "silver": "ARGENT",
    "gold": "OR",
    "new": "NOUVEAU",
    "subject": "Sujet",
    "prompt_optional": "Invite / Question",
    "video_url_optional": "URL vidéo (optionnel)",
    "card_level": "Niveau de carte (1-20)",
    "multi_lang_answers": "Réponses multilingues",
    "multi_lang_prompts": "Invites multilingues",
    "lang_abbr": "Lang",
    "answer": "Réponse",
    "prompt_label": "Invite",
    "add_lang_translation": "Ajouter une traduction de langue",
    "add_prompt_translation": "Ajouter une traduction d'invite",
    "prev": "Préc.",
    "unsaved_changes": "Modifications non enregistrées",
    "save_before_nav": "Enregistrer les modifications avant de naviguer ?",
    "discard": "Abandonner",
    "delete_card_confirm": "Supprimer cette carte ?",
    "click_to_select_image": "Cliquer pour sélectionner une image",
    "video_link": "Lien vidéo",
    "required": "Obligatoire",
    "enter_number": "Entrez un nombre",
    "invalid_number": "Nombre invalide",
    "level_range": "Doit être entre 1 et 20",
    "provide_at_least_one_answer": "Veuillez fournir au moins une réponse",
    "enter_or_select_subject": "Veuillez entrer ou sélectionner un sujet",
    "manage_library": "Gérer la bibliothèque ({sCount} sujets, {cCount} cartes)",
    "selected_count": "{count} sélectionné(s)",
    "delete_selected_cards": "Supprimer les cartes sélectionnées ?",
    "no_cards_in_library": "Aucune carte trouvée dans la bibliothèque.",
    "card_label": "carte",
    "cards_label": "cartes",
    "answer_label": "réponse",
    "answers_label": "réponses",
    "level": "Niveau",
    "pro_label": "PRO",
    "about_tagline": "Le compagnon intelligent qui aide votre cerveau à apprendre plus efficacement.",
    "algorithm_title": "L'ALGORITHME ALIOLO",
    "feat_spacing_title": "Espacement cognitif (SM-2)",
    "feat_spacing_desc": "Une implémentation complète du modèle SuperMemo-2 prédit l'oubli et planifie les révisions.",
    "feat_adaptive_title": "Temps de réponse adaptatif",
    "feat_adaptive_desc": "Le système surveille la vitesse de reconnaissance pour ajuster les intervalles.",
    "feat_recognition_title": "Entraînement aux modèles visuels",
    "feat_recognition_desc": "Exercices d'identification conçus pour créer une mémoire musculaire visuelle.",
    "feat_mastery_title": "Maîtrise visuelle & XP",
    "feat_mastery_desc": "Récompenses XP dynamiques et badges de maîtrise (Bronze, Argent, Or).",
    "licenses": "Licences",
    "master_visual_ease": "Maîtrisez les sujets visuels en toute simplicité.",
    "all_rights_reserved": "© 2026 Aliolo. Tous droits réservés.",
    "hall_of_fame": "Temple de la renommée",
    "streak": "Série",
    "day": "jour",
    "days": "jours",
    "you_rank": "Vous êtes classé #{rank}",
    "no_leaderboard_data": "Aucune donnée de classement disponible.",
    "profile": "Profil",
    "profile_title": "Mon profil et mes progrès",
    "daily_goal": "Objectif quotidien",
    "cards_per_day": "cartes par jour",
    "session_size": "Taille de session",
    "cards_per_session": "cartes par session",
    "options_count": "Nombre de réponses",
    "options_per_card": "options par carte",
    "total_xp": "XP total",
    "current_streak": "Série actuelle",
    "change_avatar": "Changer d'avatar",
    "delete_account": "Supprimer le compte",
    "delete_account_confirm": "Voulez-vous vraiment supprimer votre compte ? Cette action est définitive.",
    "enter_pass_to_confirm": "Entrez votre mot de passe pour confirmer",
    "account_deleted": "Compte supprimé avec succès",
    "error_deleting_account": "Impossible de supprimer le compte. Vérifiez votre mot de passe.",
    "version": "Version",
    "reset_password_for": "Réinitialiser le mot de passe pour : ",
    "digit_code": "Code à 6 chiffres",
    "user_not_found": "Utilisateur non trouvé",
    "invalid_code": "Code invalide",
    "password_reset_success": "Réinitialisation du mot de passe réussie",
    "to_label": "À",
    "email_subject": "Sujet",
    "reset_code_email_title": "Code de réinitialisation",
    "code_label": "Code",
    "new_password": "Nouveau mot de passe",
    "confirm": "Confirmer",
    "manage_subjects": "Gérer les sujets",
    "manage_cards": "Gérer les cartes",
    "manage_learning_langs": "Gérer les langues d'apprentissage",
    "add_subject": "Ajouter un sujet",
    "enter_subject_name": "Entrez le nom du sujet",
    "delete_subject_confirm": "Supprimer le sujet '{subject}' et les {count} cartes à l'intérieur ?"
}

# German (de)
de = {
    "login": "Anmelden",
    "username": "Benutzername",
    "password": "Passwort",
    "email": "E-Mail",
    "confirm_password": "Passwort bestätigen",
    "create_account": "Konto erstellen",
    "create_new_account": "Neues Konto erstellen",
    "back_to_login": "Zurück zum Login",
    "forgot_password": "Passwort vergessen?",
    "select_user": "Benutzer auswählen",
    "settings": "Einstellungen",
    "subjects": "Fächer",
    "about": "Über",
    "language": "Sprache",
    "logout": "Abmelden",
    "session_complete": "Sitzung abgeschlossen!",
    "xp": "XP",
    "mastery": "Meisterschaft",
    "next": "Weiter",
    "back_to_subjects": "Zurück zu den Fächern",
    "select_an_answer": "Wählen Sie eine Antwort",
    "card_details": "Kartendetails",
    "edit_card": "Karte bearbeiten",
    "create_new_card": "Neue Karte erstellen",
    "save": "Speichern",
    "delete": "Löschen",
    "confirm_logout": "Sind Sie sicher, dass Sie sich abmelden möchten?",
    "cancel": "Abbrechen",
    "ui_language": "Sprache der Benutzeroberfläche",
    "general_preferences": "Allgemeine Einstellungen",
    "sidebar_left": "Seitenleiste links",
    "sidebar_left_desc": "Lernsteuerelemente nach links verschieben.",
    "sound_effects": "Soundeffekte",
    "sound_effects_desc": "Audio-Feedback für Antworten aktivieren.",
    "public_profile": "Öffentliches Profil",
    "public_profile_desc": "Zeigen Sie XP und Streak in der Ruhmeshalle.",
    "theme_mode": "Design-Modus",
    "system": "System",
    "light": "Hell",
    "dark": "Dunkel",
    "keyboard_shortcuts": "Tastenkombinationen",
    "record_shortcut": "Kombination aufnehmen",
    "setting_saved": "Einstellung gespeichert",
    "default_learning_language": "Standard-Lernsprache",
    "default_learning_language_desc": "Wählt diese Sprache auf der Fächerseite vor.",
    "mock_email_title": "Test-Posteingang",
    "reset_code_sent": "Zurücksetzungscode für: ",
    "send_verification_code": "Verifizierungscode senden?",
    "verify": "Verifizieren",
    "update": "Aktualisieren",
    "send_code": "Code senden",
    "invalid_password": "Ungültiges Passwort",
    "fill_all_fields": "Bitte füllen Sie alle Felder aus",
    "passwords_dont_match": "Passwörter stimmen nicht überein",
    "user_exists": "Benutzer existiert bereits",
    "email_in_use": "E-Mail wird bereits verwendet",
    "account_created": "Konto erstellt!",
    "invalid_email": "Ungültige E-Mail-Adresse",
    "no_cards_found": "Keine Karten für Sprache gefunden",
    "go_to_manager": "Zur Bibliotheksverwaltung",
    "mastered": "gelernt",
    "cards": "Karten",
    "finished_session": "Sie haben {count} Karten abgeschlossen. XP-Bonus erhalten!",
    "select_lang": "Sprache wählen",
    "learning": "Lernen",
    "bronze": "BRONZE",
    "silver": "SILBER",
    "gold": "GOLD",
    "new": "NEU",
    "subject": "Fach",
    "prompt_optional": "Frage / Hinweis",
    "video_url_optional": "Video-URL (optional)",
    "card_level": "Kartenebene (1-20)",
    "multi_lang_answers": "Mehrsprachige Antworten",
    "multi_lang_prompts": "Mehrsprachige Fragen",
    "lang_abbr": "Spr.",
    "answer": "Antwort",
    "prompt_label": "Frage",
    "prev": "Zurück",
    "unsaved_changes": "Ungespeicherte Änderungen",
    "save_before_nav": "Änderungen vor dem Verlassen speichern?",
    "discard": "Verwerfen",
    "delete_card_confirm": "Diese Karte löschen?",
    "click_to_select_image": "Klicken, um Bild auszuwählen",
    "video_link": "Video-Link",
    "required": "Erforderlich",
    "enter_number": "Nummer eingeben",
    "invalid_number": "Ungültige Nummer",
    "level_range": "Muss zwischen 1 und 20 liegen",
    "provide_at_least_one_answer": "Bitte geben Sie mindestens eine Antwort an",
    "enter_or_select_subject": "Bitte geben Sie ein Fach ein oder wählen Sie eines aus",
    "manage_library": "Bibliothek verwalten ({sCount} Fächer, {cCount} Karten)",
    "selected_count": "{count} ausgewählt",
    "delete_selected_cards": "Ausgewählte Karten löschen?",
    "no_cards_in_library": "Keine Karten in der Bibliothek gefunden.",
    "card_label": "Karte",
    "cards_label": "Karten",
    "answer_label": "Antwort",
    "answers_label": "Antworten",
    "level": "Ebene",
    "pro_label": "PRO",
    "about_tagline": "Der smarte Begleiter, der Ihrem Gehirn hilft, effektiver zu lernen.",
    "algorithm_title": "DER ALIOLO-ALGORITHMUS",
    "feat_spacing_title": "Kognitive Abstände (SM-2)",
    "feat_spacing_desc": "Eine vollständige Implementierung des SuperMemo-2-Modells sagt das Vergessen voraus.",
    "feat_adaptive_title": "Adaptive Reaktionszeit",
    "feat_adaptive_desc": "Das System überwacht die Erkennungsgeschwindigkeit, um die Intervalle anzupassen.",
    "feat_recognition_title": "Visuelles Mustertraining",
    "feat_recognition_desc": "Identifikationsübungen, um ein visuelles Muskelgedächtnis aufzubauen.",
    "feat_mastery_title": "Visuelle Meisterschaft & XP",
    "feat_mastery_desc": "Dynamische XP-Belohnungen und Meisterschaftsabzeichen (Bronze, Silber, Gold).",
    "licenses": "Lizenzen",
    "master_visual_ease": "Visuelle Themen mühelos meistern.",
    "all_rights_reserved": "© 2026 Aliolo. Alle Rechte vorbehalten.",
    "hall_of_fame": "Ruhmeshalle",
    "streak": "Serie",
    "day": "Tag",
    "days": "Tage",
    "you_rank": "Du bist auf Platz #{rank}",
    "no_leaderboard_data": "Keine Bestenlistendaten verfügbar.",
    "profile": "Profil",
    "profile_title": "Mein Profil & Fortschritt",
    "daily_goal": "Tagesziel",
    "cards_per_day": "Karten pro Tag",
    "session_size": "Sitzungsgröße",
    "cards_per_session": "Karten pro Sitzung",
    "options_count": "Anzahl der Antworten",
    "options_per_card": "Optionen pro Karte",
    "total_xp": "Gesamt-XP",
    "current_streak": "Aktuelle Serie",
    "change_avatar": "Avatar ändern",
    "delete_account": "Konto löschen",
    "delete_account_confirm": "Sind Sie sicher, dass Sie Ihr Konto löschen möchten? Dies ist permanent.",
    "enter_pass_to_confirm": "Passwort zur Bestätigung eingeben",
    "account_deleted": "Konto erfolgreich gelöscht",
    "error_deleting_account": "Konto konnte nicht gelöscht werden. Passwort prüfen.",
    "version": "Version",
    "reset_password_for": "Passwort zurücksetzen für: ",
    "digit_code": "6-digit Code",
    "user_not_found": "Benutzer nicht gefunden",
    "invalid_code": "Ungültiger Code",
    "password_reset_success": "Passwort erfolgreich zurückgesetzt",
    "to_label": "An",
    "email_subject": "Betreff",
    "reset_code_email_title": "Code zum Zurücksetzen",
    "code_label": "Code",
    "new_password": "Neues Passwort",
    "confirm": "Bestätigen",
    "manage_subjects": "Fächer verwalten",
    "manage_cards": "Karten verwalten",
    "manage_learning_langs": "Lernsprachen verwalten",
    "add_subject": "Fach hinzufügen",
    "enter_subject_name": "Fachnamen eingeben",
    "delete_subject_confirm": "Fach '{subject}' und alle {count} Karten darin löschen?"
}

# Key translations for Ukrainian (uk)
uk = {
    "login": "Увійти",
    "username": "Ім'я користувача",
    "password": "Пароль",
    "email": "Електронна пошта",
    "confirm_password": "Підтвердіть пароль",
    "create_account": "Створити акаунт",
    "create_new_account": "Створити новий акаунт",
    "back_to_login": "Назад до входу",
    "forgot_password": "Забули пароль?",
    "select_user": "Оберіть користувача",
    "settings": "Налаштування",
    "subjects": "Предмети",
    "about": "Про додаток",
    "language": "Мова",
    "english": "Англійська",
    "ukrainian": "Українська",
    "logout": "Вийти",
    "session_complete": "Сесію завершено!",
    "xp": "XP",
    "mastery": "Майстерність",
    "next": "Далі",
    "back_to_subjects": "Назад до предметів",
    "select_an_answer": "Оберіть відповідь",
    "card_details": "Деталі картки",
    "edit_card": "Редагувати картку",
    "create_new_card": "Створити нову картку",
    "save": "Зберегти",
    "delete": "Видалити",
    "confirm_logout": "Ви впевнені, що хочете вийти?",
    "cancel": "Скасувати",
    "ui_language": "Мова інтерфейсу",
    "general_preferences": "Загальні налаштування",
    "sidebar_left": "Бічна панель зліва",
    "sidebar_left_desc": "Перемістити елементи керування вліво.",
    "sound_effects": "Звукові ефекти",
    "sound_effects_desc": "Увімкнути звуковий супровід відповідей.",
    "public_profile": "Публічний профіль",
    "public_profile_desc": "Показувати ваш XP та серію у Залі слави.",
    "theme_mode": "Тема",
    "system": "Системна",
    "light": "Світла",
    "dark": "Темна",
    "keyboard_shortcuts": "Гарячі клавіші",
    "previous_card": "Попередня картка",
    "next_card": "Наступна картка",
    "shortcuts_hint": "Натисніть клавішу, яку хочете використовувати з Ctrl.",
    "record_shortcut": "Записати клавішу",
    "setting_saved": "Налаштування збережено",
    "default_learning_language": "Основна мова навчання",
    "default_learning_language_desc": "Попередньо обирає цю мову на сторінці предметів.",
    "left_arrow": "Стрілка вліво",
    "right_arrow": "Стрілка вправо",
    "up_arrow": "Стрілка вгору",
    "down_arrow": "Стрілка вниз",
    "mock_email_title": "Тестова поштова скринька",
    "reset_code_sent": "Код скидання для: ",
    "send_verification_code": "Надіслати код підтвердження?",
    "verify": "Перевірити",
    "update": "Оновити",
    "send_code": "Надіслати код",
    "invalid_password": "Невірний пароль",
    "fill_all_fields": "Будь ласка, заповніть усі поля",
    "passwords_dont_match": "Паролі не співпадають",
    "user_exists": "Користувач уже існує",
    "email_in_use": "Електронна пошта вже використовується",
    "account_created": "Акаунт створено!",
    "invalid_email": "Невірна адреса електронної пошти",
    "no_cards_found": "Не знайдено карток для мови",
    "go_to_manager": "Перейти до менеджера бібліотеки",
    "mastered": "засвоєно",
    "cards": "карток",
    "finished_session": "Ви завершили {count} карток. Нараховано бонус XP!",
    "select_lang": "Оберіть мову",
    "learning": "Навчання",
    "bronze": "БРОНЗА",
    "silver": "СРІБЛО",
    "gold": "ЗОЛОТО",
    "new": "НОВА",
    "subject": "Предмет",
    "prompt_optional": "Підказка / Питання",
    "video_url_optional": "URL відео (опційно)",
    "card_level": "Рівень картки (1-20)",
    "multi_lang_answers": "Мультимовні відповіді",
    "multi_lang_prompts": "Мультимовні підказки",
    "lang_abbr": "Мова",
    "answer": "Відповідь",
    "prompt_label": "Підказка",
    "add_lang_translation": "Додати переклад",
    "add_prompt_translation": "Додати варіант підказки",
    "prev": "Попер.",
    "unsaved_changes": "Незбережені зміни",
    "save_before_nav": "Бажаєте зберегти зміни перед переходом?",
    "discard": "Відхилити",
    "delete_card_confirm": "Видалити цю картку?",
    "click_to_select_image": "Натисніть, щоб обрати зображення",
    "video_link": "Посилання на відео",
    "required": "Обов'язково",
    "enter_number": "Введіть число",
    "invalid_number": "Невірне число",
    "level_range": "Має бути від 1 до 20",
    "provide_at_least_one_answer": "Будь ласка, вкажіть хоча б одну відповідь",
    "enter_or_select_subject": "Будь ласка, вдіть або оберіть предмет",
    "manage_library": "Керування бібліотекою ({sCount} предметів, {cCount} карток)",
    "selected_count": "Вибрано: {count}",
    "delete_selected_cards": "Видалити вибрані картки?",
    "no_cards_in_library": "У бібліотеці не знайдено карток.",
    "card_label": "картка",
    "cards_label": "карток",
    "answer_label": "відповідь",
    "answers_label": "відповідей",
    "level": "Рівень",
    "pro_label": "PRO",
    "about_tagline": "Розумний компаньйон, що допомагає вашому мозку вчитися ефективніше.",
    "algorithm_title": "АЛГОРИТМ ALIOLO",
    "feat_spacing_title": "Когнітивні повторення (SM-2)",
    "feat_spacing_desc": "Повна імплементація моделі SuperMemo-2 передбачає згасання вашої пам'яті та призначає повторення на піку засвоєння.",
    "feat_adaptive_title": "Адаптивна швидкість реакції",
    "feat_adaptive_desc": "Система відстежує швидкість розпізнавання варіантів відповіді, динамічно налаштовуючи інтервали для вашого розвитку.",
    "feat_recognition_title": "Тренування візуальних образів",
    "feat_recognition_desc": "Інтенсивні вправи на ідентифікацію, розроблені для побудови миттєвої \"м'язової пам'яті\" у візуальних предметах.",
    "feat_mastery_title": "Візуальна майстерність та XP",
    "feat_mastery_desc": "Динамічні нагороди XP та значки майстерності (Бронза, Срібло, Золото) відстежують ваш шлях.",
    "licenses": "Ліцензії",
    "master_visual_ease": "Опановуйте візуальні предмети з легкістю.",
    "all_rights_reserved": "© 2026 Aliolo. Усі права захищено.",
    "hall_of_fame": "Зал слави",
    "streak": "Серія",
    "day": "день",
    "days": "дні",
    "you_rank": "Ваш ранг: #{rank}",
    "no_leaderboard_data": "Дані лідерів відсутні.",
    "profile": "Профіль",
    "profile_title": "Мій профіль та прогрес",
    "daily_goal": "Денна мета",
    "cards_per_day": "карток на день",
    "session_size": "Розмір сесії",
    "cards_per_session": "карток на сесію",
    "options_count": "Кількість відповідей",
    "options_per_card": "варіантів на картку",
    "total_xp": "Загальний XP",
    "current_streak": "Поточна серія",
    "change_avatar": "Змінити аватар",
    "delete_account": "Видалити акаунт",
    "delete_account_confirm": "Ви впевнені, що хочете видалити свій акаунт? Ця дія є незворотною.",
    "enter_pass_to_confirm": "Введіть пароль для підтвердження",
    "account_deleted": "Акаунт успішно видалено",
    "error_deleting_account": "Не вдалося видалити акаунт. Перевірте пароль.",
    "version": "Версія",
    "reset_password_for": "Скидання пароля для: ",
    "digit_code": "6-значний код",
    "user_not_found": "Користувача не знайдено",
    "invalid_code": "Невірний код",
    "password_reset_success": "Пароль успішно змінено",
    "to_label": "Кому",
    "email_subject": "Тема",
    "reset_code_email_title": "Код для скидання пароля",
    "code_label": "Код",
    "new_password": "Новий пароль",
    "confirm": "Підтвердити",
    "manage_subjects": "Керування предметами",
    "manage_cards": "Керування картками",
    "manage_learning_langs": "Керування мовами навчання",
    "add_subject": "Додати предмет",
    "enter_subject_name": "Введіть назву предмета",
    "delete_subject_confirm": "Видалити предмет '{subject}' та всі {count} карток всередині?"
}

# Key translations for Italian (it)
it = {
    "login": "Accedi",
    "username": "Nome utente",
    "password": "Password",
    "email": "Email",
    "confirm_password": "Conferma password",
    "create_account": "Crea account",
    "create_new_account": "Crea nuovo account",
    "back_to_login": "Torna al login",
    "forgot_password": "Password dimenticata?",
    "select_user": "Seleziona utente",
    "settings": "Impostazioni",
    "subjects": "Materie",
    "about": "Informazioni",
    "language": "Lingua",
    "english": "Inglese",
    "ukrainian": "Ucraino",
    "logout": "Esci",
    "session_complete": "Sessione completata!",
    "xp": "XP",
    "mastery": "Padronanza",
    "next": "Avanti",
    "back_to_subjects": "Torna alle materie",
    "select_an_answer": "Seleziona una risposta",
    "card_details": "Dettagli scheda",
    "edit_card": "Modifica scheda",
    "create_new_card": "Crea nuova scheda",
    "save": "Salva",
    "delete": "Elimina",
    "confirm_logout": "Sei sicuro di voler uscire?",
    "cancel": "Annulla",
    "ui_language": "Lingua interfaccia",
    "general_preferences": "Preferenze generali",
    "sidebar_left": "Barra laterale a sinistra",
    "sidebar_left_desc": "Sposta i controlli a sinistra.",
    "sound_effects": "Effetti sonori",
    "sound_effects_desc": "Abilita feedback audio.",
    "public_profile": "Profilo pubblico",
    "public_profile_desc": "Mostra XP e streak nella classifica.",
    "theme_mode": "Tema",
    "system": "Sistema",
    "light": "Chiaro",
    "dark": "Scuro",
    "keyboard_shortcuts": "Scorciatoie",
    "record_shortcut": "Registra scorciatoia",
    "setting_saved": "Impostazione salvata",
    "default_learning_language": "Lingua di apprendimento predefinita",
    "default_learning_language_desc": "Pre-seleziona questa lingua.",
    "mock_email_title": "Inbox simulata",
    "reset_code_sent": "Codice inviato per: ",
    "send_verification_code": "Inviare codice di verifica?",
    "verify": "Verifica",
    "update": "Aggiorna",
    "send_code": "Invia codice",
    "invalid_password": "Password non valida",
    "fill_all_fields": "Compila tutti i campi",
    "passwords_dont_match": "Le password non corrispondono",
    "user_exists": "Utente già esistente",
    "email_in_use": "Email già in uso",
    "account_created": "Account creato!",
    "invalid_email": "Email non valida",
    "no_cards_found": "Nessuna scheda trovata",
    "go_to_manager": "Vai alla gestione libreria",
    "mastered": "imparato",
    "cards": "schede",
    "finished_session": "Hai finito {count} schede. Bonus XP!",
    "select_lang": "Scegli lingua",
    "learning": "Apprendimento",
    "bronze": "BRONZO",
    "silver": "ARGENTO",
    "gold": "ORO",
    "new": "NUOVO",
    "subject": "Materia",
    "prompt_optional": "Domanda / Suggerimento",
    "video_url_optional": "URL video (Opzionale)",
    "card_level": "Livello scheda (1-20)",
    "multi_lang_answers": "Risposte multilingue",
    "multi_lang_prompts": "Suggerimenti multilingue",
    "lang_abbr": "Ling",
    "answer": "Risposta",
    "prompt_label": "Suggerimento",
    "prev": "Prec.",
    "unsaved_changes": "Modifiche non salvate",
    "save_before_nav": "Vuoi salvare prima di uscire?",
    "discard": "Scarta",
    "delete_card_confirm": "Elimina questa scheda?",
    "click_to_select_image": "Clicca per scegliere immagine",
    "video_link": "Link video",
    "required": "Obbligatorio",
    "enter_number": "Inserisci numero",
    "invalid_number": "Numero non valido",
    "level_range": "Deve essere tra 1 e 20",
    "provide_at_least_one_answer": "Inserisci almeno una risposta",
    "enter_or_select_subject": "Inserisci o scegli una materia",
    "manage_library": "Gestisci libreria ({sCount} materie, {cCount} schede)",
    "selected_count": "{count} selezionate",
    "delete_selected_cards": "Elimina schede selezionate?",
    "no_cards_in_library": "Nessuna scheda nella libreria.",
    "card_label": "scheda",
    "cards_label": "schede",
    "answer_label": "risposta",
    "answers_label": "risposte",
    "level": "Livello",
    "pro_label": "PRO",
    "about_tagline": "Il compagno intelligente per imparare meglio.",
    "algorithm_title": "L'ALGORITMO ALIOLO",
    "feat_spacing_title": "Ripetizione dilazionata (SM-2)",
    "feat_spacing_desc": "Implementazione del modello SuperMemo-2.",
    "feat_adaptive_title": "Risposta adattiva",
    "feat_adaptive_desc": "Monitora la velocità di riconoscimento.",
    "feat_recognition_title": "Pattern visivi",
    "feat_recognition_desc": "Esercizi per la memoria muscolare visiva.",
    "feat_mastery_title": "Padronanza & XP",
    "feat_mastery_desc": "Premi XP e medaglie.",
    "licenses": "Licenze",
    "master_visual_ease": "Impara con facilità.",
    "all_rights_reserved": "© 2026 Aliolo. Tutti i diritti riservati.",
    "hall_of_fame": "Classifica",
    "streak": "Serie",
    "day": "giorno",
    "days": "giorni",
    "you_rank": "Sei al posto #{rank}",
    "no_leaderboard_data": "Nessun dato disponibile.",
    "profile": "Profilo",
    "profile_title": "Il mio profilo",
    "daily_goal": "Obiettivo giornaliero",
    "cards_per_day": "schede al giorno",
    "session_size": "Dimensione sessione",
    "cards_per_session": "schede per sessione",
    "options_count": "Numero di risposte",
    "options_per_card": "opzioni per scheda",
    "total_xp": "XP totali",
    "current_streak": "Serie attuale",
    "change_avatar": "Cambia avatar",
    "delete_account": "Elimina account",
    "delete_account_confirm": "Sei sicuro? L'azione è permanente.",
    "enter_pass_to_confirm": "Inserisci password",
    "account_deleted": "Account eliminato",
    "error_deleting_account": "Errore eliminazione",
    "version": "Versione",
    "reset_password_for": "Reset per: ",
    "digit_code": "Codice 6 cifre",
    "user_not_found": "Utente non trovato",
    "invalid_code": "Codice non valido",
    "password_reset_success": "Reset riuscito",
    "to_label": "A",
    "email_subject": "Oggetto",
    "reset_code_email_title": "Codice reset",
    "code_label": "Codice",
    "new_password": "Nuova password",
    "confirm": "Conferma",
    "manage_subjects": "Gestisci materie",
    "manage_cards": "Gestisci schede",
    "manage_learning_langs": "Gestisci lingue",
    "add_subject": "Aggiungi materia",
    "enter_subject_name": "Nome materia",
    "delete_subject_confirm": "Elimina materia '{subject}' e le {count} schede?"
}

# Portuguese (pt)
pt = {
    "login": "Entrar",
    "username": "Nome de usuário",
    "password": "Senha",
    "email": "E-mail",
    "confirm_password": "Confirmar senha",
    "create_account": "Criar conta",
    "create_new_account": "Criar nova conta",
    "back_to_login": "Voltar ao login",
    "forgot_password": "Esqueceu a senha?",
    "select_user": "Selecionar usuário",
    "settings": "Configurações",
    "subjects": "Assuntos",
    "about": "Sobre",
    "language": "Idioma",
    "english": "Inglês",
    "ukrainian": "Ucraniano",
    "logout": "Sair",
    "session_complete": "Sessão concluída!",
    "xp": "XP",
    "mastery": "Domínio",
    "next": "Próximo",
    "back_to_subjects": "Voltar aos assuntos",
    "select_an_answer": "Selecione uma resposta",
    "card_details": "Detalhes do cartão",
    "edit_card": "Editar cartão",
    "create_new_card": "Criar novo cartão",
    "save": "Salvar",
    "delete": "Excluir",
    "confirm_logout": "Tem certeza que deseja sair?",
    "cancel": "Cancelar",
    "ui_language": "Idioma da interface",
    "general_preferences": "Preferências gerais",
    "sidebar_left": "Barra lateral à esquerda",
    "sidebar_left_desc": "Mover controles para a esquerda.",
    "sound_effects": "Efeitos sonoros",
    "sound_effects_desc": "Ativar áudio nas respostas.",
    "public_profile": "Perfil público",
    "public_profile_desc": "Mostrar XP e streak no ranking.",
    "theme_mode": "Modo de tema",
    "system": "Sistema",
    "light": "Claro",
    "dark": "Escuro",
    "keyboard_shortcuts": "Atalhos",
    "record_shortcut": "Gravar atalho",
    "setting_saved": "Configuração salva",
    "default_learning_language": "Idioma padrão",
    "default_learning_language_desc": "Pré-seleciona este idioma.",
    "mock_email_title": "Caixa de entrada simulada",
    "reset_code_sent": "Código enviado para: ",
    "send_verification_code": "Enviar código?",
    "verify": "Verificar",
    "update": "Atualizar",
    "send_code": "Enviar código",
    "invalid_password": "Senha inválida",
    "fill_all_fields": "Preencha todos os campos",
    "passwords_dont_match": "Senhas não coincidem",
    "user_exists": "Usuário já existe",
    "email_in_use": "E-mail em uso",
    "account_created": "Conta criada!",
    "invalid_email": "E-mail inválido",
    "no_cards_found": "Nenhum cartão encontrado",
    "go_to_manager": "Ir para gestão",
    "mastered": "aprendido",
    "cards": "cartões",
    "finished_session": "Terminou {count} cartões. Bônus XP!",
    "select_lang": "Escolher idioma",
    "learning": "Aprendizado",
    "bronze": "BRONZE",
    "silver": "PRATA",
    "gold": "OURO",
    "new": "NOVO",
    "subject": "Assunto",
    "prompt_optional": "Pergunta / Sugestão",
    "video_url_optional": "URL de vídeo",
    "card_level": "Nível (1-20)",
    "multi_lang_answers": "Respostas multilíngues",
    "multi_lang_prompts": "Sugestões multilíngues",
    "lang_abbr": "Ling",
    "answer": "Resposta",
    "prompt_label": "Sugestão",
    "prev": "Anterior",
    "unsaved_changes": "Alterações não salvas",
    "save_before_nav": "Salvar antes de sair?",
    "discard": "Descartar",
    "delete_card_confirm": "Excluir cartão?",
    "click_to_select_image": "Clique para escolher imagem",
    "video_link": "Link de vídeo",
    "required": "Obrigatório",
    "enter_number": "Insira número",
    "invalid_number": "Número inválido",
    "level_range": "Entre 1 e 20",
    "provide_at_least_one_answer": "Insira pelo menos uma resposta",
    "enter_or_select_subject": "Insira ou escolha assunto",
    "manage_library": "Gerenciar biblioteca ({sCount} assuntos, {cCount} cartões)",
    "selected_count": "{count} selecionados",
    "delete_selected_cards": "Excluir selecionados?",
    "no_cards_in_library": "Nenhum cartão.",
    "card_label": "cartão",
    "cards_label": "cartões",
    "answer_label": "resposta",
    "answers_label": "respostas",
    "level": "Nível",
    "pro_label": "PRO",
    "about_tagline": "O companheiro inteligente para aprender melhor.",
    "algorithm_title": "O ALGORITMO ALIOLO",
    "feat_spacing_title": "Espaçamento cognitivo (SM-2)",
    "feat_spacing_desc": "Implementação completa do SM-2.",
    "feat_adaptive_title": "Resposta adaptativa",
    "feat_adaptive_desc": "Monitora a velocità di riconoscimento.",
    "feat_recognition_title": "Padrões visuais",
    "feat_recognition_desc": "Exercícios de memória muscular.",
    "feat_mastery_title": "Domínio & XP",
    "feat_mastery_desc": "Prêmios XP e medalhas.",
    "licenses": "Licenças",
    "master_visual_ease": "Aprenda com facilidade.",
    "all_rights_reserved": "© 2026 Aliolo. Todos os direitos reservados.",
    "hall_of_fame": "Salão da Fama",
    "streak": "Sequência",
    "day": "dia",
    "days": "dias",
    "you_rank": "Posição #{rank}",
    "no_leaderboard_data": "Sem dados.",
    "profile": "Perfil",
    "profile_title": "Meu Perfil",
    "daily_goal": "Meta diária",
    "cards_per_day": "cartões/dia",
    "session_size": "Tamanho da sessão",
    "cards_per_session": "cartões/sessão",
    "options_count": "Número de respostas",
    "options_per_card": "opções/cartão",
    "total_xp": "XP Total",
    "current_streak": "Sequência atual",
    "change_avatar": "Alterar avatar",
    "delete_account": "Excluir conta",
    "delete_account_confirm": "Tem certeza? Ação permanente.",
    "enter_pass_to_confirm": "Digite a senha",
    "account_deleted": "Conta excluída",
    "error_deleting_account": "Erro ao excluir",
    "version": "Versione",
    "reset_password_for": "Reset para: ",
    "digit_code": "Código 6 dígitos",
    "user_not_found": "Usuário não encontrado",
    "invalid_code": "Código inválido",
    "password_reset_success": "Sucesso no reset",
    "to_label": "Para",
    "email_subject": "Assunto",
    "reset_code_email_title": "Código reset",
    "code_label": "Código",
    "new_password": "Nova senha",
    "confirm": "Confirmar",
    "manage_subjects": "Gerenciar assuntos",
    "manage_cards": "Gerenciar cartões",
    "manage_learning_langs": "Gerenciar línguas",
    "add_subject": "Adicionar assunto",
    "enter_subject_name": "Nome do assunto",
    "delete_subject_confirm": "Excluir assunto '{subject}' e {count} cartões?"
}

# Key translations for Chinese (zh)
zh = {
    "login": "登录",
    "username": "用户名",
    "password": "密码",
    "email": "电子邮件",
    "confirm_password": "确认密码",
    "create_account": "创建账户",
    "create_new_account": "创建新账户",
    "back_to_login": "返回登录",
    "forgot_password": "忘记密码？",
    "select_user": "选择用户",
    "settings": "设置",
    "subjects": "主题",
    "about": "关于",
    "language": "语言",
    "english": "英语",
    "ukrainian": "乌克兰语",
    "logout": "登出",
    "session_complete": "学习完成！",
    "xp": "经验值",
    "mastery": "掌握度",
    "next": "下一步",
    "back_to_subjects": "返回主题",
    "select_an_answer": "选择答案",
    "card_details": "卡片详情",
    "edit_card": "编辑卡片",
    "create_new_card": "创建新卡片",
    "save": "保存",
    "delete": "删除",
    "confirm_logout": "确定要登出吗？",
    "cancel": "取消",
    "ui_language": "界面语言",
    "general_preferences": "常规设置",
    "sidebar_left": "侧边栏居左",
    "sidebar_left_desc": "将控制栏移至屏幕左侧。",
    "sound_effects": "音效",
    "sound_effects_desc": "开启回答音效反馈。",
    "public_profile": "公开资料",
    "public_profile_desc": "在名人堂显示经验和连续天数。",
    "theme_mode": "主题模式",
    "system": "跟随系统",
    "light": "浅色",
    "dark": "深色",
    "keyboard_shortcuts": "键盘快捷键",
    "record_shortcut": "录制快捷键",
    "setting_saved": "设置已保存",
    "default_learning_language": "默认学习语言",
    "default_learning_language_desc": "在主题页预选此语言。",
    "mock_email_title": "模拟邮箱",
    "reset_code_sent": "重置码已发送至：",
    "send_verification_code": "发送验证码？",
    "verify": "验证",
    "update": "更新",
    "send_code": "发送代码",
    "invalid_password": "密码错误",
    "fill_all_fields": "请填写所有字段",
    "passwords_dont_match": "密码不匹配",
    "user_exists": "用户已存在",
    "email_in_use": "电子邮件已被占用",
    "account_created": "账户创建成功！",
    "invalid_email": "无效的电子邮件地址",
    "no_cards_found": "未找到该语言的卡片",
    "go_to_manager": "前往库管理器",
    "mastered": "已掌握",
    "cards": "卡片",
    "finished_session": "你完成了 {count} 张卡片。获得经验加成！",
    "select_lang": "选择语言",
    "learning": "学习中",
    "bronze": "青铜",
    "silver": "白银",
    "gold": "黄金",
    "new": "新内容",
    "subject": "主题",
    "prompt_optional": "提示 / 问题",
    "video_url_optional": "视频链接（可选）",
    "card_level": "卡片等级 (1-20)",
    "multi_lang_answers": "多语言答案",
    "multi_lang_prompts": "多语言提示",
    "lang_abbr": "语言",
    "answer": "答案",
    "prompt_label": "提示",
    "prev": "上一个",
    "unsaved_changes": "未保存的更改",
    "save_before_nav": "离开前是否保存？",
    "discard": "放弃",
    "delete_card_confirm": "删除这张卡片？",
    "click_to_select_image": "点击选择图片",
    "video_link": "视频链接",
    "required": "必填",
    "enter_number": "输入数字",
    "invalid_number": "数字无效",
    "level_range": "必须在 1 到 20 之间",
    "provide_at_least_one_answer": "请至少提供一个答案",
    "enter_or_select_subject": "请进入或选择一个主题",
    "manage_library": "管理库（{sCount} 个主题，{cCount} 张卡片）",
    "selected_count": "已选 {count} 项",
    "delete_selected_cards": "删除选中的卡片？",
    "no_cards_in_library": "库中未找到卡片。",
    "card_label": "卡片",
    "cards_label": "卡片",
    "answer_label": "答案",
    "answers_label": "答案",
    "level": "等级",
    "pro_label": "专业版",
    "about_tagline": "聪明伴侣，助你高效学习。",
    "algorithm_title": "ALIOLO 算法",
    "feat_spacing_title": "认知间隔 (SM-2)",
    "feat_spacing_desc": "完整实现的间隔重复模型。",
    "feat_adaptive_title": "自适应反应时间",
    "feat_adaptive_desc": "通过识别速度动态调整间隔。",
    "feat_recognition_title": "视觉模式训练",
    "feat_recognition_desc": "建立视觉瞬间记忆。",
    "feat_mastery_title": "视觉精通与经验值",
    "feat_mastery_desc": "动态经验奖励与掌握勋章。",
    "licenses": "许可协议",
    "master_visual_ease": "轻松掌握视觉主题。",
    "all_rights_reserved": "© 2026 Aliolo. 保留所有权利。",
    "hall_of_fame": "名人堂",
    "streak": "连续天数",
    "day": "天",
    "days": "天",
    "you_rank": "你的排名：第 #{rank} 名",
    "no_leaderboard_data": "暂无排行榜数据。",
    "profile": "个人资料",
    "profile_title": "我的资料与进度",
    "daily_goal": "每日目标",
    "cards_per_day": "张卡片/天",
    "session_size": "单次学习量",
    "cards_per_session": "张卡片/次",
    "options_count": "选项数量",
    "options_per_card": "个选项/卡片",
    "total_xp": "总经验值",
    "current_streak": "当前连续天数",
    "change_avatar": "更换头像",
    "delete_account": "注销账户",
    "delete_account_confirm": "确定要注销吗？此操作不可逆。",
    "enter_pass_to_confirm": "输入密码确认",
    "account_deleted": "账户已成功注销",
    "error_deleting_account": "无法注销，请检查密码。",
    "version": "版本",
    "reset_password_for": "重置密码：",
    "digit_code": "6 位验证码",
    "user_not_found": "找不到用户",
    "invalid_code": "验证码无效",
    "password_reset_success": "密码重置成功",
    "to_label": "至",
    "email_subject": "主题",
    "reset_code_email_title": "重置验证码",
    "code_label": "代码",
    "new_password": "新密码",
    "confirm": "确认",
    "manage_subjects": "管理主题",
    "manage_cards": "管理卡片",
    "manage_learning_langs": "管理学习语言",
    "add_subject": "添加主题",
    "enter_subject_name": "输入主题名称",
    "delete_subject_confirm": "删除主题 “{subject}” 及其包含的 {count} 张卡片？"
}

# Polish (pl)
pl = {
    "login": "Zaloguj się",
    "username": "Nazwa użytkownika",
    "password": "Hasło",
    "email": "E-mail",
    "confirm_password": "Potwierdź hasło",
    "create_account": "Utwórz konto",
    "create_new_account": "Utwórz nowe konto",
    "back_to_login": "Powrót do logowania",
    "forgot_password": "Zapomniałeś hasła?",
    "select_user": "Wybierz użytkownika",
    "settings": "Ustawienia",
    "subjects": "Tematy",
    "about": "O aplikacji",
    "language": "Język",
    "english": "Angielski",
    "ukrainian": "Ukraiński",
    "logout": "Wyloguj się",
    "session_complete": "Sesja zakończona!",
    "xp": "XP",
    "mastery": "Opanowanie",
    "next": "Dalej",
    "back_to_subjects": "Powrót do tematów",
    "select_an_answer": "Wybierz odpowiedź",
    "card_details": "Szczegóły karty",
    "edit_card": "Edytuj kartę",
    "create_new_card": "Utwórz nową kartę",
    "save": "Zapisz",
    "delete": "Usuń",
    "confirm_logout": "Czy na pewno chcesz się wylogować?",
    "cancel": "Anuluj",
    "ui_language": "Język interfejsu",
    "general_preferences": "Ustawienia ogólne",
    "sidebar_left": "Pasek boczny po lewej",
    "sidebar_left_desc": "Przenieś panel sterowania na lewą stronę ekranu.",
    "sound_effects": "Efekty dźwiękowe",
    "sound_effects_desc": "Włącz dźwięki przy odpowiedziach.",
    "public_profile": "Profil publiczny",
    "public_profile_desc": "Pokaż XP i serię w Sali Sław.",
    "theme_mode": "Tryb motywu",
    "system": "Systemowy",
    "light": "Jasny",
    "dark": "Ciemny",
    "keyboard_shortcuts": "Skróty klawiszowe",
    "record_shortcut": "Nagraj skrót",
    "setting_saved": "Ustawienie zapisane",
    "default_learning_language": "Domyślny język nauki",
    "default_learning_language_desc": "Wstępnie wybiera ten język na stronie tematów.",
    "mock_email_title": "Makieta skrzynki odbiorczej",
    "reset_code_sent": "Kod resetowania dla: ",
    "send_verification_code": "Wysłać kod weryfikacyjny?",
    "verify": "Weryfikuj",
    "update": "Aktualizuj",
    "send_code": "Wyślij kod",
    "invalid_password": "Błędne hasło",
    "fill_all_fields": "Proszę wypełnić wszystkie pola",
    "passwords_dont_match": "Hasła nie pasują do siebie",
    "user_exists": "Użytkownik już istnieje",
    "email_in_use": "Email jest już w użyciu",
    "account_created": "Konto utworzone!",
    "invalid_email": "Nieprawidłowy adres email",
    "no_cards_found": "Nie znaleziono kart dla języka",
    "go_to_manager": "Przejdź do menedżera biblioteki",
    "mastered": "opanowane",
    "cards": "kart",
    "finished_session": "Ukończyłeś {count} kart. Bonus XP przyznany!",
    "select_lang": "Wybierz język",
    "learning": "Nauka",
    "bronze": "BRĄZ",
    "silver": "SREBRO",
    "gold": "ZŁOTO",
    "new": "NOWE",
    "subject": "Temat",
    "prompt_optional": "Podpowiedź / Pytanie",
    "video_url_optional": "URL wideo (opcjonalnie)",
    "card_level": "Poziom karty (1-20)",
    "multi_lang_answers": "Odpowiedzi wielojęzyczne",
    "multi_lang_prompts": "Podpowiedzi wielojęzyczne",
    "lang_abbr": "Jęz.",
    "answer": "Odpowiedź",
    "prompt_label": "Podpowiedź",
    "prev": "Poprz.",
    "unsaved_changes": "Niezapisane zmiany",
    "save_before_nav": "Czy chcesz zapisać zmiany przed wyjściem?",
    "discard": "Odrzuć",
    "delete_card_confirm": "Usunąć tę kartę?",
    "click_to_select_image": "Kliknij, aby wybrać obraz",
    "video_link": "Link do wideo",
    "required": "Wymagane",
    "enter_number": "Wprowadź liczbę",
    "invalid_number": "Nieprawidłowa liczba",
    "level_range": "Musi być między 1 a 20",
    "provide_at_least_one_answer": "Proszę podać co najmniej jedną odpowiedź",
    "enter_or_select_subject": "Proszę wpisać lub wybrać temat",
    "manage_library": "Zarządzaj biblioteką ({sCount} tematów, {cCount} kart)",
    "selected_count": "Wybrano {count}",
    "delete_selected_cards": "Usunąć wybrane karty?",
    "no_cards_in_library": "W bibliotece nie znaleziono kart.",
    "card_label": "karta",
    "cards_label": "kart",
    "answer_label": "odpowiedź",
    "answers_label": "odpowiedzi",
    "level": "Poziom",
    "pro_label": "PRO",
    "about_tagline": "Inteligentny towarzysz, który pomaga Twojemu mózgowi uczyć się efektywniej.",
    "algorithm_title": "ALGORYTM ALIOLO",
    "feat_spacing_title": "Odstępy poznawcze (SM-2)",
    "feat_spacing_desc": "Pełna implementacja modelu SuperMemo-2.",
    "feat_adaptive_title": "Adaptacyjny czas reakcji",
    "feat_adaptive_desc": "System monitoruje szybkość rozpoznawania.",
    "feat_recognition_title": "Trening wzorców wizualnych",
    "feat_recognition_desc": "Budowanie wizualnej pamięci mięśniowej.",
    "feat_mastery_title": "Wizualna biegłość i XP",
    "feat_mastery_desc": "Dynamiczne nagrody XP i odznaki.",
    "licenses": "Licencje",
    "master_visual_ease": "Opanuj tematy wizualne z łatwością.",
    "all_rights_reserved": "© 2026 Aliolo. Wszelkie prawa zastrzeżone.",
    "hall_of_fame": "Sala Sław",
    "streak": "Seria",
    "day": "dzień",
    "days": "dni",
    "you_rank": "Ranking: #{rank}",
    "no_leaderboard_data": "Brak danych rankingu.",
    "profile": "Profil",
    "profile_title": "Mój Profil i Postępy",
    "daily_goal": "Cel dzienny",
    "cards_per_day": "kart na dzień",
    "session_size": "Wielkość sesji",
    "cards_per_session": "kart na sesję",
    "options_count": "Liczba odpowiedzi",
    "options_per_card": "opcji na kartę",
    "total_xp": "Suma XP",
    "current_streak": "Aktualna seria",
    "change_avatar": "Zmień awatar",
    "delete_account": "Usuń konto",
    "delete_account_confirm": "Czy na pewno chcesz usunąć konto? To działanie jest nieodwracalne.",
    "enter_pass_to_confirm": "Wpisz hasło, aby potwierdzić",
    "account_deleted": "Konto zostało usunięte",
    "error_deleting_account": "Błąd usuwania konta. Sprawdź hasło.",
    "version": "Wersja",
    "reset_password_for": "Reset hasła dla: ",
    "digit_code": "Kod 6-cyfrowy",
    "user_not_found": "Użytkownik nie znaleziony",
    "invalid_code": "Nieprawidłowy kod",
    "password_reset_success": "Hasło zostało zresetowane",
    "to_label": "Do",
    "email_subject": "Temat",
    "reset_code_email_title": "Kod resetowania hasła",
    "code_label": "Kod",
    "new_password": "Nowe hasło",
    "confirm": "Potwierdź",
    "manage_subjects": "Zarządzaj tematami",
    "manage_cards": "Zarządzaj kartami",
    "manage_learning_langs": "Zarządzaj językami nauki",
    "add_subject": "Dodaj temat",
    "enter_subject_name": "Wpisz nazwę tematu",
    "delete_subject_confirm": "Usunąć temat '{subject}' i wszystkie {count} kart wewnątrz?"
}

# Key translations for Japanese (ja)
ja = {
    "login": "ログイン",
    "username": "ユーザー名",
    "password": "パスワード",
    "email": "メールアドレス",
    "confirm_password": "パスワードの確認",
    "create_account": "アカウント作成",
    "create_new_account": "新規アカウント作成",
    "back_to_login": "ログインに戻る",
    "forgot_password": "パスワードを忘れた場合",
    "select_user": "ユーザー選択",
    "settings": "設定",
    "subjects": "科目",
    "about": "アプリについて",
    "language": "言語",
    "english": "英語",
    "ukrainian": "ウクライナ語",
    "logout": "ログアウト",
    "session_complete": "セッション完了！",
    "xp": "XP",
    "mastery": "習熟度",
    "next": "次へ",
    "back_to_subjects": "科目一覧に戻る",
    "select_an_answer": "回答を選択",
    "card_details": "カード詳細",
    "edit_card": "カード編集",
    "create_new_card": "新規カード作成",
    "save": "保存",
    "delete": "削除",
    "confirm_logout": "ログアウトしてもよろしいですか？",
    "cancel": "キャンセル",
    "ui_language": "UI言語",
    "general_preferences": "一般設定",
    "sidebar_left": "サイドバーを左に表示",
    "sidebar_left_desc": "操作パネルを画面の左側に移動します。",
    "sound_effects": "効果音",
    "sound_effects_desc": "正解・不正解時の音声を有効にします。",
    "public_profile": "公開プロフィール",
    "public_profile_desc": "殿堂入り画面にXPと継続日数を表示します。",
    "theme_mode": "テーマモード",
    "system": "システム設定に従う",
    "light": "ライト",
    "dark": "ダーク",
    "keyboard_shortcuts": "キーボードショートカット",
    "record_shortcut": "ショートカットを記録",
    "setting_saved": "設定を保存しました",
    "default_learning_language": "デフォルトの学習言語",
    "default_learning_language_desc": "科目ページでこの言語をあらかじめ選択します。",
    "left_arrow": "左矢印",
    "right_arrow": "右矢印",
    "up_arrow": "上矢印",
    "down_arrow": "下矢印",
    "mock_email_title": "テスト用受信トレイ",
    "reset_code_sent": "リセットコード送信先: ",
    "send_verification_code": "認証コードを送信しますか？",
    "verify": "認証",
    "update": "更新",
    "send_code": "コードを送信",
    "invalid_password": "パスワードが無効です",
    "fill_all_fields": "すべての項目を入力してください",
    "passwords_dont_match": "パスワードが一致しません",
    "user_exists": "ユーザーが既に存在します",
    "email_in_use": "このメールアドレスは既に使用されています",
    "account_created": "アカウントを作成しました！",
    "invalid_email": "メールアドレスが無効です",
    "no_cards_found": "該当言語のカードが見つかりません",
    "go_to_manager": "ライブラリ管理へ",
    "mastered": "習得済み",
    "cards": "枚のカード",
    "finished_session": "{count} 枚のカードを完了しました。XPボーナス獲得！",
    "select_lang": "言語を選択",
    "learning": "学習中",
    "bronze": "ブロンズ",
    "silver": "シルバー",
    "gold": "ゴールド",
    "new": "新規",
    "subject": "科目",
    "prompt_optional": "問い / 質問",
    "video_url_optional": "ビデオURL（任意）",
    "card_level": "カードレベル (1-20)",
    "multi_lang_answers": "多言語回答",
    "multi_lang_prompts": "多言語問い",
    "lang_abbr": "言語",
    "answer": "回答",
    "prompt_label": "問い",
    "prev": "前へ",
    "unsaved_changes": "未保存の変更",
    "save_before_nav": "移動する前に変更を保存しますか？",
    "discard": "破棄",
    "delete_card_confirm": "このカードを削除しますか？",
    "click_to_select_image": "クリックして画像を選択",
    "video_link": "ビデオリンク",
    "required": "必須",
    "enter_number": "数値を入力",
    "invalid_number": "無効な数値",
    "level_range": "1から20の間で指定してください",
    "provide_at_least_one_answer": "少なくとも1つの回答を入力してください",
    "enter_or_select_subject": "科目名を入力または選択してください",
    "manage_library": "ライブラリ管理 ({sCount} 科目, {cCount} 枚)",
    "selected_count": "{count} 個選択中",
    "delete_selected_cards": "選択したカードを削除しますか？",
    "no_cards_in_library": "ライブラリにカードがありません。",
    "card_label": "カード",
    "cards_label": "カード",
    "answer_label": "回答",
    "answers_label": "回答",
    "level": "レベル",
    "pro_label": "PRO",
    "about_tagline": "あなたの脳がより効果的に学習するのを助けるスマートな相棒。",
    "algorithm_title": "ALIOLO アルゴリズム",
    "feat_spacing_title": "認知的間隔 (SM-2)",
    "feat_spacing_desc": "忘却曲線を予測し、復習をスケジュールします。",
    "feat_adaptive_title": "適応型レスポンスタイム",
    "feat_adaptive_desc": "認識速度を監視して、復習間隔を調整します。",
    "feat_recognition_title": "視覚パターン訓練",
    "feat_recognition_desc": "視覚的な「マッスルメモリー」を構築します。",
    "feat_mastery_title": "視覚的習熟とXP",
    "feat_mastery_desc": "XP報酬と習熟バッジ（ブロンズ、シルバー、ゴールド）。",
    "licenses": "ライセンス",
    "master_visual_ease": "視覚的な科目を簡単に習得。",
    "all_rights_reserved": "© 2026 Aliolo. All rights reserved.",
    "hall_of_fame": "殿堂入り",
    "streak": "継続日数",
    "day": "日",
    "days": "日",
    "you_rank": "あなたの順位：#{rank}位",
    "no_leaderboard_data": "ランキングデータがありません。",
    "profile": "プロフィール",
    "profile_title": "マイプロフィールと進捗",
    "daily_goal": "今日の目標",
    "cards_per_day": "枚/日",
    "session_size": "セッションサイズ",
    "cards_per_session": "枚/セッション",
    "options_count": "回答の選択肢数",
    "options_per_card": "個/カード",
    "total_xp": "累計XP",
    "current_streak": "現在の継続日数",
    "change_avatar": "アバターを変更",
    "delete_account": "アカウントを削除",
    "delete_account_confirm": "アカウントを削除してもよろしいですか？この操作は取り消せません。",
    "enter_pass_to_confirm": "確認のためパスワードを入力してください",
    "account_deleted": "アカウントを削除しました",
    "error_deleting_account": "削除できませんでした。パスワードを確認してください。",
    "version": "バージョン",
    "reset_password_for": "パスワードリセット: ",
    "digit_code": "6桁のコード",
    "user_not_found": "ユーザーが見つかりません",
    "invalid_code": "コードが無効です",
    "password_reset_success": "パスワードをリセットしました",
    "to_label": "宛先",
    "email_subject": "件名",
    "reset_code_email_title": "パスワードリセットコード",
    "code_label": "コード",
    "new_password": "新しいパスワード",
    "confirm": "確認",
    "manage_subjects": "科目を管理",
    "manage_cards": "カードを管理",
    "manage_learning_langs": "学習言語を管理",
    "add_subject": "科目を追加",
    "enter_subject_name": "科目名を入力",
    "delete_subject_confirm": "科目 '{subject}' と、その中の {count} 枚のカードをすべて削除しますか？"
}

# Key translations for Korean (ko)
ko = {
    "login": "로그인",
    "username": "사용자 이름",
    "password": "비밀번호",
    "email": "이메일",
    "confirm_password": "비밀번호 확인",
    "create_account": "계정 생성",
    "create_new_account": "새 계정 생성",
    "back_to_login": "로그인으로 돌아가기",
    "forgot_password": "비밀번호를 잊으셨나요?",
    "select_user": "사용자 선택",
    "settings": "설정",
    "subjects": "주제",
    "about": "정보",
    "language": "언어",
    "english": "영어",
    "ukrainian": "우크라이나어",
    "logout": "로그아웃",
    "session_complete": "학습 완료!",
    "xp": "XP",
    "mastery": "숙련도",
    "next": "다음",
    "back_to_subjects": "주제 목록으로",
    "select_an_answer": "답변 선택",
    "card_details": "카드 상세 정보",
    "edit_card": "카드 편집",
    "create_new_card": "새 카드 생성",
    "save": "저장",
    "delete": "삭제",
    "confirm_logout": "로그아웃하시겠습니까?",
    "cancel": "취소",
    "ui_language": "UI 언어",
    "general_preferences": "일반 설정",
    "sidebar_left": "사이드바 왼쪽",
    "sidebar_left_desc": "컨트롤을 화면 왼쪽에 표시합니다.",
    "sound_effects": "음향 효과",
    "sound_effects_desc": "정답/오답 소리를 활성화합니다.",
    "public_profile": "공개 프로필",
    "public_profile_desc": "명예의 전당에 XP와 기록을 표시합니다.",
    "theme_mode": "테마 모드",
    "system": "시스템 설정",
    "light": "라이트",
    "dark": "다크",
    "keyboard_shortcuts": "단축키",
    "record_shortcut": "단축키 기록",
    "setting_saved": "설정 저장됨",
    "default_learning_language": "기본 학습 언어",
    "default_learning_language_desc": "주제 페이지에서 이 언어를 우선 선택합니다.",
    "left_arrow": "왼쪽 화살표",
    "right_arrow": "오른쪽 화살표",
    "up_arrow": "위쪽 화살표",
    "down_arrow": "아래쪽 화살표",
    "mock_email_title": "테스트용 편지함",
    "reset_code_sent": "재설정 코드 전송: ",
    "send_verification_code": "인증 코드를 보내시겠습니까?",
    "verify": "인증",
    "update": "업데이트",
    "send_code": "코드 전송",
    "invalid_password": "잘못된 비밀번호",
    "fill_all_fields": "모든 필드를 입력해주세요",
    "passwords_dont_match": "비밀번호가 일치하지 않습니다",
    "user_exists": "이미 존재하는 사용자입니다",
    "email_in_use": "이미 사용 중인 이메일입니다",
    "account_created": "계정이 생성되었습니다!",
    "invalid_email": "유효하지 않은 이메일 주소",
    "no_cards_found": "해당 언어의 카드를 찾을 수 없습니다",
    "go_to_manager": "라이브러리 관리로 이동",
    "mastered": "학습 완료",
    "cards": "장의 카드",
    "finished_session": "{count}장의 카드를 완료했습니다. XP 보너스!",
    "select_lang": "언어 선택",
    "learning": "학습 중",
    "bronze": "브론즈",
    "silver": "실버",
    "gold": "골드",
    "new": "신규",
    "subject": "주제",
    "prompt_optional": "질문 / 힌트",
    "video_url_optional": "비디오 URL (선택)",
    "card_level": "카드 레벨 (1-20)",
    "multi_lang_answers": "다국어 답변",
    "multi_lang_prompts": "다국어 질문",
    "lang_abbr": "언어",
    "answer": "답변",
    "prompt_label": "질문",
    "prev": "이전",
    "unsaved_changes": "저장되지 않은 변경사항",
    "save_before_nav": "이동하기 전에 저장하시겠습니까?",
    "discard": "삭제",
    "delete_card_confirm": "이 카드를 삭제하시겠습니까?",
    "click_to_select_image": "클릭하여 이미지 선택",
    "video_link": "비디오 링크",
    "required": "필수",
    "enter_number": "숫자 입력",
    "invalid_number": "유효하지 않은 숫자",
    "level_range": "1에서 20 사이여야 합니다",
    "provide_at_least_one_answer": "최소 하나 이상의 답변을 입력해주세요",
    "enter_or_select_subject": "주제를 입력하거나 선택해주세요",
    "manage_library": "라이브러리 관리 ({sCount}개 주제, {cCount}장 카드)",
    "selected_count": "{count}개 선택됨",
    "delete_selected_cards": "선택한 카드를 삭제하시겠습니까?",
    "no_cards_in_library": "라이브러리에 카드가 없습니다.",
    "card_label": "카드",
    "cards_label": "카드",
    "answer_label": "답변",
    "answers_label": "답변",
    "level": "레벨",
    "pro_label": "PRO",
    "about_tagline": "뇌의 효율적인 학습을 돕는 스마트한 동반자.",
    "algorithm_title": "ALIOLO 알고리즘",
    "feat_spacing_title": "인지적 간격 (SM-2)",
    "feat_spacing_desc": "망각 곡선을 예측하고 복습 일정을 예약합니다.",
    "feat_adaptive_title": "적응형 반응 시간",
    "feat_adaptive_desc": "인식 속도를 모니터링하여 간격을 조정합니다.",
    "feat_recognition_title": "시각적 패턴 훈련",
    "feat_recognition_desc": "시각적 근육 기억을 형성합니다.",
    "feat_mastery_title": "시각적 숙달 및 XP",
    "feat_mastery_desc": "XP 보상과 숙달 배지 (브론즈, 실버, 골드).",
    "licenses": "라이선스",
    "master_visual_ease": "시각적 주제를 쉽게 정복하세요.",
    "all_rights_reserved": "© 2026 Aliolo. All rights reserved.",
    "hall_of_fame": "명예의 전당",
    "streak": "연속 학습",
    "day": "일",
    "days": "일",
    "you_rank": "현재 순위: #{rank}위",
    "no_leaderboard_data": "순위 데이터가 없습니다.",
    "profile": "프로필",
    "profile_title": "내 프로필 및 진도",
    "daily_goal": "일일 목표",
    "cards_per_day": "장/일",
    "session_size": "학습량",
    "cards_per_session": "장/세션",
    "options_count": "답변 선택지 수",
    "options_per_card": "개/카드",
    "total_xp": "총 XP",
    "current_streak": "현재 연속 학습일",
    "change_avatar": "아바타 변경",
    "delete_account": "계정 삭제",
    "delete_account_confirm": "계정을 삭제하시겠습니까? 이 작업은 되돌릴 수 없습니다.",
    "enter_pass_to_confirm": "확인을 위해 비밀번호를 입력하세요",
    "account_deleted": "계정이 삭제되었습니다",
    "error_deleting_account": "삭제 실패. 비밀번호를 확인하세요.",
    "version": "버전",
    "reset_password_for": "비밀번호 재설정: ",
    "digit_code": "6자리 코드",
    "user_not_found": "사용자를 찾을 수 없음",
    "invalid_code": "잘못된 코드",
    "password_reset_success": "비밀번호가 재설정되었습니다",
    "to_label": "받는 사람",
    "email_subject": "제목",
    "reset_code_email_title": "비밀번호 재설정 코드",
    "code_label": "코드",
    "new_password": "새 비밀번호",
    "confirm": "확인",
    "manage_subjects": "주제 관리",
    "manage_cards": "카드 관리",
    "manage_learning_langs": "학습 언어 관리",
    "add_subject": "주제 추가",
    "enter_subject_name": "주제 이름 입력",
    "delete_subject_confirm": "주제 '{subject}'와(과) 내부의 카드 {count}장을 모두 삭제하시겠습니까?"
}

# Helper to merge with English for missing keys
def write_lang(code, data):
    merged = base_en.copy()
    merged.update(data)
    with open(os.path.join(lang_dir, f"{code}.json"), "w", encoding="utf-8") as f:
        json.dump(merged, f, ensure_ascii=False, indent=2)

write_lang("es", es)
write_lang("fr", fr)
write_lang("de", de)
write_lang("it", it)
write_lang("pt", pt)
write_lang("pl", pl)
write_lang("zh", zh)
write_lang("ja", ja)
write_lang("ko", ko)
write_lang("uk", uk)

print("Comprehensive UI translation files generated successfully.")
