# -*- coding: utf-8 -*-
import os

# English reference keys and values
refs = {
    'onboarding_1_title': 'Welcome to Aliolo',
    'onboarding_1_desc': 'Learn Visually. Master Permanently. Your visual learning companion powered by SM-2 science.',
    'onboarding_2_title': 'How old are you?',
    'onboarding_2_desc': 'This helps us personalize your learning experience and recommend the right subjects.',
    'onboarding_3_title': 'What do you want to master?',
    'onboarding_3_desc': 'Select your primary interest to customize your initial dashboard.',
    'onboarding_4_title': 'Create & Share',
    'onboarding_4_desc': 'Build your own deck or dive into cards shared by Aliolo learners worldwide. Learn at your pace, then test yourself when you\'re ready.',
    'onboarding_5_title': 'Master Anywhere',
    'onboarding_5_desc': 'Your library stays in sync across all your devices. We’ll only nudge you when it’s time to protect your streak.',
    'onboarding_6_title': 'Join the Community',
    'onboarding_6_desc': 'Start your journey today and master anything you set your mind to.',
    'onboarding_7_quote': 'Aliolo has completely transformed the way my children and I master new topics. The visual cards and spaced repetition make learning feel like a game!',
    'onboarding_7_joined': 'Joined by thousands of learners',
    'onboarding_next': 'Next',
    'onboarding_skip': 'Skip',
    'compare_plans': 'Compare Free vs Premium',
    'hide_comparison': 'Hide Plan Comparison',
    'age_under_14': 'Under 14',
    'age_15_18': '15 - 18',
    'age_19_25': '19 - 25',
    'age_26_35': '26 - 35',
    'age_36_50': '36 - 50',
    'age_over_50': 'Over 50'
}

# Supported languages (34 total)
langs = ['en', 'id', 'bg', 'cs', 'da', 'de', 'et', 'es', 'fr', 'ga', 'hr', 'it', 'lv', 'lt', 'hu', 'mt', 'nl', 'pl', 'pt', 'ro', 'sk', 'sl', 'fi', 'sv', 'tl', 'vi', 'tr', 'el', 'uk', 'ar', 'hi', 'zh', 'ja', 'ko']

# Comprehensive translations dictionary
translations_all = {
    'en': refs,
    'id': {
        'onboarding_1_title': 'Selamat Datang di Aliolo',
        'onboarding_1_desc': 'Belajar Secara Visual. Kuasai Secara Permanen. Pendamping belajar visual Anda yang didukung oleh sains SM-2.',
        'onboarding_2_title': 'Berapa usia Anda?',
        'onboarding_2_desc': 'Ini membantu kami mempersonalisasi pengalaman belajar Anda dan merekomendasikan mata pelajaran yang tepat.',
        'onboarding_3_title': 'Apa yang ingin Anda kuasai?',
        'onboarding_3_desc': 'Pilih minat utama Anda untuk menyesuaikan dasbor awal Anda.',
        'onboarding_4_title': 'Buat & Bagikan',
        'onboarding_4_desc': 'Bangun dek Anda sendiri atau selami kartu yang dibagikan oleh pelajar Aliolo di seluruh dunia. Belajar sesuai kecepatan Anda, lalu uji diri Anda saat siap.',
        'onboarding_5_title': 'Kuasai di Mana Saja',
        'onboarding_5_desc': 'Perpustakaan Anda tetap sinkron di semua perangkat Anda. Kami hanya akan mengingatkan Anda saat waktunya melindungi streak Anda.',
        'onboarding_6_title': 'Bergabunglah dengan Komunitas',
        'onboarding_6_desc': 'Mulailah perjalanan Anda hari ini dan kuasai apa pun yang Anda inginkan.',
        'onboarding_7_quote': 'Aliolo telah sepenuhnya mengubah cara anak-anak saya dan saya menguasai topik baru. Kartu visual dan pengulangan berjarak membuat belajar terasa seperti permainan!',
        'onboarding_7_joined': 'Bergabung dengan ribuan pelajar',
        'onboarding_next': 'Berikutnya',
        'onboarding_skip': 'Lewati',
        'compare_plans': 'Bandingkan Gratis vs Premium',
        'hide_comparison': 'Sembunyikan Perbandingan Paket',
        'age_under_14': 'Di bawah 14',
        'age_15_18': '15 - 18',
        'age_19_25': '19 - 25',
        'age_26_35': '26 - 35',
        'age_36_50': '36 - 50',
        'age_over_50': 'Di atas 50'
    },
    'bg': {
        'onboarding_1_title': 'Добре дошли в Aliolo',
        'onboarding_1_desc': 'Учете визуално. Овладейте перманентно. Вашият спътник за визуално обучение, задвижван от науката SM-2.',
        'onboarding_2_title': 'На колко години сте?',
        'onboarding_2_desc': 'Това ни помага да персонализираме вашето учебно изживяване и да препоръчаме правилните предмети.',
        'onboarding_3_title': 'Какво искате да овладеете?',
        'onboarding_3_desc': 'Изберете основния си интерес, за да персонализирате началното си табло.',
        'onboarding_4_title': 'Създавайте и споделяйте',
        'onboarding_4_desc': 'Изградете своя собствена колода или се потопете в карти, споделени от учащи в Aliolo по целия свят. Учете със свое собствено темпо, след което се тествайте, когато сте готови.',
        'onboarding_5_title': 'Овладявайте навсякъде',
        'onboarding_5_desc': 'Вашата библиотека остава синхронизирана на всички ваши устройства. Ще ви подсещаме само когато е време да защитите серията си.',
        'onboarding_6_title': 'Присъединете се към общността',
        'onboarding_6_desc': 'Започнете своето пътуване днес и овладейте всичко, което си наумите.',
        'onboarding_7_quote': 'Aliolo напълно трансформира начина, по който децата ми и аз овладяваме нови теми. Визуалните карти и интервалното повторение правят ученето да изглежда като игра!',
        'onboarding_7_joined': 'Присъединиха се хиляди учащи',
        'onboarding_next': 'Напред',
        'onboarding_skip': 'Пропусни',
        'compare_plans': 'Сравнете безплатен срещу премиум',
        'hide_comparison': 'Скриване на сравнението на плановете',
        'age_under_14': 'Под 14',
        'age_15_18': '15 - 18',
        'age_19_25': '19 - 25',
        'age_26_35': '26 - 35',
        'age_36_50': '36 - 50',
        'age_over_50': 'Над 50'
    },
    'cs': {
        'onboarding_1_title': 'Vítejte v Aliolo',
        'onboarding_1_desc': 'Učte se vizuálně. Ovládejte trvale. Váš vizuální společník pro učení poháněný vědou SM-2.',
        'onboarding_2_title': 'Kolik vám je let?',
        'onboarding_2_desc': 'To nám pomůže přizpůsobit vaše učení a doporučit ty správné předměty.',
        'onboarding_3_title': 'Co chcete ovládnout?',
        'onboarding_3_desc': 'Vyberte svůj primární zájem a přizpůsobte si úvodní panel.',
        'onboarding_4_title': 'Vytvářejte a sdílejte',
        'onboarding_4_desc': 'Sestavte si vlastní balíček nebo se ponořte do karet sdílených studenty Aliolo po celém světě. Učte se vlastním tempem a otestujte se, až budete připraveni.',
        'onboarding_5_title': 'Ovládejte kdekoli',
        'onboarding_5_desc': 'Vaše knihovna zůstává synchronizovaná ve všech vašich zařízeních. Upozorníme vás, jen když bude čas chránit vaši sérii.',
        'onboarding_6_title': 'Připojte se ke komunitě',
        'onboarding_6_desc': 'Začněte svou cestu dnes a ovládněte cokoli, co si předsevzete.',
        'onboarding_7_quote': 'Aliolo zcela změnilo způsob, jakým moje děti i já ovládáme nová témata. Vizuální karty a rozložené opakování dělají z učení hru!',
        'onboarding_7_joined': 'Připojily se tisíce studentů',
        'onboarding_next': 'Další',
        'onboarding_skip': 'Přeskočit',
        'compare_plans': 'Porovnat zdarma vs. prémiové',
        'hide_comparison': 'Skrýt porovnání plánů',
        'age_under_14': 'Pod 14',
        'age_15_18': '15 - 18',
        'age_19_25': '19 - 25',
        'age_26_35': '26 - 35',
        'age_36_50': '36 - 50',
        'age_over_50': 'Nad 50'
    },
    'da': {
        'onboarding_1_title': 'Velkommen til Aliolo',
        'onboarding_1_desc': 'Lær visuelt. Mestre permanent. Din visuelle læringskammerat drevet af SM-2 videnskab.',
        'onboarding_2_title': 'Hvor gammel er du?',
        'onboarding_2_desc': 'Dette hjælper os med at personliggøre din læringsoplevelse og anbefale de rigtige emner.',
        'onboarding_3_title': 'Hvad vil du mestre?',
        'onboarding_3_desc': 'Vælg din primære interesse for at tilpasse dit indledende instrumentbræt.',
        'onboarding_4_title': 'Opret og del',
        'onboarding_4_desc': 'Byg dit eget dæk eller dyk ned i kort delt af Aliolo-lærende over hele verden. Lær i dit eget tempo, og test dig selv, når du er klar.',
        'onboarding_5_title': 'Mestre overalt',
        'onboarding_5_desc': 'Dit bibliotek forbliver synkroniseret på tværs af alle dine enheder. Vi giver dig kun et puf, når det er tid til at beskytte din streak.',
        'onboarding_6_title': 'Bliv en del af fællesskabet',
        'onboarding_6_desc': 'Start din rejse i dag og mestre alt, hvad du sætter dig for.',
        'onboarding_7_quote': 'Aliolo har fuldstændig ændret den måde, mine børn og jeg mestrer nye emner på. De visuelle kort og spaced repetition får læring til at føles som en leg!',
        'onboarding_7_joined': 'Deltaget af tusindvis af lærende',
        'onboarding_next': 'Næste',
        'onboarding_skip': 'Spring over',
        'compare_plans': 'Sammenlign gratis vs. premium',
        'hide_comparison': 'Skjul plansammenligning',
        'age_under_14': 'Under 14',
        'age_15_18': '15 - 18',
        'age_19_25': '19 - 25',
        'age_26_35': '26 - 35',
        'age_36_50': '36 - 50',
        'age_over_50': 'Over 50'
    },
    'de': {
        'onboarding_1_title': 'Willkommen bei Aliolo',
        'onboarding_1_desc': 'Visuell lernen. Dauerhaft meistern. Dein visueller Lernbegleiter, basierend auf SM-2-Wissenschaft.',
        'onboarding_2_title': 'Wie alt bist du?',
        'onboarding_2_desc': 'Dies hilft uns, dein Lernerlebnis zu personalisieren und die richtigen Themen zu empfehlen.',
        'onboarding_3_title': 'Was möchtest du meistern?',
        'onboarding_3_desc': 'Wähle dein Hauptinteresse aus, um dein initiales Dashboard anzupassen.',
        'onboarding_4_title': 'Erstellen & Teilen',
        'onboarding_4_desc': 'Erstelle dein eigenes Deck oder tauche in Karten ein, die von Aliolo-Lernern weltweit geteilt werden. Lerne in deinem Tempo und teste dich selbst, wenn du bereit bist.',
        'onboarding_5_title': 'Überall meistern',
        'onboarding_5_desc': 'Deine Bibliothek bleibt auf allen deinen Geräten synchron. Wir erinnern dich nur, wenn es Zeit ist, deine Serie zu schützen.',
        'onboarding_6_title': 'Tritt der Community bei',
        'onboarding_6_desc': 'Beginne deine Reise heute und meistere alles, was du dir vornimmst.',
        'onboarding_7_quote': 'Aliolo hat die Art und Weise, wie meine Kinder und ich neue Themen meistern, völlig verändert. Die visuellen Karten und die abgestufte Wiederholung lassen das Lernen wie ein Spiel erscheinen!',
        'onboarding_7_joined': 'Tausende von Lernern sind dabei',
        'onboarding_next': 'Weiter',
        'onboarding_skip': 'Überspringen',
        'compare_plans': 'Kostenlos vs. Premium vergleichen',
        'hide_comparison': 'Planvergleich ausblenden',
        'age_under_14': 'Unter 14',
        'age_15_18': '15 - 18',
        'age_19_25': '19 - 25',
        'age_26_35': '26 - 35',
        'age_36_50': '36 - 50',
        'age_over_50': 'Über 50'
    },
    'et': {
        'onboarding_1_title': 'Tere tulemast Aliolosse',
        'onboarding_1_desc': 'Õpi visuaalselt. Omanda jäädavalt. Sinu visuaalne õpikaaslane, mis põhineb SM-2 teadusel.',
        'onboarding_2_title': 'Kui vana sa oled?',
        'onboarding_2_desc': 'See aitab meil sinu õpikogemust personaliseerida ja soovitada õigeid teemasid.',
        'onboarding_3_title': 'Mida sa soovid omandada?',
        'onboarding_3_desc': 'Vali oma peamine huvi, et kohandada oma algset töölauda.',
        'onboarding_4_title': 'Loo ja jaga',
        'onboarding_4_desc': 'Koosta oma kaardipakk või süvene kaartidesse, mida jagavad Aliolo õppijad üle maailma. Õpi oma tempos ja pane end proovile, kui oled valmis.',
        'onboarding_5_title': 'Omanda kõikjal',
        'onboarding_5_desc': 'Sinu raamatukogu püsib kõigis seadmetes sünroonis. Anname sulle märku vaid siis, kui on aeg kaitsta oma õpijärge.',
        'onboarding_6_title': 'Liitu kogukonnaga',
        'onboarding_6_desc': 'Alusta oma teekonda täna ja omanda kaikki, mille ette võtad.',
        'onboarding_7_quote': 'Aliolo on täielikult muutnud viisi, kuidas mina ja minu lapsed uusi teemasid omandame. Visuaalsed kaardid ja kordamine teevad õppimisest mängu!',
        'onboarding_7_joined': 'Liitunud tuhandete õppijatega',
        'onboarding_next': 'Edasi',
        'onboarding_skip': 'Jäta vahele',
        'compare_plans': 'Võrdle tasuta ja Premium paketti',
        'hide_comparison': 'Peida pakettide võrdlus',
        'age_under_14': 'Alla 14',
        'age_15_18': '15 - 18',
        'age_19_25': '19 - 25',
        'age_26_35': '26 - 35',
        'age_36_50': '36 - 50',
        'age_over_50': 'Üle 50'
    },
    'es': {
        'onboarding_1_title': 'Bienvenido a Aliolo',
        'onboarding_1_desc': 'Aprende visualmente. Domina permanentemente. Tu compañero de aprendizaje visual impulsado por la ciencia SM-2.',
        'onboarding_2_title': '¿Qué edad tienes?',
        'onboarding_2_desc': 'Esto nos ayuda a personalizar tu experiencia de aprendizaje y recomendarte los temas adecuados.',
        'onboarding_3_title': '¿Qué quieres dominar?',
        'onboarding_3_desc': 'Selecciona tu interés principal para personalizar tu panel inicial.',
        'onboarding_4_title': 'Crear y Compartir',
        'onboarding_4_desc': 'Crea tu propio mazo o sumérgete en las cartas compartidas por estudiantes de Aliolo en todo el mundo. Aprende a tu ritmo y luego ponte a prueba cuando estés listo.',
        'onboarding_5_title': 'Domina en cualquier lugar',
        'onboarding_5_desc': 'Tu biblioteca se mantiene sincronizada en todos tus dispositivos. Solo te daremos un toque cuando sea el momento de proteger tu racha.',
        'onboarding_6_title': 'Únete a la comunidad',
        'onboarding_6_desc': 'Comienza tu viaje hoy y domina cualquier cosa que te propongas.',
        'onboarding_7_quote': 'Aliolo ha transformado completamente la forma en que mis hijos y yo dominamos nuevos temas. ¡Las tarjetas visuales y la repetición espaciada hacen que el aprendizaje parezca un juego!',
        'onboarding_7_joined': 'Se han unido miles de estudiantes',
        'onboarding_next': 'Siguiente',
        'onboarding_skip': 'Omitir',
        'compare_plans': 'Comparar Gratis vs Premium',
        'hide_comparison': 'Ocultar comparación de planes',
        'age_under_14': 'Menores de 14',
        'age_15_18': '15 - 18',
        'age_19_25': '19 - 25',
        'age_26_35': '26 - 35',
        'age_36_50': '36 - 50',
        'age_over_50': 'Mayores de 50'
    },
    'fr': {
        'onboarding_1_title': 'Bienvenue sur Aliolo',
        'onboarding_1_desc': 'Apprenez visuellement. Maîtrisez durablement. Votre compagnon d\'apprentissage visuel propulsé par la science SM-2.',
        'onboarding_2_title': 'Quel âge avez-vous ?',
        'onboarding_2_desc': 'Cela nous aide à personnaliser votre expérience d\'apprentissage et à recommander les bons sujets.',
        'onboarding_3_title': 'Que voulez-vous maîtriser ?',
        'onboarding_3_desc': 'Sélectionnez votre intérêt principal pour personnaliser votre tableau de bord initial.',
        'onboarding_4_title': 'Créer & Partager',
        'onboarding_4_desc': 'Créez votre propre jeu ou plongez dans les cartes partagées par les apprenants Aliolo du monde entier. Apprenez à votre rythme, puis testez-vous quand vous êtes prêt.',
        'onboarding_5_title': 'Maîtrisez n\'importe où',
        'onboarding_5_desc': 'Votre bibliothèque reste synchronisée sur tous vos appareils. Nous ne vous solliciterons que lorsqu\'il sera temps de protéger votre série.',
        'onboarding_6_title': 'Rejoignez la communauté',
        'onboarding_6_desc': 'Commencez votre voyage aujourd\'hui et maîtrisez tout ce que vous entreprenez.',
        'onboarding_7_quote': 'Aliolo a complètement transformé la façon dont mes enfants et moi maîtrisons de nouveaux sujets. Les cartes visuelles et la répétition espacée font de l\'apprentissage un jeu !',
        'onboarding_7_joined': 'Rejoint par des milliers d\'apprenants',
        'onboarding_next': 'Suivant',
        'onboarding_skip': 'Passer',
        'compare_plans': 'Comparer Gratuit vs Premium',
        'hide_comparison': 'Masquer la comparaison des forfaits',
        'age_under_14': 'Moins de 14 ans',
        'age_15_18': '15 - 18 ans',
        'age_19_25': '19 - 25 ans',
        'age_26_35': '26 - 35 ans',
        'age_36_50': '36 - 50 ans',
        'age_over_50': 'Plus de 50 ans'
    },
    'ga': {
        'onboarding_1_title': 'Fáilte go Aliolo',
        'onboarding_1_desc': 'Foghlaim go hAmhairc. Máistreacht go Buan. Do chompánach foghlama amhairc bunaithe ar eolaíocht SM-2.',
        'onboarding_2_title': 'Cén aois thú?',
        'onboarding_2_desc': 'Cabhraíonn sé seo linn do thaithí foghlama a phearsantú agus na hábhair chearta a mholadh.',
        'onboarding_3_title': 'Cad ba mhaith leat a mháistir?',
        'onboarding_3_desc': 'Roghnaigh do phríomhspéis chun do dheais tosaigh a shaincheapadh.',
        'onboarding_4_title': 'Cruthaigh & Comhroinn',
        'onboarding_4_desc': 'Tóg do dheic féin nó tumadh isteach i gcártaí roinnte ag foghlaimeoirí Aliolo ar fud an domhain. Foghlaim ar do luas féin, ansin déan tástáil ort féin nuair a bhíonn tú réidh.',
        'onboarding_5_title': 'Máistreacht áit ar bith',
        'onboarding_5_desc': 'Fanann do leabharlann sioncronaithe ar do ghléasanna go léir. Ní thabharfaimid leid duit ach nuair a bheidh sé in am do stríoc a chosaint.',
        'onboarding_6_title': 'Bí sa Phobal',
        'onboarding_6_desc': 'Tosaigh do thuras inniu agus máistir rud ar bith a chuireann tú d\'intinn chuige.',
        'onboarding_7_quote': 'D\'athraigh Aliolo go hiomlán an bealach a n-éiríonn liom féin agus mo pháistí máistreacht a fháil ar thopaicí nua. Is cosúil le cluiche é an fhoghlaim mar gheall ar na cártaí amhairc!',
        'onboarding_7_joined': 'Na mílte foghlaimeoirí tar éis dul isteach',
        'onboarding_next': 'Ar aghaidh',
        'onboarding_skip': 'Scipeáil',
        'compare_plans': 'Déan comparáid idir Saor in aisce agus Préimh',
        'hide_comparison': 'Folaigh Comparáid Plean',
        'age_under_14': 'Faoi 14',
        'age_15_18': '15 - 18',
        'age_19_25': '19 - 25',
        'age_26_35': '26 - 35',
        'age_36_50': '36 - 50',
        'age_over_50': 'Os cionn 50'
    },
    'hr': {
        'onboarding_1_title': 'Dobrodošli u Aliolo',
        'onboarding_1_desc': 'Učite vizualno. Savladajte trajno. Vaš pratitelj za vizualno učenje potpomognut SM-2 znanošću.',
        'onboarding_2_title': 'Koliko imate godina?',
        'onboarding_2_desc': 'To nam pomaže personalizirati vaše iskustvo učenja i preporučiti prave predmete.',
        'onboarding_3_title': 'Što želite savladati?',
        'onboarding_3_desc': 'Odaberite svoj primarni interes kako biste prilagodili svoju početnu nadzornu ploču.',
        'onboarding_4_title': 'Stvorite i podijelite',
        'onboarding_4_desc': 'Sastavite vlastiti špil ili uronite u kartice koje dijele Aliolo polaznici diljem svijeta. Učite svojim tempom, a zatim se testirajte kada budete spremni.',
        'onboarding_5_title': 'Savladajte bilo gdje',
        'onboarding_5_desc': 'Vaša knjižnica ostaje sinkronizirana na svim vašim uređajima. Podsjetit ćemo vas samo kada bude vrijeme da zaštitite svoj niz.',
        'onboarding_6_title': 'Pridružite se zajednici',
        'onboarding_6_desc': 'Započnite svoje putovanje danas i savladajte sve što naumite.',
        'onboarding_7_quote': 'Aliolo je potpuno transformirao način na koji moja djeca i ja svladavamo nove teme. Vizualne kartice i ponavljanje u razmacima čine učenje igrom!',
        'onboarding_7_joined': 'Pridružile su se tisuće polaznika',
        'onboarding_next': 'Dalje',
        'onboarding_skip': 'Preskoči',
        'compare_plans': 'Usporedite besplatno i Premium',
        'hide_comparison': 'Sakrij usporedbu planova',
        'age_under_14': 'Ispod 14',
        'age_15_18': '15 - 18',
        'age_19_25': '19 - 25',
        'age_26_35': '26 - 35',
        'age_36_50': '36 - 50',
        'age_over_50': 'Iznad 50'
    },
    'it': {
        'onboarding_1_title': 'Benvenuti su Aliolo',
        'onboarding_1_desc': 'Impara visivamente. Padroneggia permanentemente. Il tuo compagno di apprendimento visivo alimentato dalla scienza SM-2.',
        'onboarding_2_title': 'Quanti anni hai?',
        'onboarding_2_desc': 'Questo ci aiuta a personalizzare la tua esperienza di apprendimento e consigliare i soggetti giusti.',
        'onboarding_3_title': 'Cosa vuoi padroneggiare?',
        'onboarding_3_desc': 'Seleziona il tuo interesse primario per personalizzare la tua dashboard iniziale.',
        'onboarding_4_title': 'Crea e Condividi',
        'onboarding_4_desc': 'Costruisci il tuo mazzo o tuffati nelle carte condivise dagli studenti di Aliolo in tutto il mondo. Impara al tuo ritmo, poi mettiti alla prova quando sei pronto.',
        'onboarding_5_title': 'Padroneggia Ovunque',
        'onboarding_5_desc': 'La tua libreria rimane sincronizzata su tutti i tuoi dispositivi. Ti avviseremo solo quando sarà il momento di proteggere la tua serie.',
        'onboarding_6_title': 'Unisciti alla Community',
        'onboarding_6_desc': 'Inizia il tuo viaggio oggi e padroneggia tutto ciò che ti prefiggi.',
        'onboarding_7_quote': 'Aliolo ha completamente trasformato il modo in cui io e i miei figli padroneggiamo nuovi argomenti. Le carte visive e la ripetizione spaziata fanno sembrare l\'apprendimento un gioco!',
        'onboarding_7_joined': 'Uniti a migliaia di studenti',
        'onboarding_next': 'Avanti',
        'onboarding_skip': 'Salta',
        'compare_plans': 'Confronta Gratis vs Premium',
        'hide_comparison': 'Nascondi Confronto Piani',
        'age_under_14': 'Sotto i 14',
        'age_15_18': '15 - 18',
        'age_19_25': '19 - 25',
        'age_26_35': '26 - 35',
        'age_36_50': '36 - 50',
        'age_over_50': 'Oltre 50'
    },
    'lv': {
        'onboarding_1_title': 'Laipni lūdzam Aliolo',
        'onboarding_1_desc': 'Mācieties vizuāli. Apgūstiet paliekoši. Jūsu vizuālais mācību biedrs, kura pamatā ir SM-2 zinātne.',
        'onboarding_2_title': 'Cik jums ir gadu?',
        'onboarding_2_desc': 'Tas palīdz mums personalizēt jūsu mācību pieredzi un ieteikt piemērotākos priekšmetus.',
        'onboarding_3_title': 'Ko jūs vēlaties apgūt?',
        'onboarding_3_desc': 'Izvēlieties savu galveno interesi, lai pielāgotu sākotnējo informācijas paneli.',
        'onboarding_4_title': 'Izveidojiet un kopīgojiet',
        'onboarding_4_desc': 'Izveidojiet savu kāršu komplektu vai iedziļinieties kartītēs, ar kurām dalās Aliolo lietotāji visā pasaulē. Mācieties savā tempā un pēc tam pārbaudiet sevi, kad esat gatavs.',
        'onboarding_5_title': 'Apgūstiet jebkur',
        'onboarding_5_desc': 'Jūsu bibliotēka tiek sinhronizēta visās jūsu ierīcēs. Mēs jūs mudināsim tikai tad, kad būs laiks aizsargāt savu sēriju.',
        'onboarding_6_title': 'Pievienojieties kopienai',
        'onboarding_6_desc': 'Sāciet savu ceļojumu šodien un apgūstiet visu, ko esat iecerējis.',
        'onboarding_7_quote': 'Aliolo ir pilnībā mainījis veidu, kā es un mani bērni apgūstam jaunas tēmas. Vizuālās kartītes un intervālu atkārtošana liek mācībām justies kā spēlei!',
        'onboarding_7_joined': 'Pievienojušies tūkstošiem izglītojamo',
        'onboarding_next': 'Tālāk',
        'onboarding_skip': 'Izlaist',
        'compare_plans': 'Salīdzināt bezmaksas pret Premium',
        'hide_comparison': 'Paslēpt plānu salīdzinājumu',
        'age_under_14': 'Zem 14',
        'age_15_18': '15 - 18',
        'age_19_25': '19 - 25',
        'age_26_35': '26 - 35',
        'age_36_50': '36 - 50',
        'age_over_50': 'Virs 50'
    },
    'lt': {
        'onboarding_1_title': 'Sveiki atvykę į Aliolo',
        'onboarding_1_desc': 'Mokykitės vizualiai. Įsisavinkite visam laikui. Jūsų vizualaus mokymosi palydovas, pagrįstas SM-2 mokslu.',
        'onboarding_2_title': 'Kiek jums metų?',
        'onboarding_2_desc': 'Tai padeda mums personalizuoti jūsų mokymosi patirtį ir rekomenduoti tinkamus dalykus.',
        'onboarding_3_title': 'Ką norite įsisavinti?',
        'onboarding_3_desc': 'Pasirinkite pagrindinį interesą, kad pritaikytumėte pradinį prietaisų skydelį.',
        'onboarding_4_title': 'Kurkite ir dalinkitės',
        'onboarding_4_desc': 'Susikurkite savo rinkinį arba pasinerkite į korteles, kuriomis dalijasi Aliolo mokiniai visame pasaulyje. Mokykitės savo tempu, tada išbandykite save, kai būsite pasiruošę.',
        'onboarding_5_title': 'Įsisavinkite bet kur',
        'onboarding_5_desc': 'Jūsų biblioteka sinchronizuojama visuose įrenginiuose. Priminsime tik tada, kai ateis laikas apsaugoti savo seriją.',
        'onboarding_6_title': 'Prisijunkite prie bendruomenės',
        'onboarding_6_desc': 'Pradėkite savo kelionę šiandien ir įsisavinkite viską, ką užsibrėžėte.',
        'onboarding_7_quote': 'Aliolo visiškai pakeitė tai, jak aš ir mano vaikai įsisaviname naujas temas. Vizualios kortelės ir pasikartojimai daro mokymąsi panašų į žaidimą!',
        'onboarding_7_joined': 'Prisijungė tūkstančiai mokinių',
        'onboarding_next': 'Toliau',
        'onboarding_skip': 'Praleisti',
        'compare_plans': 'Palyginkite nemokamą ir „Premium“',
        'hide_comparison': 'Slėpti planų palyginimą',
        'age_under_14': 'Iki 14',
        'age_15_18': '15 - 18',
        'age_19_25': '19 - 25',
        'age_26_35': '26 - 35',
        'age_36_50': '36 - 50',
        'age_over_50': 'Virš 50'
    },
    'hu': {
        'onboarding_1_title': 'Üdvözöljük az Aliolo világában',
        'onboarding_1_desc': 'Tanuljon vizuálisan. Sajátítsa el véglegesen. Vizuális tanulási társa az SM-2 tudomány erejével.',
        'onboarding_2_title': 'Hány éves vagy?',
        'onboarding_2_desc': 'Ez segít nekünk személyre szabni a tanulási élményt, és a megfelelő tantárgyakat ajánlani.',
        'onboarding_3_title': 'Mit szeretnél elsajátítani?',
        'onboarding_3_desc': 'Válaszd ki az elsődleges érdeklődési körödet a kezdő irányítópult testreszabásához.',
        'onboarding_4_title': 'Létrehozás és megosztás',
        'onboarding_4_desc': 'Építsd fel saját paklidat, vagy merülj el az Aliolo tanulók által világszerte megosztott kártyákban. Tanulj a saját tempódban, majd teszteld magad, amikor készen állsz.',
        'onboarding_5_title': 'Sajátítsa el bárhol',
        'onboarding_5_desc': 'A könyvtárad minden eszközödön szinkronban marad. Csak akkor fogunk figyelmeztetni, amikor ideje megvédeni a sorozatodat.',
        'onboarding_6_title': 'Csatlakozz a közösséghez',
        'onboarding_6_desc': 'Kezdje el az utazást ma, és sajátítson el bármit, amit elhatározott.',
        'onboarding_7_quote': 'Az Aliolo teljesen átalakította a gyermekeim és az én tanulási módszereinket. A vizuális kártyák és az ismétlés játéknak tűnik a tanulás közben!',
        'onboarding_7_joined': 'Tanulók ezrei csatlakoztak már',
        'onboarding_next': 'Tovább',
        'onboarding_skip': 'Kihagyás',
        'compare_plans': 'Ingyenes vs. Premium összehasonlítása',
        'hide_comparison': 'Csomagok összehasonlításának elrejtése',
        'age_under_14': '14 év alatt',
        'age_15_18': '15 - 18',
        'age_19_25': '19 - 25',
        'age_26_35': '26 - 35',
        'age_36_50': '36 - 50',
        'age_over_50': '50 év felett'
    },
    'mt': {
        'onboarding_1_title': 'Merħba f\'Aliolo',
        'onboarding_1_desc': 'Tgħallem Viżwalment. Ikkontrolla b\'mod Permanenti. Il-kumpann tat-tagħlim viżwali tiegħek imħaddem mix-xjenza SM-2.',
        'onboarding_2_title': 'Kemm għandek żmien?',
        'onboarding_2_desc': 'Dan jgħinna nippersonalizzaw l-esperjenza tat-tagħlim tiegħek u nirrakkomandaw is-suġġetti t-tajba.',
        'onboarding_3_title': 'X\'tixtieq tikkontrolla?',
        'onboarding_3_desc': 'Agħżel l-interess primarju tiegħek biex tippersonalizza d-dashboard inizjali tiegħek.',
        'onboarding_4_title': 'Oħloq u Aqsam',
        'onboarding_4_desc': 'Ibni l-gverta tiegħek jew idħol f\'karti maqsuma mill-istudenti ta\' Aliolo madwar id-dinja. Tgħallem bil-pass tiegħek, imbagħad ittestja lilek innifsek meta tkun lest.',
        'onboarding_5_title': 'Ikkontrolla Kullimkien',
        'onboarding_5_desc': 'Il-librerija tiegħek tibqa\' sinkronizzata fl-apparati kollha tiegħek. Aħna ninfurmak biss meta jkun wasal iż-żmien li tipproteġi l-istreak tiegħek.',
        'onboarding_6_title': 'Ingħaqad mal-Komunità',
        'onboarding_6_desc': 'Ibda l-vjaġġ tiegħek illum u kkontrolla kull ħaġa li tpoġġi f\'moħħok.',
        'onboarding_7_quote': 'Aliolo bidlet kompletament il-mod kif uliedi u jien nikkontrollaw suġġetti ġodda. Il-karti viżwali u r-ripetizzjoni jagħmlu t-tagħlim iħossu bħal logħba!',
        'onboarding_7_joined': 'Ingħaqdu eluf ta\' studenti',
        'onboarding_next': 'Li jmiss',
        'onboarding_skip': 'Aqbeż',
        'compare_plans': 'Qabbel Free vs Premium',
        'hide_comparison': 'Aħbi l-Paragun tal-Pjan',
        'age_under_14': 'Taħt l-14',
        'age_15_18': '15 - 18',
        'age_19_25': '19 - 25',
        'age_26_35': '26 - 35',
        'age_36_50': '36 - 50',
        'age_over_50': 'Fuq il-50'
    },
    'nl': {
        'onboarding_1_title': 'Welkom bij Aliolo',
        'onboarding_1_desc': 'Leer Visueel. Beheers Permanent. Je visuele leerpartner aangedreven door SM-2-wetenschap.',
        'onboarding_2_title': 'Hoe oud ben je?',
        'onboarding_2_desc': 'Dit helpt ons je leerervaring te personaliseren en de juiste onderwerpen aan te bevelen.',
        'onboarding_3_title': 'Wat wil je beheersen?',
        'onboarding_3_desc': 'Selecteer je primaire interesse om je eerste dashboard aan te passen.',
        'onboarding_4_title': 'Creëren & Delen',
        'onboarding_4_desc': 'Bouw je eigen deck of duik in kaarten die worden gedeeld door Aliolo-leerlingen wereldwijd. Leer in je eigen tempo en test jezelf wanneer je er klaar voor bent.',
        'onboarding_5_title': 'Beheers Overal',
        'onboarding_5_desc': 'Je bibliotheek blijft gesynchroniseerd op al je apparaten. We geven je alleen een seintje als het tijd is om je streak te beschermen.',
        'onboarding_6_title': 'Word lid van de Community',
        'onboarding_6_desc': 'Begin vandaag nog aan je reis en beheers alles wat je van plan bent.',
        'onboarding_7_quote': 'Aliolo heeft de manier waarop mijn kinderen en ik nieuwe onderwerpen beheersen volledig veranderd. De visuele kaarten en gespreide herhaling maken het leren als een spel!',
        'onboarding_7_joined': 'Aangesloten door duizenden leerlingen',
        'onboarding_next': 'Volgende',
        'onboarding_skip': 'Overslaan',
        'compare_plans': 'Vergelijk Gratis vs Premium',
        'hide_comparison': 'Verberg Planvergelijking',
        'age_under_14': 'Onder 14',
        'age_15_18': '15 - 18',
        'age_19_25': '19 - 25',
        'age_26_35': '26 - 35',
        'age_36_50': '36 - 50',
        'age_over_50': 'Boven 50'
    },
    'pl': {
        'onboarding_1_title': 'Witaj w Aliolo',
        'onboarding_1_desc': 'Ucz się wizualnie. Opanuj na stałe. Twój wizualny towarzysz nauki oparty na nauce SM-2.',
        'onboarding_2_title': 'Ile masz lat?',
        'onboarding_2_desc': 'Pomoże nam to spersonalizować Twoją naukę i polecić odpowiednie przedmioty.',
        'onboarding_3_title': 'Co chcesz opanować?',
        'onboarding_3_desc': 'Wybierz swoje główne zainteresowania, aby dostosować swój początkowy pulpit.',
        'onboarding_4_title': 'Twórz i udostępniaj',
        'onboarding_4_desc': 'Zbuduj własną talię lub zanurz się w kartach udostępnionych przez uczniów Aliolo na całym świecie. Ucz się we własnym tempie, a następnie sprawdź się, gdy będziesz gotowy.',
        'onboarding_5_title': 'Opanuj wszędzie',
        'onboarding_5_desc': 'Twoja biblioteka jest zsynchronizowana na wszystkich Twoich urządzeniach. Powiadomimy Cię tylko wtedy, gdy nadejdzie czas na ochronę Twojej serii.',
        'onboarding_6_title': 'Dołącz do społeczności',
        'onboarding_6_desc': 'Zacznij swoją podróż już dziś i opanuj wszystko, co sobie zaplanujesz.',
        'onboarding_7_quote': 'Aliolo całkowicie zmieniło sposób, w jaki moje dzieci i ja opanowujemy nowe tematy. Wizualne karty i powtarzanie w odstępach sprawiają, że nauka przypomina zabawę!',
        'onboarding_7_joined': 'Dołączyły tysiące uczniów',
        'onboarding_next': 'Dalej',
        'onboarding_skip': 'Pomiń',
        'compare_plans': 'Porównaj darmowy vs Premium',
        'hide_comparison': 'Ukryj porównanie planów',
        'age_under_14': 'Poniżej 14',
        'age_15_18': '15 - 18',
        'age_19_25': '19 - 25',
        'age_26_35': '26 - 35',
        'age_36_50': '36 - 50',
        'age_over_50': 'Powyżej 50'
    },
    'pt': {
        'onboarding_1_title': 'Bem-vindo ao Aliolo',
        'onboarding_1_desc': 'Aprenda Visualmente. Domine Permanentemente. Seu companheiro de aprendizado visual alimentado pela ciência SM-2.',
        'onboarding_2_title': 'Qual é a sua idade?',
        'onboarding_2_desc': 'Isso nos ajuda a personalizar sua experiência de aprendizado e recomendar os assuntos certos.',
        'onboarding_3_title': 'O que você quer dominar?',
        'onboarding_3_desc': 'Selecione seu interesse principal para personalizar seu painel inicial.',
        'onboarding_4_title': 'Criar e Compartilhar',
        'onboarding_4_desc': 'Crie seu próprio baralho ou mergulhe em cartas compartilhadas por alunos do Aliolo em todo o mundo. Aprenda no seu ritmo e teste-se quando estiver pronto.',
        'onboarding_5_title': 'Domine em Qualquer Lugar',
        'onboarding_5_desc': 'Sua biblioteca permanece sincronizada em todos os seus dispositivos. Apenas avisaremos quando for a hora de proteger sua sequência.',
        'onboarding_6_title': 'Junte-se à Comunidade',
        'onboarding_6_desc': 'Comece sua jornada hoje e domine qualquer coisa que desejar.',
        'onboarding_7_quote': 'O Aliolo transformou completamente a maneira como meus filhos e eu dominamos novos tópicos. Os cartões visuais e a repetição espaçada fazem o aprendizado parecer um jogo!',
        'onboarding_7_joined': 'Juntou-se a milhares de alunos',
        'onboarding_next': 'Próximo',
        'onboarding_skip': 'Pular',
        'compare_plans': 'Comparar Grátis vs Premium',
        'hide_comparison': 'Ocultar Comparação de Planos',
        'age_under_14': 'Menos de 14',
        'age_15_18': '15 - 18',
        'age_19_25': '19 - 25',
        'age_26_35': '26 - 35',
        'age_36_50': '36 - 50',
        'age_over_50': 'Mais de 50'
    },
    'ro': {
        'onboarding_1_title': 'Bun venit la Aliolo',
        'onboarding_1_desc': 'Învață vizual. Stăpânește permanent. Partenerul tău de învățare vizuală bazat pe știința SM-2.',
        'onboarding_2_title': 'Câți ani ai?',
        'onboarding_2_desc': 'Acest lucru ne ajută să îți personalizăm experiența de învățare și să îți recomandăm subiectele potrivite.',
        'onboarding_3_title': 'Ce vrei să stăpânești?',
        'onboarding_3_desc': 'Selectează interesul principal pentru a-ți personaliza tabloul de bord inițial.',
        'onboarding_4_title': 'Creează și Distribuie',
        'onboarding_4_desc': 'Construiește-ți propriul set sau explorează cardurile partajate de cursanții Aliolo din întreaga lume. Învață în ritmul tău, apoi testează-te când ești gata.',
        'onboarding_5_title': 'Stăpânește oriunde',
        'onboarding_5_desc': 'Biblioteca ta rămâne sincronizată pe toate dispozitivele tale. Te vom anunța doar când este timpul să îți protejezi seria.',
        'onboarding_6_title': 'Alătură-te comunității',
        'onboarding_6_desc': 'Începe-ți călătoria astăzi și stăpânește orice îți propui.',
        'onboarding_7_quote': 'Aliolo a transformat complet modul în care copiii mei și cu mine stăpânim subiecte noi. Cardurile vizuale și repetiția distanțată fac învățarea să pară un joc!',
        'onboarding_7_joined': 'S-au alăturat mii de cursanți',
        'onboarding_next': 'Înainte',
        'onboarding_skip': 'Omite',
        'compare_plans': 'Compară Gratuit vs Premium',
        'hide_comparison': 'Ascunde compararea planurilor',
        'age_under_14': 'Sub 14',
        'age_15_18': '15 - 18',
        'age_19_25': '19 - 25',
        'age_26_35': '26 - 35',
        'age_36_50': '36 - 50',
        'age_over_50': 'Peste 50'
    },
    'sk': {
        'onboarding_1_title': 'Vitajte v Aliolo',
        'onboarding_1_desc': 'Učte sa vizuálne. Ovládajte trvalo. Váš vizuálny spoločník na učenie poháňaný vedou SM-2.',
        'onboarding_2_title': 'Koľko máte rokov?',
        'onboarding_2_desc': 'To nám pomôže prispôsobiť vaše učenie a odporučiť tie správne predmety.',
        'onboarding_3_title': 'Čo chcete ovládnuť?',
        'onboarding_3_desc': 'Vyberte svoj primárny záujem a prispôsobte si úvodný panel.',
        'onboarding_4_title': 'Vytvárajte a zdieľajte',
        'onboarding_4_desc': 'Zostavte si vlastný balíček alebo sa ponorte do kariet zdieľaných študentmi Aliolo po celom svete. Učte sa vlastným tempom a otestujte sa, keď budete pripravení.',
        'onboarding_5_title': 'Ovládajte kdekoľvek',
        'onboarding_5_desc': 'Vaša knižnica zostáva synchronizovaná vo všetkých vašich zariadeniach. Upozorníme vás, len keď bude čas chrániť vašu sériu.',
        'onboarding_6_title': 'Pripojte sa ku komunite',
        'onboarding_6_desc': 'Začnite svoju cestu dnes a ovládnite čokoľvek, čo si zaumienite.',
        'onboarding_7_quote': 'Aliolo úplne zmenilo spôsob, akým moje deti aj ja ovládame nové témy. Vizuálne karty a rozložené opakovanie robia z učenia hru!',
        'onboarding_7_joined': 'Pridali sa tisíce študentov',
        'onboarding_next': 'Ďalej',
        'onboarding_skip': 'Preskočiť',
        'compare_plans': 'Porovnať zadarmo vs. Premium',
        'hide_comparison': 'Skryť porovnanie plánov',
        'age_under_14': 'Pod 14',
        'age_15_18': '15 - 18',
        'age_19_25': '19 - 25',
        'age_26_35': '26 - 35',
        'age_36_50': '36 - 50',
        'age_over_50': 'Nad 50'
    },
    'sl': {
        'onboarding_1_title': 'Dobrodošli v Aliolo',
        'onboarding_1_desc': 'Učite se vizualno. Obvladajte trajno. Vaš vizualni sopotnik pri učenju, ki ga poganja znanost SM-2.',
        'onboarding_2_title': 'Koliko ste stari?',
        'onboarding_2_desc': 'To nam pomaga prilagoditi vašo učno izkušnjo in priporočiti prave predmete.',
        'onboarding_3_title': 'Kaj želite obvladati?',
        'onboarding_3_desc': 'Izberite svoje primarno zanimanje, da prilagodite svojo začetno nadzorno ploščo.',
        'onboarding_4_title': 'Ustvarite in delite',
        'onboarding_4_desc': 'Sestavite svoj paket ali se potopite v kartice, ki jih delijo učenci Aliolo po vsem svetu. Učite se v svojem tempu, nato pa se preizkusite, ko boste pripravljeni.',
        'onboarding_5_title': 'Obvladajte kjerkoli',
        'onboarding_5_desc': 'Vaša knjižnica ostaja sinhronizirana v vseh vaših napravah. Opomnili vas bomo le, ko bo čas za zaščito vašega niza.',
        'onboarding_6_title': 'Pridružite se skupnosti',
        'onboarding_6_desc': 'Začnite svojo pot danes in obvladajte vse, kar si zadate.',
        'onboarding_7_quote': 'Aliolo je popolnoma spremenil način, kako moji otroci in jaz obvladujemo nove teme. Vizualne kartice in ponavljanje v razmikih naredijo učenje kot igro!',
        'onboarding_7_joined': 'Pridružilo se je na tisoče učencev',
        'onboarding_next': 'Naprej',
        'onboarding_skip': 'Preskoči',
        'compare_plans': 'Primerjajte brezplačno in Premium',
        'hide_comparison': 'Skrij primerjavo paketov',
        'age_under_14': 'Pod 14',
        'age_15_18': '15 - 18',
        'age_19_25': '19 - 25',
        'age_26_35': '26 - 35',
        'age_36_50': '36 - 50',
        'age_over_50': 'Nad 50'
    },
    'fi': {
        'onboarding_1_title': 'Tervetuloa Alioloon',
        'onboarding_1_desc': 'Opi visuaalisesti. Hallitse pysyvästi. Visuaalinen oppimiskumppanisi, joka perustuu SM-2-tieteeseen.',
        'onboarding_2_title': 'Kuinka vanha olet?',
        'onboarding_2_desc': 'Tämä auttaa meitä personoimaan oppimiskokemuksesi ja suosittelemaan oikeita aiheita.',
        'onboarding_3_title': 'Mitä haluat hallita?',
        'onboarding_3_desc': 'Valitse ensisijainen kiinnostuksesi mukauttaaksesi aloitusnäkymäsi.',
        'onboarding_4_title': 'Luo ja jaa',
        'onboarding_4_desc': 'Rakenna oma pakkasi tai sukella Aliolo-oppijoiden jakamiin kortteihin ympäri maailmaa. Opi omaan tahtiisi ja testaa itsesi, kun olet valmis.',
        'onboarding_5_title': 'Hallitse missä tahansa',
        'onboarding_5_desc': 'Kirjastosi pysyy synkronoituna kaikilla laitteillasi. Muistutamme sinua vain silloin, kun on aika suojata putkesi.',
        'onboarding_6_title': 'Liity yhteisöön',
        'onboarding_6_desc': 'Aloita matkasi tänään ja hallitse mitä tahansa päätätkin.',
        'onboarding_7_quote': 'Aliolo on täysin muuttanut tavan, jolla lapseni ja minä hallitsemme uusia aiheita. Visuaaliset kortit ja jaksotettu kertaus saavat oppimisen tuntumaan peliltä!',
        'onboarding_7_joined': 'Tuhannet oppijat ovat liittyneet',
        'onboarding_next': 'Seuraava',
        'onboarding_skip': 'Ohita',
        'compare_plans': 'Vertaa ilmaista ja Premiumia',
        'hide_comparison': 'Piilota tilausvertailu',
        'age_under_14': 'Alle 14',
        'age_15_18': '15 - 18',
        'age_19_25': '19 - 25',
        'age_26_35': '26 - 35',
        'age_36_50': '36 - 50',
        'age_over_50': 'Yli 50'
    },
    'sv': {
        'onboarding_1_title': 'Välkommen till Aliolo',
        'onboarding_1_desc': 'Lär dig visuellt. Bemästra permanent. Din visuella lärkompis som drivs av SM-2-vetenskap.',
        'onboarding_2_title': 'Hur gammal är du?',
        'onboarding_2_desc': 'Detta hjälper oss att personanpassa din lärandeupplevelse och rekommendera rätt ämnen.',
        'onboarding_3_title': 'Vad vill du bemästra?',
        'onboarding_3_desc': 'Välj ditt primära intresse för att anpassa din första instrumentpanel.',
        'onboarding_4_title': 'Skapa & Dela',
        'onboarding_4_desc': 'Bygg din egen kortlek eller dyk in i kort som delas av Aliolo-lärande över hela världen. Lär dig i din egen takt och testa dig själv när du är redo.',
        'onboarding_5_title': 'Bemästra var som helst',
        'onboarding_5_desc': 'Ditt bibliotek förblir synkroniserat över alla dina enheter. Vi påminner dig bara när det är dags att skydda din streak.',
        'onboarding_6_title': 'Gå med i gemenskapen',
        'onboarding_6_desc': 'Börja din resa idag och bemästra vad du än tar dig för.',
        'onboarding_7_quote': 'Aliolo har helt förändrat sättet som mina barn och jag bemästrar nya ämnen. De visuella korten och den utspridda repetitionen gör att lärandet känns som en lek!',
        'onboarding_7_joined': 'Gått med av tusentals lärande',
        'onboarding_next': 'Nästa',
        'onboarding_skip': 'Hoppa över',
        'compare_plans': 'Jämför gratis vs. premium',
        'hide_comparison': 'Dölj planjämförelse',
        'age_under_14': 'Under 14',
        'age_15_18': '15 - 18',
        'age_19_25': '19 - 25',
        'age_26_35': '26 - 35',
        'age_36_50': '36 - 50',
        'age_over_50': 'Över 50'
    },
    'tl': {
        'onboarding_1_title': 'Maligayang Pagdating sa Aliolo',
        'onboarding_1_desc': 'Matuto nang Visual. Master nang Permanente. Ang iyong visual learning companion na pinatatakbo ng SM-2 science.',
        'onboarding_2_title': 'Ilang taon ka na?',
        'onboarding_2_desc': 'Tinutulungan kami nito na i-personalize ang iyong karanasan sa pag-aaral at irekomenda ang tamang mga paksa.',
        'onboarding_3_title': 'Ano ang gusto mong i-master?',
        'onboarding_3_desc': 'Piliin ang iyong pangunahing interes upang i-customize ang iyong paunang dashboard.',
        'onboarding_4_title': 'Gumawa at Magbahagi',
        'onboarding_4_desc': 'Bumuo ng sarili mong deck o sumisid sa mga card na ibinahagi ng mga nag-aaral ng Aliolo sa buong mundo. Matuto sa sarili mong bilis, pagkatapos ay subukan ang iyong sarili kapag handa ka na.',
        'onboarding_5_title': 'I-master Kahit Saan',
        'onboarding_5_desc': 'Nananatiling naka-sync ang iyong library sa lahat ng iyong device. Bibigyan ka lang namin ng nudge kapag oras na para protektahan ang iyong streak.',
        'onboarding_6_title': 'Sumali sa Komunidad',
        'onboarding_6_desc': 'Simulan ang iyong paglalakbay ngayon at i-master ang anumang itinakda mo sa iyong isip.',
        'onboarding_7_quote': 'Ganap na binago ng Aliolo ang paraan ng pag-master namin ng aking mga anak sa mga bagong paksa. Ang mga visual card at spaced repetition ay nagpaparamdam sa pag-aaral na parang isang laro!',
        'onboarding_7_joined': 'Sinalihan ng libu-libong nag-aaral',
        'onboarding_next': 'Susunod',
        'onboarding_skip': 'Laktawan',
        'compare_plans': 'Ipaghambing ang Libre vs Premium',
        'hide_comparison': 'Itago ang Paghahambing ng Plano',
        'age_under_14': 'Bata sa 14',
        'age_15_18': '15 - 18',
        'age_19_25': '19 - 25',
        'age_26_35': '26 - 35',
        'age_36_50': '36 - 50',
        'age_over_50': 'Higit sa 50'
    },
    'vi': {
        'onboarding_1_title': 'Chào mừng bạn đến với Aliolo',
        'onboarding_1_desc': 'Học qua hình ảnh. Làm chủ vĩnh viễn. Người bạn đồng hành học tập trực quan của bạn được hỗ trợ bởi khoa học SM-2.',
        'onboarding_2_title': 'Bạn bao nhiêu tuổi?',
        'onboarding_2_desc': 'Điều này giúp chúng tôi cá nhân hóa trải nghiệm học tập của bạn và đề xuất các chủ đề phù hợp.',
        'onboarding_3_title': 'Bạn muốn làm chủ điều gì?',
        'onboarding_3_desc': 'Chọn sở thích chính của bạn để tùy chỉnh bảng điều khiển ban đầu.',
        'onboarding_4_title': 'Tạo & Chia sẻ',
        'onboarding_4_desc': 'Xây dựng bộ thẻ của riêng bạn hoặc khám phá các thẻ được chia sẻ bởi những người học Aliolo trên toàn thế giới. Học theo tốc độ của bạn, sau đó tự kiểm tra khi bạn đã sẵn sàng.',
        'onboarding_5_title': 'Làm chủ ở mọi nơi',
        'onboarding_5_desc': 'Thư viện của bạn luôn được đồng bộ hóa trên tất cả các thiết bị. Chúng tôi sẽ chỉ nhắc nhở bạn khi đến lúc bảo vệ chuỗi ngày học của mình.',
        'onboarding_6_title': 'Tham gia cộng đồng',
        'onboarding_6_desc': 'Bắt đầu hành trình của bạn ngay hôm nay và làm chủ bất cứ điều gì bạn đặt tâm trí vào.',
        'onboarding_7_quote': 'Aliolo đã hoàn toàn thay đổi cách các con tôi và tôi làm chủ các chủ đề mới. Các thẻ hình ảnh và sự lặp lại ngắt quãng làm cho việc học giống như một trò chơi!',
        'onboarding_7_joined': 'Được tham gia bởi hàng ngàn người học',
        'onboarding_next': 'Tiếp theo',
        'onboarding_skip': 'Bỏ qua',
        'compare_plans': 'So sánh Miễn phí và Cao cấp',
        'hide_comparison': 'Ẩn so sánh gói dịch vụ',
        'age_under_14': 'Dưới 14',
        'age_15_18': '15 - 18',
        'age_19_25': '19 - 25',
        'age_26_35': '26 - 35',
        'age_36_50': '36 - 50',
        'age_over_50': 'Trên 50'
    },
    'tr': {
        'onboarding_1_title': 'Aliolo\'ya Hoş Geldiniz',
        'onboarding_1_desc': 'Görsel Olarak Öğrenin. Kalıcı Olarak Ustalaşın. SM-2 bilimi ile güçlendirilmiş görsel öğrenme arkadaşınız.',
        'onboarding_2_title': 'Kaç yaşındasınız?',
        'onboarding_2_desc': 'Bu, öğrenme deneyiminizi kişiselleştirmemize ve doğru konuları önermemize yardımcı olur.',
        'onboarding_3_title': 'Neyde ustalaşmak istiyorsunuz?',
        'onboarding_3_desc': 'Başlangıç panelinizi özelleştirmek için ana ilginizi seçin.',
        'onboarding_4_title': 'Oluştur ve Paylaş',
        'onboarding_4_desc': 'Kendi destenizi oluşturun veya dünya çapındaki Aliolo öğrencileri tarafından paylaşılan kartlara dalın. Kendi hızınızda öğrenin, hazır olduğunuzda kendinizi test edin.',
        'onboarding_5_title': 'Her Yerde Ustalaşın',
        'onboarding_5_desc': 'Kütüphaneniz tüm cihazlarınızda senkronize kalır. Sadece serinizi koruma zamanı geldiğinde sizi uyaracağız.',
        'onboarding_6_title': 'Topluluğa Katılın',
        'onboarding_6_desc': 'Yolculuğunuza bugün başlayın ve aklınıza koyduğunuz her şeyde ustalaşın.',
        'onboarding_7_quote': 'Aliolo, çocuklarımın ve benim yeni konularda ustalaşma şeklimizi tamamen değiştirdi. Görsel kartlar ve aralıklı tekrar, öğrenmeyi bir oyun gibi hissettiriyor!',
        'onboarding_7_joined': 'Binlerce öğrenci katıldı',
        'onboarding_next': 'Sonraki',
        'onboarding_skip': 'Atla',
        'compare_plans': 'Ücretsiz ve Premium\'u Karşılaştır',
        'hide_comparison': 'Plan Karşılaştırmasını Gizle',
        'age_under_14': '14 Yaş Altı',
        'age_15_18': '15 - 18',
        'age_19_25': '19 - 25',
        'age_26_35': '26 - 35',
        'age_36_50': '36 - 50',
        'age_over_50': '50 Yaş Üstü'
    },
    'el': {
        'onboarding_1_title': 'Καλώς ήρθατε στο Aliolo',
        'onboarding_1_desc': 'Μάθετε οπτικά. Κατακτήστε μόνιμα. Ο οπτικός σας σύντροφος μάθησης που υποστηρίζεται από την επιστήμη SM-2.',
        'onboarding_2_title': 'Πόσο χρονών είστε;',
        'onboarding_2_desc': 'Αυτό μας βοηθά να εξατομικεύσουμε τη μαθησιακή σας εμπειρία και να προτείνουμε τα σωστά θέματα.',
        'onboarding_3_title': 'Τι θέλετε να κατακτήσετε;',
        'onboarding_3_desc': 'Επιλέξτε το κύριο ενδιαφέρον σας για να προσαρμόσετε τον αρχικό σας πίνακα ελέγχου.',
        'onboarding_4_title': 'Δημιουργία & Κοινή χρήση',
        'onboarding_4_desc': 'Φτιάξτε τη δική σας τράπουλα ή βουτήξτε σε κάρτες που μοιράζονται οι μαθητές του Aliolo σε όλο τον κόσμο. Μάθετε με τον δικό σας ρυθμό και μετά δοκιμάστε τον εαυτό σας όταν είστε έτοιμοι.',
        'onboarding_5_title': 'Κατάκτηση παντού',
        'onboarding_5_desc': 'Η βιβλιοθήκη σας παραμένει συγχρονισμένη σε όλες τις συσκευές σας. Θα σας ειδοποιήσουμε μόνο όταν έρθει η ώρα να προστατεύσετε το σερί σας.',
        'onboarding_6_title': 'Γίνετε μέλος της κοινότητας',
        'onboarding_6_desc': 'Ξεκινήστε το ταξίδι σας σήμερα και κατακτήστε οτιδήποτε βάλετε στο μυαλό σας.',
        'onboarding_7_quote': 'Το Aliolo έχει αλλάξει εντελώς τον τρόπο με τον οποίο τα παιδιά μου και εγώ κατακτούμε νέα θέματα. Οι οπτικές κάρτες και η επανάληψη σε διαστήματα κάνουν τη μάθηση να μοιάζει με παιχνίδι!',
        'onboarding_7_joined': 'Συμμετέχουν χιλιάδες μαθητές',
        'onboarding_next': 'Επόμενο',
        'onboarding_skip': 'Παράλειψη',
        'compare_plans': 'Σύγκριση Δωρεάν έναντι Premium',
        'hide_comparison': 'Απόκρυψη σύγκρισης προγραμμάτων',
        'age_under_14': 'Κάτω από 14',
        'age_15_18': '15 - 18',
        'age_19_25': '19 - 25',
        'age_26_35': '26 - 35',
        'age_36_50': '36 - 50',
        'age_over_50': 'Πάνω από 50'
    },
    'uk': {
        'onboarding_1_title': 'Ласкаво просимо до Aliolo',
        'onboarding_1_desc': 'Навчайтеся візуально. Опановуйте назавжди. Ваш супутник для візуального навчання на базі науки SM-2.',
        'onboarding_2_title': 'Скільки вам років?',
        'onboarding_2_desc': 'Це допоможе нам персоналізувати ваш досвід навчання та рекомендувати відповідні предмети.',
        'onboarding_3_title': 'Що ви хочете опанувати?',
        'onboarding_3_desc': 'Виберіть свій основний інтерес, щоб налаштувати початкову панель керування.',
        'onboarding_4_title': 'Створюйте та діліться',
        'onboarding_4_desc': 'Створюйте власні колоди або занурюйтеся в картки, якими діляться учні Aliolo по всьому світу. Навчайтеся у своєму темпі, а потім перевірте себе, коли будете готові.',
        'onboarding_5_title': 'Опановуйте будь-де',
        'onboarding_5_desc': 'Ваша бібліотека синхронізується на всіх ваших пристроях. Ми нагадаємо вам лише тоді, коли прийде час захистити вашу серію.',
        'onboarding_6_title': 'Приєднуйтесь до спільноти',
        'onboarding_6_desc': 'Почніть свою подорож сьогодні та опануйте все, що задумаєте.',
        'onboarding_7_quote': 'Aliolo повністю змінив те, як мої діти та я опановуємо нові теми. Візуальні картки та інтервальні повторення роблять навчання схожим на гру!',
        'onboarding_7_joined': 'Приєдналися тисячі учнів',
        'onboarding_next': 'Далі',
        'onboarding_skip': 'Пропустити',
        'compare_plans': 'Порівняти Безкоштовний та Преміум',
        'hide_comparison': 'Приховати порівняння планів',
        'age_under_14': 'До 14',
        'age_15_18': '15 - 18',
        'age_19_25': '19 - 25',
        'age_26_35': '26 - 35',
        'age_36_50': '36 - 50',
        'age_over_50': 'Понад 50'
    },
    'ar': {
        'onboarding_1_title': 'مرحباً بك في Aliolo',
        'onboarding_1_desc': 'تعلم بصرياً. أتقن بشكل دائم. رفيقك في التعلم البصري المدعوم بعلم SM-2.',
        'onboarding_2_title': 'كم عمرك؟',
        'onboarding_2_desc': 'هذا يساعدنا على تخصيص تجربة التعلم الخاصة بك والتوصية بالمواد المناسبة.',
        'onboarding_3_title': 'ماذا تريد أن تتقن؟',
        'onboarding_3_desc': 'حدد اهتمامك الأساسي لتخصيص لوحة التحكم الأولية الخاصة بك.',
        'onboarding_4_title': 'الإنشاء والمشاركة',
        'onboarding_4_desc': 'قم ببناء مجموعتك الخاصة أو استكشف البطاقات التي يشاركها متعلمو Aliolo في جميع أنحاء العالم. تعلم بالسرعة التي تناسبك، ثم اختبر نفسك عندما تكون مستعداً.',
        'onboarding_5_title': 'الإتقان في أي مكان',
        'onboarding_5_desc': 'تظل مكتبتك متزامنة عبر جميع أجهزتك. سنقوم فقط بتذكيرك عندما يحين الوقت لحماية سلسلتك.',
        'onboarding_6_title': 'انضم إلى المجتمع',
        'onboarding_6_desc': 'ابدأ رحلتك اليوم وأتقن أي شيء تضعه في اعتبارك.',
        'onboarding_7_quote': 'لقد غيرت Aliolo تماماً الطريقة التي أتقن بها أنا وأطفالي موضوعات جديدة. البطاقات المرئية والتكرار المتباعد يجعل التعلم يبدو وكأنه لعبة!',
        'onboarding_7_joined': 'انضم إليه آلاف المتعلمين',
        'onboarding_next': 'التالي',
        'onboarding_skip': 'تخطي',
        'compare_plans': 'قارن بين الخطط المجانية والمدفوعة',
        'hide_comparison': 'إخفاء مقارنة الخطط',
        'age_under_14': 'أقل من 14',
        'age_15_18': '15 - 18',
        'age_19_25': '19 - 25',
        'age_26_35': '26 - 35',
        'age_36_50': '36 - 50',
        'age_over_50': 'أكثر من 50'
    },
    'hi': {
        'onboarding_1_title': 'Aliolo में आपका स्वागत है',
        'onboarding_1_desc': 'विजुअल सीखें। स्थायी रूप से महारत हासिल करें। SM-2 विज्ञान द्वारा संचालित आपका विजुअल लर्निंग साथी।',
        'onboarding_2_title': 'आपकी उम्र क्या है?',
        'onboarding_2_desc': 'यह हमें आपके सीखने के अनुभव को व्यक्तिगत बनाने और सही विषयों की सिफारिश करने में मदद करता है।',
        'onboarding_3_title': 'आप किसमें महारत हासिल करना चाहते हैं?',
        'onboarding_3_desc': 'अपने शुरुआती डैशबोर्ड को कस्टमाइज़ करने के लिए अपनी प्राथमिक रुचि चुनें।',
        'onboarding_4_title': 'बनाएं और साझा करें',
        'onboarding_4_desc': 'अपना खुद का डेк बनाएं या दुनिया भर में Aliolo सीखने वालों द्वारा साझा किए गए कार्डों में गोता लगाएँ। अपनी गति से सीखें, फिर तैयार होने पर खुद का परीक्षण करें।',
        'onboarding_5_title': 'कहीं भी महारत हासिल करें',
        'onboarding_5_desc': 'आपकी लाइब्रेरी आपके सभी डिवाइसों में सिंक रहती है। जब आपकी स्ट्रीक को सुरक्षित करने का समय होगा, तब हम आपको केवल संकेत देंगे।',
        'onboarding_6_title': 'समुदाय में शामिल हों',
        'onboarding_6_desc': 'आज ही अपनी यात्रा शुरू करें और जो कुछ भी आप अपने मन में ठान लें, उसमें महारत हासिल करें।',
        'onboarding_7_quote': 'Aliolo ने मेरे बच्चों और मेरे नए विषयों में महारत हासिल करने के तरीके को पूरी तरह से बदल दिया है। विजुअल कार्ड और अंतराल पुनरावृत्ति सीखने को एक खेल की तरह महसूस कराते हैं!',
        'onboarding_7_joined': 'हजारों शिक्षार्थियों द्वारा शामिल हुए',
        'onboarding_next': 'अगला',
        'onboarding_skip': 'छोड़ें',
        'compare_plans': 'मुफ्त बनाम प्रीमियम की तुलना करें',
        'hide_comparison': 'प्लान तुलना छिपाएं',
        'age_under_14': '14 से कम',
        'age_15_18': '15 - 18',
        'age_19_25': '19 - 25',
        'age_26_35': '26 - 35',
        'age_36_50': '36 - 50',
        'age_over_50': '50 से अधिक'
    },
    'zh': {
        'onboarding_1_title': '欢迎来到 Aliolo',
        'onboarding_1_desc': '视觉化学习，永久掌握。由 SM-2 科学支持的视觉学习伴侣。',
        'onboarding_2_title': '你多大了？',
        'onboarding_2_desc': '这有助于我们个性化你的学习体验并推荐合适的主题。',
        'onboarding_3_title': '你想掌握什么？',
        'onboarding_3_desc': '选择你的主要兴趣以自定义初始仪表板。',
        'onboarding_4_title': '创建与分享',
        'onboarding_4_desc': '构建你自己的卡组或深入研究全球 Aliolo 学习者分享的卡片。按照你自己的节奏学习，然后在准备好时测试自己。',
        'onboarding_5_title': '随时随地掌握',
        'onboarding_5_desc': '你的库在所有设备上保持同步。我们只会在需要保护你的连续记录时提醒你。',
        'onboarding_6_title': '加入社区',
        'onboarding_6_desc': '今天就开始你的旅程，掌握你下定决心要做的任何事情。',
        'onboarding_7_quote': 'Aliolo 完全改变了我及我的孩子掌握新主题的方式。视觉卡片和间隔重复让学习感觉像是一场游戏！',
        'onboarding_7_joined': '已有成千上万的学习者加入',
        'onboarding_next': '下一步',
        'onboarding_skip': '跳过',
        'compare_plans': '比较免费版 vs 高级版',
        'hide_comparison': '隐藏方案对比',
        'age_under_14': '14 岁以下',
        'age_15_18': '15 - 18',
        'age_19_25': '19 - 25',
        'age_26_35': '26 - 35',
        'age_36_50': '36 - 50',
        'age_over_50': '50 岁以上'
    },
    'ja': {
        'onboarding_1_title': 'Alioloへようこそ',
        'onboarding_1_desc': '視覚的に学び、永続的に習得。SM-2科学に基づいた、あなたの視覚学習コンパニオン。',
        'onboarding_2_title': '年齢を教えてください。',
        'onboarding_2_desc': '学習体験をパーソナライズし、最適な主題を推奨するのに役立ちます。',
        'onboarding_3_title': '何を習得したいですか？',
        'onboarding_3_desc': '主な興味を選択して、初期ダッシュボードをカスタマイズします。',
        'onboarding_4_title': '作成と共有',
        'onboarding_4_desc': '自分だけのデッキを作ったり、世界中のAliolo学習者が共有するカードに飛び込んだりできます。自分のペースで学び、準備ができたらテストしましょう。',
        'onboarding_5_title': 'どこでも習得',
        'onboarding_5_desc': 'ライブラリはすべてのデバイスで同期されます。学習の継続記録を守る時期になったときだけ通知します。',
        'onboarding_6_title': 'コミュニティに参加',
        'onboarding_6_desc': '今日から旅を始めて、決心したことを何でも習得しましょう。',
        'onboarding_7_quote': 'Alioloは、私と子供たちが新しいトピックを習得する方法を完全に変えました。視覚的なカードと間隔を空けた反復練習で、学習がゲームのように感じられます！',
        'onboarding_7_joined': '数千人の学習者が参加中',
        'onboarding_next': '次へ',
        'onboarding_skip': 'スキップ',
        'compare_plans': '無料版とプレミアム版を比較',
        'hide_comparison': 'プラン比較を隠す',
        'age_under_14': '14歳未満',
        'age_15_18': '15 - 18',
        'age_19_25': '19 - 25',
        'age_26_35': '26 - 35',
        'age_36_50': '36 - 50',
        'age_over_50': '50歳以上'
    },
    'ko': {
        'onboarding_1_title': 'Aliolo에 오신 것을 환영합니다',
        'onboarding_1_desc': '시각적으로 배우고 영구적으로 마스터하세요. SM-2 과학으로 강화된 시각 학습 도우미입니다.',
        'onboarding_2_title': '나이가 어떻게 되시나요?',
        'onboarding_2_desc': '학습 경험을 개인화하고 적절한 주제를 추천하는 데 도움이 됩니다.',
        'onboarding_3_title': '무엇을 마스터하고 싶으신가요?',
        'onboarding_3_desc': '초기 대시보드를 사용자 정의하려면 주요 관심사를 선택하세요.',
        'onboarding_4_title': '만들기 및 공유',
        'onboarding_4_desc': '나만의 덱을 만들거나 전 세계 Aliolo 학습자들이 공유한 카드를 살펴보세요. 자신의 속도에 맞춰 배우고 준비가 되면 테스트해보세요.',
        'onboarding_5_title': '어디서나 마스터하기',
        'onboarding_5_desc': '라이브러리는 모든 장치에서 동기화됩니다. 연속 기록을 지켜야 할 때만 알려드립니다.',
        'onboarding_6_title': '커뮤니티 가입',
        'onboarding_6_desc': '오늘부터 여정을 시작하고 마음먹은 무엇이든 마스터하세요.',
        'onboarding_7_quote': 'Aliolo는 저와 아이들이 새로운 주제를 마스터하는 방식을 완전히 바꾸어 놓았습니다. 시각적 카드와 간격 반복 덕분에 학습이 게임처럼 느껴집니다!',
        'onboarding_7_joined': '수천 명의 학습자가 가입함',
        'onboarding_next': '다음',
        'onboarding_skip': '건너뛰기',
        'compare_plans': '무료 vs 프리미엄 비교',
        'hide_comparison': '요금제 비교 숨기기',
        'age_under_14': '14세 미만',
        'age_15_18': '15 - 18',
        'age_19_25': '19 - 25',
        'age_26_35': '26 - 35',
        'age_36_50': '36 - 50',
        'age_over_50': '50세 이상'
    }
}

def escape_sql(text):
    return text.replace("'", "''")

def get_translation(lang, key, en_val):
    if lang in translations_all and key in translations_all[lang]:
        return translations_all[lang][key]
    return en_val

def main():
    output_file = 'scripts/sql/onboarding_translations_all.sql'
    os.makedirs(os.path.dirname(output_file), exist_ok=True)
    
    with open(output_file, 'w', encoding='utf-8') as f:
        for lang in langs:
            f.write(f"-- Translations for {lang}\n")
            for key, en_val in refs.items():
                val = get_translation(lang, key, en_val)
                sql = f"INSERT INTO ui_translations (lang, key, value) VALUES ('{lang}', '{key}', '{escape_sql(val)}') ON CONFLICT (lang, key) DO UPDATE SET value = EXCLUDED.value;\n"
                f.write(sql)
            f.write("\n")

if __name__ == "__main__":
    main()
