import sys
import re
import json
import requests
import urllib.parse
import time
import os

LANGS = ['ar', 'bg', 'cs', 'da', 'de', 'el', 'en', 'es', 'et', 'fi', 'fr', 'ga', 'hi', 'hr', 'hu', 'id', 'it', 'ja', 'ko', 'lt', 'lv', 'mt', 'nl', 'pl', 'pt', 'ro', 'sk', 'sl', 'sv', 'tl', 'tr', 'uk', 'vi', 'zh']

def translate_text(text, target_lang):
    if not text: return ""
    if target_lang == 'en': return text
    if target_lang == 'zh': target_lang = 'zh-CN'
    
    url = f"https://translate.googleapis.com/translate_a/single?client=gtx&sl=en&tl={target_lang}&dt=t&q={urllib.parse.quote(text)}"
    try:
        r = requests.get(url, timeout=10)
        if r.status_code == 200:
            res = r.json()
            translated = ''.join([item[0] for item in res[0]])
            return translated
        else:
            time.sleep(1)
            r = requests.get(url, timeout=10)
            if r.status_code == 200:
                res = r.json()
                translated = ''.join([item[0] for item in res[0]])
                return translated
            print(f"  [!] HTTP {r.status_code} translating '{text}' to {target_lang}. Retaining original text.")
            return text 
    except Exception as e:
        print(f"  [!] Error translating '{text}' to {target_lang}: {e}. Retaining original text.")
        return text 

def main():
    if len(sys.argv) < 2:
        print("Usage: python3 translate_clean_sql.py <path_to_clean_sql_file>")
        sys.exit(1)
        
    input_file = sys.argv[1]
    
    if not os.path.exists(input_file):
        print(f"File not found: {input_file}")
        sys.exit(1)

    print(f"Reading {input_file}...")
    with open(input_file, 'r', encoding='utf-8') as f:
        content = f.read()

    # Regex to find UPDATE statements generated by our previous script
    pattern = r"UPDATE cards\nSET localized_data = '(.*?)'::jsonb\nWHERE id = '(.*?)';"
    matches = list(re.finditer(pattern, content, re.DOTALL))
    
    if not matches:
        print("No valid SQL UPDATE statements found in the file.")
        sys.exit(1)
        
    print(f"Found {len(matches)} cards to translate.")
    
    out_filename = input_file.replace(".sql", "_translated.sql")
    
    out_f = open(out_filename, 'w', encoding='utf-8')
    
    trans_cache = {} 

    for idx, match in enumerate(matches):
        json_str_escaped = match.group(1)
        card_id = match.group(2)
        
        # Unescape single quotes
        json_str = json_str_escaped.replace("''", "'")
        
        try:
            data = json.loads(json_str)
        except json.JSONDecodeError as e:
            print(f"  [!] Failed to parse JSON for card {card_id}: {e}")
            out_f.write(match.group(0) + "\n\n") # Write original unchanged
            continue
            
        global_data = data.get("global", {})
        answer_en = global_data.get("answer", "").strip()
        prompt_en = global_data.get("prompt", "").strip()
        
        print(f"[{idx+1}/{len(matches)}] Translating card: {answer_en or '<No Answer>'} ({card_id})")
        
        for lang in LANGS:
            if lang not in data:
                data[lang] = {}
                
            # Translate answer
            if answer_en:
                cache_key = f"ans_{answer_en}_{lang}"
                if cache_key not in trans_cache:
                    trans_cache[cache_key] = translate_text(answer_en, lang)
                data[lang]["answer"] = trans_cache[cache_key]
            else:
                data[lang]["answer"] = ""
                
            # Translate prompt if exists
            if prompt_en:
                cache_key = f"pr_{prompt_en}_{lang}"
                if cache_key not in trans_cache:
                    trans_cache[cache_key] = translate_text(prompt_en, lang)
                data[lang]["prompt"] = trans_cache[cache_key]
            elif "prompt" in data[lang]: 
                # If prompt isn't in global, ensure it isn't set
                data[lang]["prompt"] = ""
                
        # Re-serialize to JSON and escape single quotes for SQL
        new_json_str = json.dumps(data, indent=2, ensure_ascii=False).replace("'", "''")
        new_sql = f"UPDATE cards\nSET localized_data = '{new_json_str}'::jsonb\nWHERE id = '{card_id}';"
        
        out_f.write(new_sql + "\n\n")
        
        # Sleep briefly to prevent API rate limits
        time.sleep(0.3)

    out_f.close()
    print(f"\nDone! Translated SQL saved to: {out_filename}")

if __name__ == "__main__":
    main()
