-- user_subscriptions table for cross-platform billing (Android + Web)
CREATE TABLE IF NOT EXISTS public.user_subscriptions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  status TEXT NOT NULL DEFAULT 'inactive', -- 'active', 'inactive', 'expired', 'canceled'
  provider TEXT NOT NULL, -- 'google_play', 'stripe', 'system'
  expiry_date TIMESTAMPTZ,
  purchase_token TEXT, -- Token from Google or Stripe subscription ID
  order_id TEXT, -- Order ID from provider
  product_id TEXT, -- The subscription SKU/Price ID
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(user_id)
);

-- invitations table for tracking user invites
CREATE TABLE IF NOT EXISTS public.invitations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  email TEXT NOT NULL,
  invited_by UUID REFERENCES auth.users(id),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- feedbacks table for the feedback system
CREATE TABLE IF NOT EXISTS public.feedbacks (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  type TEXT NOT NULL, -- 'bug', 'suggestion', 'other'
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'open', -- 'open', 'replied', 'closed'
  attachment_urls TEXT[],
  metadata JSONB DEFAULT '{}',
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- feedback_replies table for feedback conversation
CREATE TABLE IF NOT EXISTS public.feedback_replies (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  feedback_id UUID REFERENCES public.feedbacks(id) ON DELETE CASCADE NOT NULL,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  content TEXT NOT NULL,
  attachment_urls TEXT[],
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE public.user_subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.invitations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.feedbacks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.feedback_replies ENABLE ROW LEVEL SECURITY;

-- Policies: User Subscriptions
DROP POLICY IF EXISTS "Users can view own subscription" ON public.user_subscriptions;
CREATE POLICY "Users can view own subscription" ON public.user_subscriptions FOR SELECT USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Service role full access" ON public.user_subscriptions;
CREATE POLICY "Service role full access" ON public.user_subscriptions FOR ALL TO service_role USING (true);

-- Policies: Invitations
DROP POLICY IF EXISTS "Users can view own invitations" ON public.invitations;
CREATE POLICY "Users can view own invitations" ON public.invitations FOR SELECT USING (auth.uid() = invited_by);

-- Policies: Feedbacks
DROP POLICY IF EXISTS "Users can view own feedbacks" ON public.feedbacks;
CREATE POLICY "Users can view own feedbacks" ON public.feedbacks FOR SELECT USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can insert own feedback" ON public.feedbacks;
CREATE POLICY "Users can insert own feedback" ON public.feedbacks FOR INSERT WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Admin can view all feedbacks" ON public.feedbacks;
CREATE POLICY "Admin can view all feedbacks" ON public.feedbacks FOR SELECT USING (auth.uid() = 'f2fb4c9c-169b-447d-b8a6-dce72c4ed5ac');

DROP POLICY IF EXISTS "Admin can update all feedbacks" ON public.feedbacks;
CREATE POLICY "Admin can update all feedbacks" ON public.feedbacks FOR UPDATE USING (auth.uid() = 'f2fb4c9c-169b-447d-b8a6-dce72c4ed5ac');

-- Policies: Feedback Replies
DROP POLICY IF EXISTS "Users can view replies to their own feedback" ON public.feedback_replies;
CREATE POLICY "Users can view replies to their own feedback" 
ON public.feedback_replies FOR SELECT 
USING (
  EXISTS (
    SELECT 1 FROM public.feedbacks 
    WHERE feedbacks.id = feedback_replies.feedback_id 
    AND feedbacks.user_id = auth.uid()
  )
);

DROP POLICY IF EXISTS "Users can insert replies to their own feedback" ON public.feedback_replies;
CREATE POLICY "Users can insert replies to their own feedback" 
ON public.feedback_replies FOR INSERT 
WITH CHECK (
  EXISTS (
    SELECT 1 FROM public.feedbacks 
    WHERE feedbacks.id = feedback_replies.feedback_id 
    AND feedbacks.user_id = auth.uid()
  )
);

DROP POLICY IF EXISTS "Admin can view all replies" ON public.feedback_replies;
CREATE POLICY "Admin can view all replies" ON public.feedback_replies FOR SELECT USING (auth.uid() = 'f2fb4c9c-169b-447d-b8a6-dce72c4ed5ac');

DROP POLICY IF EXISTS "Admin can insert replies" ON public.feedback_replies;
CREATE POLICY "Admin can insert replies" ON public.feedback_replies FOR INSERT WITH CHECK (auth.uid() = 'f2fb4c9c-169b-447d-b8a6-dce72c4ed5ac');

-- Trigger for updated_at
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

DROP TRIGGER IF EXISTS update_user_subscriptions_updated_at ON public.user_subscriptions;
CREATE TRIGGER update_user_subscriptions_updated_at BEFORE UPDATE ON public.user_subscriptions FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

DROP TRIGGER IF EXISTS update_feedbacks_updated_at ON public.feedbacks;
CREATE TRIGGER update_feedbacks_updated_at BEFORE UPDATE ON public.feedbacks FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
